#!/usr/bin/env bash
#
# NorNet Logo Script
# Copyright (C) 2018-2024 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY# without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

# Bash options:
set -e

RESOLUTION="1920x1080"

make generate_overlayImage-${RESOLUTION}.png

result=$(find . -name "Overlay-${RESOLUTION}.png")
if [ -e "${result}" ] ; then
   echo "==> ${result}"
else
   echo "Something went wrong!"
   exit 1
fi
