#!/usr/bin/env bash
#
# Template VM Image Builder
# Copyright (C) 2017-2022 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

set -e

DESTINATIONS="nornetpp@odin.simula.nornet:images/ nornetpp@openstack.simula.nornet:images/"
SSH_PROXY="128.39.37.188"

source ./directories.config

imageFiles=""
VMs=`find ${OUTPUT_DIRECTORY} -mindepth 1 -maxdepth 1 -type d -name "QEMU*OpenStack*"`
for vm in ${VMs} ; do
   pushd ${vm} >/dev/null
   if [ -e "successfully-built.txt" ] ; then
      imageDirectory=`find . -mindepth 1 -maxdepth 1 -type d -name "*OpenStack*"`
      if [ -d "${imageDirectory}" ] ; then
         pushd ${imageDirectory} >/dev/null
         image=`ls -S .`
         if [ -e "${image}" ] ; then
            for destination in ${DESTINATIONS} ; do
               echo  "rsync -e \"ssh -4J ${SSH_PROXY}\" -vz --partial --info=progress2 `realpath ${image}` ${destination}${image}.qcow2"
               sh -c "rsync -e \"ssh -4J ${SSH_PROXY}\" -vz --partial --info=progress2 `realpath ${image}` ${destination}${image}.qcow2" &
            done
            imageFiles="${imageFiles} ${image}.qcow2"
         fi
         popd >/dev/null
      fi
   fi
   popd >/dev/null
   sleep 1
done
wait


echo ""
echo "------ OpenStack commands: ------"
for imageFile in ${imageFiles} ; do
   imageName="${imageFile/.qcow2/}"
   echo "image delete ${imageName}"
   echo "image create ${imageName} --file images/${imageFile} --disk-format qcow2 --container-format bare --property hw_firmware_type=uefi --property architecture=amd64 --public"
done
