#!/usr/bin/env bash
#
# Template VM Image Builder
# Copyright (C) 2017-2020 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

set -e

source ./directories.config

VMs=`find ${OUTPUT_DIRECTORY} -mindepth 1 -maxdepth 1 -type d -name "VirtualBox-HAW*"`
for vm in ${VMs} ; do
   if [ -e "${vm}/successfully-built.txt" ] ; then
      imageDirectory=`find ${vm} -mindepth 1 -maxdepth 1 -type d -name "HAW*"`
      if [ -d "${imageDirectory}" ] ; then
         image=`find ${imageDirectory} -name "*.ova"`
         if [ -e "${image}" ] ; then
            ls -l ${image}
            vmDate=`date -r "${image}" +"%Y-%m-%d"`
            # rclone mkdir "haw:Virtual Machines/VirtualBox-HAW-${vmDate}/"
            # rclone copy --progress "${image}" "haw:Virtual Machines/VirtualBox-HAW-${vmDate}/"
            # rsync -Pav "${image}" nornetpp@www.nntb.no:public_html/haw/
            rsync -e "ssh -J dreibh@oesthorn.nntb.no" -Pcv "${image}" nornetpp@kirkeveien.simula.nornet:/filesrv/adm/packages/haw/
         fi
      fi
   fi
done
