#!/usr/bin/env bash
#
# Template VM Image Builder
# Copyright (C) 2017-2025 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

set -eu

source ./directories.config

mkdir -p links/
rm -f links/*

VMs=$(find ${OUTPUT_DIRECTORY} -mindepth 1 -maxdepth 1 -type d -name "VirtualBox-*")
for vm in ${VMs} ; do
   if [ -e "${vm}/successfully-built.txt" ] ; then
      image=$(find "${vm}" -mindepth 2 -maxdepth 2 -name "*.ova")
      if [ -e "${image}" ] ; then
         ls -l "${image}"
         ln -s "${image}" links/
         # cp -a "${image}" links/
      fi
   fi
done
