#!/usr/bin/env bash
#
# Template VM Image Builder
# Copyright (C) 2017-2020 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

set -e

. ./vm-build-helper

HYPERVISOR="VirtualBox"
SYSTEMS="Ubuntu-18.04-LTS Ubuntu-20.04-LTS Fedora-31 Fedora-32"
SYSTEMS="Ubuntu-20.04-LTS"

# ------ Parameters ---------------------------------------
PROJECTS="NEAT"
HOSTNAME="brunost.simula.nornet"
USER_NAME="nornetpp"
USER_PASSWORD="neat4me!"
USER_REALNAME="NorNet Praesum Presum"

CORES=6
MEMORY=4096
DISK_ROOT=32768
DISK_HOME=65536
DISK_SWAP=2048
VIDEO="FHD"
BACKGROUND_SDDM="/usr/share/neat-desktop/desktop/NEATManagement1-3840x2160-mosaic.jpeg"
BACKGROUND_LOCKSCREEN="/usr/share/neat-desktop/desktop/NEATDesktop1-3840x2160-mosaic.jpeg"
BACKGROUND_DESKTOP="/usr/share/neat-desktop/desktop/NEATDesktop1-3840x2160-plain.jpeg"
OPTIONS=""
# ---------------------------------------------------------

build-defined-vms
