#!/usr/bin/env bash
# ==========================================================================
#    __   ____  __   ___                       ___      _ _    _
#    \ \ / /  \/  | |_ _|_ __  __ _ __ _ ___  | _ )_  _(_) |__| |___ _ _
#     \ V /| |\/| |  | || '  \/ _` / _` / -_) | _ \ || | | / _` / -_) '_|
#      \_/ |_|  |_| |___|_|_|_\__,_\__, \___| |___/\_,_|_|_\__,_\___|_|
#                                  |___/
#
#   --- Virtual Machine Image Builder and System Installation Scripts ---
#            https://www.nntb.no/~dreibh/vmimage-builder-scripts/
# ==========================================================================
#
# VM Image Builder Scripts
# Copyright (C) 2017-2026 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

# Bash options:
set -euo pipefail


. ./vm-build-helper
. ./supported-systems.config


HYPERVISOR="VirtualBox"
SYSTEMS=( "${DEFAULT_SYSTEMS_CURRENT[@]}" )
# SYSTEMS="Ubuntu-26.04 Debian-13 Fedora-44 FreeBSD-15.1-RELEASE"

# ------ Parameters ---------------------------------------
PROJECTS="HAW-Router HAW-Desktop"
# HOSTNAME="baumwall.haw.nornet"
USER_NAME="student"
USER_PASSWORD="b00tloader"
USER_REALNAME="HAW-Student"

CHIPSET=ich9
FIRMWARE=efi
CORES=4
MEMORY=4096
BALLOON=2048
DISK_ROOT=32768
DISK_HOME=65536
DISK_SWAP=2048
BOOTSPLASH=""
BACKGROUND_SDDM="/usr/share/simulamet/Desktop-with-Logo/3840x2160/mosaic/Hamburg1.jpeg"
BACKGROUND_LOCKSCREEN="/usr/share/simulamet/Desktop-with-Logo/3840x2160/mosaic/Hamburg2.jpeg"
BACKGROUND_DESKTOP="/usr/share/simulamet/Desktop-with-Logo/3840x2160/plain/Hamburg2.jpeg"
OPTIONS=""

# Explicitly set full-HD for boot screen:
VIDEO="FHD"
# ---------------------------------------------------------

for project in ${PROJECTS} ; do
   if [ "${project}" == "HAW-Desktop" ] ; then
      HOSTNAME="baumwall.haw.nornet"
      CORES=4
      MEMORY=4096
      BALLOON=2048
   else
      HOSTNAME="reeperbahn.haw.nornet"
      CORES=2
      MEMORY=2048
      BALLOON=1024
   fi
   PROJECTS="${project}"
   # shellcheck disable=SC2119
   build-defined-vms &
done
wait
