#!/usr/bin/env bash
# ==========================================================================
#  ___         _        _ _      _   _            ___         _      _
# |_ _|_ _  __| |_ __ _| | |__ _| |_(_)___ _ _   / __| __ _ _(_)_ __| |_ ___
#  | || ' \(_-<  _/ _` | | / _` |  _| / _ \ ' \  \__ \/ _| '_| | '_ \  _(_-<
# |___|_||_/__/\__\__,_|_|_\__,_|\__|_\___/_||_| |___/\__|_| |_| .__/\__/__/
#                                                              |_|
#
#   --- Virtual Machine Image Builder and System Installation Scripts ---
#            https://www.nntb.no/~dreibh/vmimage-builder-scripts/
# ==========================================================================
#
# System Installation Scripts
# Copyright (C) 2017-2026 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

# Bash options:
set -euo pipefail


# ###### Install OpenSans fonts #############################################
install-opensans-fonts ()
{
   local fontsDirectory="$1"
   local temporaryDirectory

   temporaryDirectory="$(mktemp -d /tmp/opensans-install.XXXXXX)"
   pushd "${temporaryDirectory}" >/dev/null
   curl -L -o opensans.zip "https://github.com/googlefonts/opensans/archive/refs/heads/main.zip"
   unzip -q opensans.zip
   sudo mkdir -p "$fontsDirectory"
   sudo cp opensans-main/fonts/ttf/*.ttf "$fontsDirectory"
   sudo fc-cache -f "$fontsDirectory"
   popd >/dev/null

   rm -rf "${temporaryDirectory}"
}


# ###### Main program #######################################################

# ====== Check/set environment variables ====================================
if [ "$(id -u)" -eq 0 ] && [ -v SUDO_USER ] ; then
   # Running as ROOT!
   USER_NAME="${SUDO_USER}"
else
   USER_NAME="$(id -un)"
fi
USER_REALNAME="$(getent passwd "${USER_NAME}" | cut -d":" -f5 | cut -d"," -f1)"
if [ "${USER_REALNAME}" == "" ] ; then
   USER_REALNAME="${USER_NAME}"
fi

# ====== Obtain system details ==============================================
UNAME="$(uname)"
NAME="${UNAME}"
ID="${UNAME,,}"
VERSION="$(uname -r)"
VERSION_ID="${VERSION/_*/}"
if [ -f /etc/os-release ] ; then
   . /etc/os-release
fi


# ====== Handle command-line parameters =====================================
if [ $# -lt 1 ] ; then
   echo >&2 "Usage: $0 project"
   echo >&2 "Example: $0 HiPerConTracer"
   exit 1
fi
PROJECT="$1"
shift 1
while [ $# -gt 0 ] ; do
   if [ "$1" == "--username" ] || [ "$1" == "-u" ] ; then
      USER_NAME="$2"
      shift
   elif [ "$1" == "--realname" ] || [ "$1" == "-r" ] ; then
      USER_REALNAME="$2"
      shift
   else
      echo >&2 "ERROR: Unknown option $1!"
      echo >&2 "Usage: $0"
      echo >&2 "   [--user|-u username]"
      echo >&2 "   [--realname|-r real_user_name]"
      exit 1
   fi
   shift
done


# ====== Get provisioners ===================================================
# Defaults, to be overwritten by the actual configuration:
VIDEO="1024x768"
KEYBOARD_MODEL="pc105"
KEYBOARD_LAYOUTS="de:nodeadkeys no us"
LOCALES="de_DE en_US nb_NO"
TIMEZONE="Europe/Oslo"
BOOTSPLASH=""
BACKGROUND_SDDM=""
BACKGROUND_LOCKSCREEN=""
BACKGROUND_DESKTOP=""

pushd >/dev/null projects
CONFIG="${PROJECT}.config"
if [ ! -e "${CONFIG}" ] ; then
   echo >&2 "ERROR: Project configuration ${CONFIG} not found!"
   exit 1
fi
PROVISIONERS=""
# shellcheck disable=SC1090
. ./"${CONFIG}"
PROVISIONERS="$(echo "${PROVISIONERS}" | xargs -n1 | sort -u)"
popd >/dev/null

LOCALES="$(echo "${LOCALES}" | tr "," " " | xargs -n1 | sort | xargs)"
KEYBOARD_LAYOUTS="$(echo "${KEYBOARD_LAYOUTS}" | tr "," " " | xargs)"
if [ "${VIDEO}" == "XGA" ] ; then
   VIDEO="1024x768"   # Standard, 4:3
elif [ "${VIDEO}" == "SXGA" ] ; then
   VIDEO="1280x960"   # SXGA, 4:3
elif [ "${VIDEO}" == "HD" ] ; then
   VIDEO="1280x720"   # HD, 16:9
elif [ "${VIDEO}" == "HD+" ] ; then
   VIDEO="1600x900"   # HD+, 16:9
elif [ "${VIDEO}" == "FHD" ] ; then
   VIDEO="1920x1080"  # Full HD, 16:9
elif [ "${VIDEO}" == "UHD" ] ; then
   VIDEO="3840x2160"  # 4K, 16:9
fi
if [ "${VIDEO}" != "NA" ] ; then
   if [[ ! "${VIDEO}" =~ ^[0-9]+x[0-9]+$ ]] ; then
      echo >&2 "ERROR: Bad video setting: ${VIDEO}"
      exit 1
   fi
fi


# ====== Print configuration ================================================
echo "Configuration:"
echo " - VIDEO=${VIDEO}"
echo " - BOOTSPLASH=${BOOTSPLASH}"
echo " - BACKGROUND_SDDM=${BACKGROUND_SDDM}"
echo " - BACKGROUND_LOCKSCREEN=${BACKGROUND_LOCKSCREEN}"
echo " - BACKGROUND_DESKTOP=${BACKGROUND_DESKTOP}"
echo " - KEYBOARD_MODEL=${KEYBOARD_MODEL}"
echo " - KEYBOARD_LAYOUTS=${KEYBOARD_LAYOUTS}"
echo " - LOCALES=${LOCALES}"
echo " - TIMEZONE=${TIMEZONE}"


# ====== Ensure that the generated files are there ==========================
pushd >/dev/null files

# ------ Get background build dependencies, and generate the backgrounds ----
if [ "${ID}" == "ubuntu" ] || [ "${ID}" == "debian" ] ; then
   # Note: gcc and libc6-dev are needed by GNUInstallDirs.
   sudo env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      cmake fonts-open-sans gcc gimp git graphicsmagick libc6-dev libimage-exiftool-perl make
elif [ "${ID}" == "fedora" ] ; then
   sudo dnf install --setopt=install_weak_deps=False -y \
      awk cmake gcc git GraphicsMagick gimp open-sans-fonts perl-Image-ExifTool
   sudo fc-cache -f
elif [[ "${ID}" =~ ^opensuse- ]] ; then
   sudo zypper --non-interactive install \
      --force-resolution --allow-vendor-change --allow-name-change \
      --no-recommends -y \
      awk cmake exiftool gcc git GraphicsMagick gimp google-opensans-fonts
elif [ "${ID}" == "alpine" ] ; then
   sudo apk add cmake exiftool font-opensans gawk gcc git gimp graphicsmagick make musl-dev
elif [ "${ID}" == "freebsd" ] ; then
   sudo pkg install -y \
      cmake flock getopt gimp3-app git GraphicsMagick opensans-ttf p5-Image-ExifTool
   sudo fc-cache -f
elif [ "${ID}" == "netbsd" ] ; then
   sudo pkgin -y install cmake getopt gimp git GraphicsMagick p5-Image-ExifTool
   if [ -z "$(fc-list : family style -f "%{family[0]} %{style[0]}\n" | grep "^Open Sans")" ] ; then
      install-opensans-fonts "/usr/pkg/share/fonts/X11/TTF"
   fi
elif [ "${ID}" == "openbsd" ] ; then
   sudo pkg_add -r -I cmake flock "$(pkg_info -z "gimp->=3")" git gnugetopt GraphicsMagick p5-Image-ExifTool unzip--
   if [ -z "$(fc-list : family style -f "%{family[0]} %{style[0]}\n" | grep "^Open Sans")" ] ; then
      install-opensans-fonts "/usr/local/share/fonts"
   fi
elif [ "${ID}" == "sunos" ] ; then
   sudo pkg install pkg://openindiana.org/developer/build/cmake gcc-14 gimp git gnu-getopt graphicsmagick image-exiftool || [ $? -eq 4 ]
   if [ -z "$(fc-list : family style -f "%{family[0]} %{style[0]}\n" | grep "^Open Sans")" ] ; then
      install-opensans-fonts "/usr/share/fonts/TrueType"
   fi
fi
if [ -z "$(fc-list : family style -f "%{family[0]} %{style[0]}\n" | grep "^Open Sans")" ] ; then
   echo >&2 "ERROR: Open Sans fonts are not available!"
   exit 1
fi
./generate-backgrounds

popd >/dev/null


# ====== Run provisioners ===================================================
for provisioner in ${PROVISIONERS} ; do
   echo ""
   echo -e "\x1b[34mRunning ${provisioner} ...\x1b[0m"
   echo ""

   if [ -e "files/${provisioner}" ] ; then
      while read -r s destination ; do
         if [ "${s}" != "" ] && [[ ! "${s}" =~ ^# ]] ; then
            source="$(realpath files/"${s}")"
            if [ ! -e "${source}" ] ; then
               echo >&2 "ERROR: Cannot find source file ${source} in files/${provisioner}!"
               exit 1
            fi
            if [ "${destination}" == "" ] ; then
               echo >&2 "ERROR: Destination has to be provided in files/${provisioner}!"
               exit 1
            fi
            if [[ "${destination}" =~ [/]$ ]] ; then
               mkdir -p "${destination}"
            else
               mkdir -p "$(dirname "${destination}")"
            fi
            echo "Copying ${source} to ${destination} ..."
            cp "${source}" "${destination}"
         fi
      done <"files/${provisioner}"
   fi

   sudo env \
      VIDEO="${VIDEO}" \
      USER_NAME="${USER_NAME}" \
      USER_REALNAME="${USER_REALNAME}" \
      KEYBOARD_MODEL="${KEYBOARD_MODEL}" \
      KEYBOARD_LAYOUTS="${KEYBOARD_LAYOUTS}" \
      LOCALES="${LOCALES}"  \
      TIMEZONE="${TIMEZONE}" \
      BOOTSPLASH="${BOOTSPLASH}" \
      BACKGROUND_SDDM="${BACKGROUND_SDDM}" \
      BACKGROUND_LOCKSCREEN="${BACKGROUND_LOCKSCREEN}" \
      BACKGROUND_DESKTOP="${BACKGROUND_DESKTOP}" \
      "scripts/${provisioner}"
done
