#!/usr/bin/env bash
#
# Template VM Image Builder
# Copyright (C) 2017-2020 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

set -e

. ./vm-build-helper

HYPERVISOR="VirtualBox"
SYSTEMS="Ubuntu-18.04-LTS Ubuntu-20.04-LTS Ubuntu-20.10 Fedora-32 Fedora-33"
# SYSTEMS="Ubuntu-20.04-LTS"

# ------ Parameters ---------------------------------------
PROJECTS="HAW-Router HAW-Desktop"
# HOSTNAME="baumwall.haw.nornet"
USER_NAME="student"
USER_PASSWORD="b00tloader"
USER_REALNAME="HAW-Student"

# CORES=4
# MEMORY=4096
DISK_ROOT=32768
DISK_HOME=65536
DISK_SWAP=2048
VIDEO="FHD"
BACKGROUND_SDDM="/usr/share/simulamet/Desktop-with-Logo/3840x2160/mosaic/Hamburg1.jpeg"
BACKGROUND_LOCKSCREEN="/usr/share/simulamet/Desktop-with-Logo/3840x2160/mosaic/Hamburg2.jpeg"
BACKGROUND_DESKTOP="/usr/share/simulamet/Desktop-with-Logo/3840x2160/plain/Hamburg2.jpeg"
OPTIONS=""
# ---------------------------------------------------------

for project in ${PROJECTS} ; do
   if [ "${project}" == "HAW-Desktop" ] ; then
      HOSTNAME="baumwall.haw.nornet"
      CORES=4
      MEMORY=4096
   else
      HOSTNAME="reeperbahn.haw.nornet"
      CORES=2
      MEMORY=2048
   fi
   PROJECTS="${project}"
   build-defined-vms &
done
wait
