#!/usr/bin/env bash
#
# Template VM Image Builder
# Copyright (C) 2017-2024 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

set -eu


# ###### Handle command-line parameters #####################################
if [ $# -lt 1 ] ; then
   echo >&2 "Usage: $0 project"
   echo >&2 "Example: $0 HiPerConTracer"
   exit 1
fi

USER_NAME="nornetpp"
USER_REALNAME="NorNet Praesum Presum"

BOOTSPLASH="/usr/share/bootsplash/Bjørnsund-3840x2160.jpeg"
BACKGROUND_SDDM="/usr/share/desktop/Nordmarka-3840x2160-mosaic.jpeg"
BACKGROUND_LOCKSCREEN="/usr/share/desktop/Flåm-3840x2160-mosaic.jpeg"
BACKGROUND_DESKTOP="/usr/share/desktop/Flåm-3840x2160-plain.jpeg"


# ###### Get provisioners ###################################################
pushd >/dev/null projects
CONFIG="$1.config"
if [ ! -e "${CONFIG}" ] ; then
   echo >&2: "ERROR: Project configuration ${CONFIG} not found!"
   exit 1
fi
PROVISIONERS=""
. ./"${CONFIG}"
PROVISIONERS="$(echo "${PROVISIONERS}" | xargs -n1 | sort -u)"
popd >/dev/null


# ###### Run provisioners ###################################################
for provisioner in ${PROVISIONERS} ; do
   echo ""
   echo -e "\x1b[34mRunning ${provisioner} ...\x1b[0m"
   echo ""

   sudo env \
      USER_NAME="${USER_NAME}" \
      USER_REALNAME="${USER_REALNAME}" \
      BOOTSPLASH="${BOOTSPLASH}" \
      BACKGROUND_SDDM="${BACKGROUND_SDDM}" \
      BACKGROUND_LOCKSCREEN="${BACKGROUND_LOCKSCREEN}" \
      BACKGROUND_DESKTOP="${BACKGROUND_DESKTOP}" \
      "scripts/${provisioner}"
done
