#!/usr/bin/env bash
#
# Template VM Image Builder
# Copyright (C) 2017-2024 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

set -e

. ./vm-build-helper

HYPERVISOR="Proxmox"
SYSTEMS="Ubuntu-18.04-LTS Ubuntu-20.04-LTS Ubuntu-22.04-LTS Ubuntu-24.04-LTS   Ubuntu-23.10   Debian-11 Debian-12   Fedora-38 Fedora-39"
SYSTEMS="Ubuntu-18.04-LTS Ubuntu-20.04-LTS Ubuntu-22.04-LTS   Ubuntu-23.10   Debian-11 Debian-12   Fedora-38 Fedora-39"
SYSTEMS="Ubuntu-22.04-LTS"

# ------ Parameters ---------------------------------------
PROJECTS="NorNet NorNet-Desktop"

HOSTNAME="akerbrygge.simula.nornet"
USER_NAME="nornetpp"
USER_PASSWORD="!NorNetInst!"
USER_REALNAME="NorNet Praesum Presum"

CHIPSET=ich9
FIRMWARE=efi
CORES=4
MEMORY=2048
DISK_ROOT=16384
DISK_HOME=8192
DISK_SWAP=2048
VIDEO="HD+"
OPTIONS="--proxmox $HOME/.config/proxmox.config"
BOOTSPLASH="/usr/share/bootsplash/Splash-Gressholmen-3840x2160.jpeg"
BACKGROUND_SDDM="/usr/share/nornet-desktop/Desktop-with-Logo/Server1-3840x2160-plain.jpeg"
BACKGROUND_LOCKSCREEN="/usr/share/nornet-desktop/Desktop-with-Logo/FileSrv1-3840x2160-plain.jpeg"
BACKGROUND_DESKTOP="/usr/share/nornet-desktop/Desktop-with-Logo/Display1-3840x2160-plain.jpeg"
# ---------------------------------------------------------

files/generate-backgrounds
build-defined-vms
