#!/usr/bin/env bash
# ==========================================================================
#    __   ____  __   ___                       ___      _ _    _
#    \ \ / /  \/  | |_ _|_ __  __ _ __ _ ___  | _ )_  _(_) |__| |___ _ _
#     \ V /| |\/| |  | || '  \/ _` / _` / -_) | _ \ || | | / _` / -_) '_|
#      \_/ |_|  |_| |___|_|_|_\__,_\__, \___| |___/\_,_|_|_\__,_\___|_|
#                                  |___/
#
#   --- Virtual Machine Image Builder and System Installation Scripts ---
#            https://www.nntb.no/~dreibh/vmimage-builder-scripts/
# ==========================================================================
#
# VM Image Builder Scripts
# Copyright (C) 2017-2026 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

# Bash options:
set -euo pipefail


. ./vm-build-helper
. ./supported-systems.config


HYPERVISOR="vSphere"
SYSTEMS=( "${DEFAULT_SYSTEMS_CURRENT[@]}" )
# SYSTEMS="Ubuntu-24.04"

# ------ Parameters ---------------------------------------
PROJECTS="Minimal NorNet NorNet-Desktop"   #  NorNet-Desktop

HOSTNAME="tjuvholmen.simula.nornet"
USER_NAME="nornetpp"
USER_PASSWORD="!NorNetInst!"
USER_REALNAME="NorNet Praesum Presum"

CHIPSET=ich9
FIRMWARE=efi
CORES=4
MEMORY=2048
BALLOON=NA
DISK_ROOT=16384
DISK_HOME=8192
DISK_SWAP=2048
OPTIONS="--vsphere $HOME/.config/vsphere.config"
# ---------------------------------------------------------

files/generate-backgrounds
# shellcheck disable=SC2119
build-defined-vms
