#!/usr/bin/env bash
#
# Template VM Image Builder
# Copyright (C) 2017-2025 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

set -eu

. ./vm-build-helper
. ./supported-systems.config

HYPERVISOR="VirtualBox"
SYSTEMS="${DEFAULT_SYSTEMS_CURRENT}"
# SYSTEMS="Ubuntu-24.04-LTS"

# ------ Parameters ---------------------------------------
PROJECTS="NEAT"
HOSTNAME="brunost.simula.nornet"
USER_NAME="nornetpp"
USER_PASSWORD="neat4me!"
USER_REALNAME="NorNet Praesum Presum"

CHIPSET=ich9
FIRMWARE=efi
CORES=6
MEMORY=4096
BALLOON=2048
DISK_ROOT=32768
DISK_HOME=65536
DISK_SWAP=2048
VIDEO="FHD"
BOOTSPLASH=""
BACKGROUND_SDDM="/usr/share/neat-desktop/desktop/NEATManagement1-3840x2160-mosaic.jpeg"
BACKGROUND_LOCKSCREEN="/usr/share/neat-desktop/desktop/NEATDesktop1-3840x2160-mosaic.jpeg"
BACKGROUND_DESKTOP="/usr/share/neat-desktop/desktop/NEATDesktop1-3840x2160-plain.jpeg"
OPTIONS=""
# ---------------------------------------------------------

files/generate-backgrounds
# shellcheck disable=SC2119
build-defined-vms
