#!/usr/bin/env bash
#
# Template VM Image Builder
# Copyright (C) 2017-2025 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

set -eu

. ./vm-build-helper
. ./supported-systems.config

HYPERVISOR="Proxmox"
SYSTEMS="${DEFAULT_SYSTEMS_CURRENT}"
# SYSTEMS="Ubuntu-24.04-LTS"

# ------ Parameters ---------------------------------------
PROJECTS="Development"   # Development KDE KDE+Development

HOSTNAME="localhost"
USER_NAME="nornetpp"
USER_PASSWORD="!NorNetInst!"
USER_REALNAME="NorNet Praesum Presum"

CHIPSET=ich9
FIRMWARE=efi
CORES=4
MEMORY=4096
BALLOON=2048
DISK_ROOT=32768
DISK_HOME=16384
DISK_SWAP=4096
VIDEO="FHD"
OPTIONS="--proxmox $HOME/.config/proxmox.config"
BOOTSPLASH="/usr/share/bootsplash/Bjørnsund-3840x2160.jpeg"
BACKGROUND_SDDM="/usr/share/desktop/Nordmarka-3840x2160-mosaic.jpeg"
BACKGROUND_LOCKSCREEN="/usr/share/desktop/Flåm-3840x2160-mosaic.jpeg"
BACKGROUND_DESKTOP="/usr/share/desktop/Flåm-3840x2160-plain.jpeg"
# ---------------------------------------------------------

files/generate-backgrounds
build-defined-vms 60
