#!/usr/bin/env bash
#
# Template VM Image Builder
# Copyright (C) 2017-2024 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

set -e

. ./vm-build-helper

HYPERVISOR="VirtualBox"   # "VirtualBox" "QEMU"
SYSTEMS="FreeBSD-14.0-RELEASE" # FreeBSD-14.0-STABLE"

# ------ Parameters ---------------------------------------
PROJECTS="Minimal" # KDE"
# PROJECTS="Minimal"

HOSTNAME="burgsteinfurt.openstack"
USER_NAME="nornetpp"
USER_PASSWORD="!NorNetInst!"
USER_REALNAME="NorNet Praesum Presum"

CHIPSET=ich9
FIRMWARE=efi
CORES=4
MEMORY=4096
DISK_ROOT=65536
DISK_HOME=0   # Just one disk -> not used here!
DISK_SWAP=0   # Just one disk -> not used here!
VIDEO="1920x1080"
BOOTSPLASH="/usr/share/bootsplash/Splash-Gressholmen-3840x2160.jpeg"
BACKGROUND_SDDM="/usr/share/desktop/Nordmarka-3840x2160-mosaic.jpeg"
BACKGROUND_LOCKSCREEN="/usr/share/desktop/Flåm-3840x2160-mosaic.jpeg"
BACKGROUND_DESKTOP="/usr/share/desktop/Flåm-3840x2160-plain.jpeg"
OPTIONS="-1"   # Just one disk!
# ---------------------------------------------------------

files/generate-backgrounds
build-defined-vms
