#!/usr/bin/env bash
# ==========================================================================
#    __   ____  __   ___                       ___      _ _    _
#    \ \ / /  \/  | |_ _|_ __  __ _ __ _ ___  | _ )_  _(_) |__| |___ _ _
#     \ V /| |\/| |  | || '  \/ _` / _` / -_) | _ \ || | | / _` / -_) '_|
#      \_/ |_|  |_| |___|_|_|_\__,_\__, \___| |___/\_,_|_|_\__,_\___|_|
#                                  |___/
#
#   --- Virtual Machine Image Builder and System Installation Scripts ---
#            https://www.nntb.no/~dreibh/vmimage-builder-scripts/
# ==========================================================================
#
# VM Image Builder Scripts
# Copyright (C) 2017-2026 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

# Bash options:
set -euo pipefail


# ====== Handle arguments ===================================================
if [ $# -ne 1 ] ; then
   echo >&2 "Usage: $0 user@server"
   exit 1
fi
SERVER="${1//*@/}"
USER="${1//@*/}"
if [ "${USER}" == "${SERVER}" ] ; then
   USER="nornetpp"
fi

# ====== Obtain name and e-mail for Git configuration =======================
gitConfig="${HOME}/.gitconfig"
if [ -e "${gitConfig}" ] ; then
   GIT_NAME="$(grep "^[[:space:]]*name[[:space:]]*=" "${gitConfig}" | sed -e 's/^.*=[ \t]*//')"
   GIT_EMAIL="$(grep "^[[:space:]]*email[[:space:]]*=" "${gitConfig}" | sed -e 's/^.*=[ \t]*//')"
else
   GIT_NAME=""
   GIT_EMAIL=""
   echo >&2 "WARNING: Unable to determine Git user and email!"
fi

# ====== Configure server ===================================================
ssh-copy-id -i ~/.ssh/id_rsa -oStrictHostKeyChecking=no "${USER}@${SERVER}"
# shellcheck disable=SC2029
ssh -t "${USER}@${SERVER}" "
set -euo
UNAME=\"\$(uname)\"
NAME=\"\${UNAME}\"
ID=\$(echo \"\${UNAME}\" | tr '[:upper:]' '[:lower:]')
VERSION=\"\$(uname -r)\"
VERSION_ID=\"\${VERSION%%_*}\"
if [ -f /etc/os-release ] ; then
   . /etc/os-release
fi
if [ ! -e .gitconfig ] || grep -q -E '^[[:space:]]*name[[:space:]]*=[[:space:]]*NorNet Praesum Presum' .gitconfig ; then
   echo \"Updating .gitconfig:\"
   (
      echo \"[user]\"
      echo \"        name = ${GIT_NAME}\"
      echo \"        email = ${GIT_EMAIL}\"
      echo \"[push]\"
      echo \"        default = simple\"
      echo \"        autoSetupRemote = true\"
      echo \"[pull]\"
      echo \"        rebase = false\"
      echo \"[color]\"
      echo \"        ui = auto\"
   ) | tee .gitconfig
else
   echo \"Leaving .gitconfig unchanged!\"
fi
echo \"nornetpp ALL=(ALL) NOPASSWD:ALL\" | \
if [ -d /etc/sudoers.d ] ; then
   sudo tee /etc/sudoers.d/99-nornetpp
elif [ -d /usr/local/etc/sudoers.d ] ; then
   sudo tee /usr/local/etc/sudoers.d/99-nornetpp
elif [ -d /usr/pkg/etc/sudoers.d ] ; then
   sudo tee /usr/pkg/etc/sudoers.d/99-nornetpp
else
   echo >&2 \"ERROR: Unable to find location for sudoers configuration!\"
   exit 1
fi
if ! command -v git || ! command -v joe ; then
   case \"\${NAME}\" in
      ubuntu|debian)
         sudo apt install -y ca-certificates git joe
         ;;
      fedora)
         sudo dnf install -y git joe
         ;;
      opensuse-*)
         sudo zypper install -y git joe
         ;;
      alpine)
         sudo /sbin/apk add git joe
         ;;
      freebsd)
         sudo pkg install -y git joe
         ;;
      netbsd)
         sudo /usr/pkg/bin/pkgin -y install mozilla-rootcerts-openssl git joe
         ;;
      openbsd)
         sudo pkg_add git joe
         ;;
      SunOS)
         sudo pkg install git joe
         ;;
   esac
fi
mkdir -p ~/src
cd ~/src
if [ -d vmimage-builder-scripts ] ; then
   cd vmimage-builder-scripts
   git pull
else
   git clone https://dreibh@github.com/simula/nornet-vmimage-builder-scripts.git vmimage-builder-scripts
   cd vmimage-builder-scripts
fi
cd ~/src
if [ -d system-tools ] ; then
   cd system-tools
   git pull
else
   git clone https://dreibh@github.com/dreibh/system-tools.git system-tools
   cd system-tools
fi
"

# ====== Connect to server ==================================================
ssh "${USER}@${SERVER}"
