#!/usr/bin/env bash
#
# Template VM Image Builder
# Copyright (C) 2017-2025 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

set -eu


# ====== Handle arguments ===================================================
if [ $# -lt 1 ] ; then
   echo >&2 "Usage: $0 vm_address"
   exit 1
fi
user="${1//@*/}"
address="${1//*@/}"
if [ "${user}" == "${address}" ] ; then
   user="nornetpp"
fi

# ====== Obtain name and e-mail for Git configuration =======================
gitConfig="${HOME}/.gitconfig"
if [ -e "${gitConfig}" ] ; then
   GIT_NAME="$(grep "^[ \t]*name[ \t]*=" "${gitConfig}" | sed -e 's/^.*=[ \t]*//')"
   GIT_EMAIL="$(grep "^[ \t]*email[ \t]*=" "${gitConfig}" | sed -e 's/^.*=[ \t]*//')"
else
   GIT_NAME=""
   GIT_EMAIL=""
fi

# ====== Configure server ===================================================
ssh-copy-id -oStrictHostKeyChecking=no "${user}@${address}"
ssh "${user}@${address}" "
echo \"nornetpp ALL=(ALL) NOPASSWD:ALL\" | sudo tee /etc/sudoers.d/99-nornetpp
if ! which git || ! which joe ; then
   if [ -x /usr/bin/apt ] ; then
      sudo /usr/bin/apt install -y git joe
   elif [ -x /usr/bin/dnf ] ; then
      sudo /usr/bin/dnf install -y git joe
   elif [ -x /usr/bin/pkg ] ; then
      sudo /usr/bin/pkg install -y git joe
   fi
fi
if [ ! -d ~/src/vmimage-builder-scripts ] ; then
   git clone https://dreibh@github.com/simula/nornet-vmimage-builder-scripts ~/src/vmimage-builder-scripts
   cd ~/src/vmimage-builder-scripts
   git config pull.rebase true
   # git checkout dreibh/freebsd
fi
if [ ! -e ~/.gitconfig ] ; then
   (
      echo \"[user]\"
      echo \"        name = ${GIT_NAME}\"
      echo \"        email = ${GIT_EMAIL}\"
      echo \"[push]\"
      echo \"        default = simple\"
      echo \"        autoSetupRemote = true\"
      echo \"[pull]\"
      echo \"        rebase = false\"
      echo \"[color]\"
      echo \"        ui = auto\"
   ) >.gitconfig
fi
"

# ====== Connect to server ==================================================
ssh "${user}@${address}"
