#!/usr/bin/env bash
#
# Template VM Image Builder
# Copyright (C) 2017-2025 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

set -eu


# ====== Handle arguments ===================================================
if [ $# -ne 2 ] ; then
   echo >&2 "Usage: $0 user@server project"
   exit 1
fi
SERVER="${1//*@/}"
USER="${1//@*/}"
PROJECT="$2"
if [ "${USER}" == "${SERVER}" ] ; then
   USER="nornetpp"
fi

# ====== Obtain name and e-mail for Git configuration =======================
gitConfig="${HOME}/.gitconfig"
if [ -e "${gitConfig}" ] ; then
   GIT_NAME="$(grep "^[ \t]*name[ \t]*=" "${gitConfig}" | sed -e 's/^.*=[ \t]*//')"
   GIT_EMAIL="$(grep "^[ \t]*email[ \t]*=" "${gitConfig}" | sed -e 's/^.*=[ \t]*//')"
else
   GIT_NAME=""
   GIT_EMAIL=""
fi

# ====== Configure server ===================================================
ssh-copy-id "${USER}@${SERVER}"
# shellcheck disable=SC2029
ssh "${USER}@${SERVER}" "
if [ ! -e .gitconfig ] ; then
   (
      echo \"[user]\"
      echo \"        name = ${GIT_NAME}\"
      echo \"        email = ${GIT_EMAIL}\"
      echo \"[push]\"
      echo \"        default = simple\"
      echo \"        autoSetupRemote = true\"
      echo \"[pull]\"
      echo \"        rebase = false\"
      echo \"[color]\"
      echo \"        ui = auto\"
   ) >.gitconfig
fi
mkdir -p src
cd src
if [ -d vmimage-builder-scripts ] ; then
   cd vmimage-builder-scripts
   git pull
else
   git clone https://dreibh@github.com/simula/nornet-vmimage-builder-scripts.git vmimage-builder-scripts
   cd vmimage-builder-scripts
fi
cd files
if [ -x /usr/bin/apt ] ; then
   sudo /usr/bin/apt install -y --no-install-recommends cmake gawk gcc gcc-multilib graphicsmagick gimp libimage-exiftool-perl make
fi
./generate-backgrounds
cd ..
./make-direct \"${PROJECT}\"
"
