#!/usr/bin/env bash
#
# Template VM Image Builder
# Copyright (C) 2017-2025 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

set -eu


if [ $# -lt 1 ] ; then
   echo >&2 "Usage: $0 vm_address"
   exit 1
fi
user="${1//@*/}"
address="${1//*@/}"
if [ "${user}" == "${address}" ] ; then
   user="nornetpp"
fi


ssh-copy-id -oStrictHostKeyChecking=no "${user}@${address}"
ssh -t "${user}@${address}" '
echo "nornetpp ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/99-nornetpp
if ! which git || ! which joe ; then
   if [ -x /usr/bin/apt ] ; then
      sudo /usr/bin/apt install -y git joe
   elif [ -x /usr/bin/dnf ] ; then
      sudo /usr/bin/dnf install -y git joe
   elif [ -x /usr/bin/pkg ] ; then
      sudo /usr/bin/pkg install -y git joe
   fi
fi
if [ ! -d ~/src/vmimage-builder-scripts ] ; then
   git clone https://dreibh@github.com/simula/nornet-vmimage-builder-scripts ~/src/vmimage-builder-scripts
   cd ~/src/vmimage-builder-scripts
   git config pull.rebase true
   # git checkout dreibh/freebsd
fi
if [ ! -e ~/.gitconfig ] ; then
   cat >~/.gitconfig <<EOF
[user]
        name = Thomas Dreibholz
        email = thomas.dreibholz@gmail.com
[push]
        default = simple
[color]
        ui = auto
EOF
fi
'

ssh "${user}@${address}"
