#!/usr/bin/env bash
#
# Template VM Image Builder
# Copyright (C) 2017-2025 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

set -eu

source ./directories.config

CONTAINERS=$(find "${OUTPUT_DIRECTORY}" -mindepth 1 -maxdepth 1 -type d -name "Docker*")
for container in ${CONTAINERS} ; do
   json=$(find "${container}" -mindepth 1 -maxdepth 1 -type f -name "*.json")
   if [ "${json}" != "" ] ; then
      REPOSITORY="$(jq '."post-processors"[0]' "${json}" | jq '.[0].repository' | tr -d '"')"
      TAG="$(jq '."post-processors"[0]' "${json}" | jq '.[0].tags[0]' | tr -d '"')"
      if [ "${REPOSITORY}" != "" ] && [ "${TAG}" != "" ] ; then
         echo "Pushing ${REPOSITORY}:${TAG} ..."
         docker push "${REPOSITORY}":"${TAG}"
      fi
   fi
done
