#!/bin/sh

# Based on: https://github.com/stoned/packer-nbsd-boxes

export PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/pkg/sbin:/usr/pkg/bin

set -eux


# ====== Find disks =========================================================
# Disk names: sysctl hw.disknames
DISK_ROOT=""
for d in sd0 ; do
  if [ -e "/dev/$d" ]; then
    export DISK_ROOT=$d
    break
  fi
done
if [ "$DISK_ROOT" = "" ] ; then
   echo >&2 "ERROR: Root disk not found!"
   exit 1
fi

DISK_HOME=""
for d in sd1 ; do
  if [ -e "/dev/$d" ]; then
    export DISK_HOME=$d
    break
  fi
done
if [ "$DISK_HOME" = "" ] ; then
   echo >&2 "ERROR: Home disk not found!"
   exit 1
fi

DISK_SWAP=""
for d in sd2 ; do
  if [ -e "/dev/$d" ]; then
    export DISK_SWAP=$d
    break
  fi
done
if [ "$DISK_SWAP" = "" ] ; then
   echo >&2 "ERROR: Swap disk not found!"
   exit 1
fi


# ====== Partitioning =======================================================
# Root:
gpt create $DISK_ROOT
gpt add -t efi -s 64m $DISK_ROOT
gpt add -t ffs $DISK_ROOT
dkctl $DISK_ROOT listwedges
newfs_msdos /dev/rdk0
newfs -O 2 /dev/rdk1

# Home:
gpt create $DISK_HOME
gpt add -t ffs $DISK_HOME
dkctl $DISK_HOME listwedges
newfs -O 2 /dev/rdk2

# Swap:
gpt create $DISK_SWAP
gpt add -t swap $DISK_SWAP
dkctl $DISK_SWAP listwedges
swapctl -a /dev/dk3


# # disk partition
# cat <<EOF > /tmp/sed.$$
# /total sectors:/{
# s/.*sectors: //
# s/,.*//
# p
# q
# }
# EOF
# wd_size="$(fdisk wd0d | sed -n -f /tmp/sed.$$)"
# fdisk -i -a -0 -f -u -s 169/63/$(($wd_size - 63)) /dev/rwd0d
#
# # disklabel
# ram_size="$(sysctl -n hw.physmem)"
# swap_size="$(($ram_size / 512))"
# root_size="$(($wd_size - 63 - $swap_size))"
# disklabel -t wd0 > /tmp/disktab.$$ || true # XXX
# sed -e "s/generated label/generated label|mylabel/" \
#     -e "s/:pe#.*/:pa#$root_size:oa#63:ta=4.2BSD:ba#16384:fa#2048:pb#$swap_size:ob#$(($root_size + 63)):tb=swap:/" \
#     /tmp/disktab.$$ > /tmp/newdisktab.$$
# disklabel -w -f /tmp/newdisktab.$$ wd0 mylabel
#
# # newfs
# newfs -O 2 /dev/rwd0a


# ====== NetBSD installation ================================================

# ------ Mount filesystems --------------------------------------------------
r=/targetroot
mount /dev/dk1 $r
mkdir -p $r/boot/efi/EFI
mount /dev/dk0 $r/boot/efi/EFI
mkdir -p $r/home
mount /dev/dk2 $r/home

# ------ Extract sets -------------------------------------------------------
suffix=tgz
[ -f /amd64/binary/sets/base.tar.xz ] && suffix=tar.xz

# X11: xbase xcomp xetc xfont xserver
for s in base etc comp games kern-GENERIC man misc modules tests text ; do
  ( cd $r && echo $s && tar --chroot -zxpf /amd64/binary/sets/$s.$suffix )
done

# MAKEDEV
( cd $r/dev && sh ./MAKEDEV all )

# fstab
mkdir $r/kern
mkdir $r/proc
cat <<EOF > $r/etc/fstab
/dev/dk1 /            ffs     rw,log        1 1
/dev/dk0 /boot/efi    msdos   rw            0 0
/dev/dk2 /home        ffs     rw,log        1 2
/dev/dk2 none         swap    sw,dp         0 0
kernfs   /kern        kernfs  rw            0 0
procfs   /proc        procfs  rw            0 0
fdesc    /dev         fdesc   ro,-o=union   0 0
ptyfs    /dev/pts     ptyfs   rw            0 0
tmpfs    /tmp tmpfs   rw,-m1777,-sram%25
EOF


# ====== Boot loader ========================================================
mkdir -p $r/boot/efi/EFI/boot
cp /usr/mdec/bootx64.efi $r/boot/efi/EFI/BOOT/BOOTX64.EFI
cat > $r/boot/efi/EFI/BOOT/BOOT.CFG << EOF
menu=Boot normally:boot hd0b:netbsd
menu=Boot single user:boot hd0b:netbsd -s
default=1
timeout=5
EOF

# efi -c -d sd0 -p 1 -l "\\EFI\\BOOT\\BOOTX64.EFI" -L "NetBSD"
( cd $r/boot/efi && efi -q -c -l "\\EFI\\BOOT\\BOOTX64.EFI" -L "NetBSD" )


# ====== Basic configuration ================================================

# ------ Set root password --------------------------------------------------
passhash="$(chroot $r pwhash "<SET_PASSWORD_HERE>")"
sed -e "s,^root::,root:$passhash:," $r/etc/master.passwd > /tmp/master.passwd
cp /tmp/master.passwd $r/etc/master.passwd
chown 0:0 $r/etc/master.passwd
chmod 600 $r/etc/master.passwd
chroot $r pwd_mkdb -p /etc/master.passwd

# hostname & network config
cat <<EOF >> $r/etc/rc.conf
hostname="<SET_HOSTFQDN_HERE>
ifconfig_wm0=dhcp
EOF

# ssh config
cat <<EOF >> $r/etc/ssh/sshd_config
UseDNS no
NoneEnabled yes
EOF
echo sshd=YES >> $r/etc/rc.conf

# misc configuration
echo wscons=YES >> $r/etc/rc.conf
sed -e 's/^rc_configured=NO/rc_configured=YES/' $r/etc/rc.conf > /tmp/rc.conf
cp /tmp/rc.conf $r/etc/rc.conf

# kill dhcpcd and relaunch it in chroot
kill -TERM "$(cat /var/run/dhcpcd-wm0.pid)"
chroot $r dhcpcd wm0

# ------ Initialise package database ----------------------------------------
release=11.0

chroot $r pkg_add http://ftp.NetBSD.org/pub/pkgsrc/packages/NetBSD/amd64/$release/All/pkgin
sed -e 's,^[^#].*$,http://ftp.NetBSD.org/pub/pkgsrc/packages/NetBSD/$arch/'$release'/All,' $r/usr/pkg/etc/pkgin/repositories.conf > /tmp/repositories.conf
mv /tmp/repositories.conf $r/usr/pkg/etc/pkgin/repositories.conf
chroot $r pkgin -y update

# Install some basic packages:
chroot $r /usr/pkg/bin/pkgin -y install bash sudo wget virt-what


# ====== User ===============================================================
echo "<SET_PASSWORD_HERE>" | pw useradd -u 1000 -n "<SET_USERNAME_HERE>" -h 0 -s /bin/sh -G wheel -c "<SET_REALNAME_HERE>" -m

mkdir -p $r/usr/pkg/etc/sudoers.d
echo "<SET_USERNAME_HERE> ALL=(ALL) NOPASSWD: ALL" >"$r/usr/pkg/etc/sudoers.d/<SET_USERNAME_HERE>"
chmod 0440 "$r/usr/pkg/etc/sudoers.d/<SET_USERNAME_HERE>"

chsh -s /usr/pkg/bin/bash "<SET_USERNAME_HERE>"

# chroot $r useradd -s /usr/pkg/bin/bash -d /home/vagrant -m -g staff -G wheel -p "$passhash" vagrant
# mkdir -pm 700 $r/home/vagrant/.ssh
# chroot $r /usr/pkg/bin/wget --no-check-certificate 'https://raw.github.com/mitchellh/vagrant/master/keys/vagrant.pub' -O /home/vagrant/.ssh/authorized_keys
# chmod 0600 $r/home/vagrant/.ssh/authorized_keys
# chroot $r chown -R vagrant /home/vagrant/.ssh
# echo "vagrant ALL=(ALL) NOPASSWD: ALL" >> $r/usr/pkg/etc/sudoers.d/vagrant
# chmod 0400 $r/usr/pkg/etc/sudoers.d/vagrant


# ====== Reboot =============================================================

# Reboot into the freshly installed system:
# reboot
