#!/bin/sh

# Based on: https://github.com/stoned/packer-nbsd-boxes

export PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/pkg/sbin:/usr/pkg/bin

set -eux


# ====== Find disks =========================================================
# Disk names extracted dynamically from sysctl hw.disknames
VALID_DISKS=""
for d in $(sysctl -n hw.disknames); do
  case "$d" in
    dk*|cd*)
       # Skip CD drives and wedges
       ;;
    *)
       VALID_DISKS="$VALID_DISKS $d"
       ;;
  esac
done

# Map space-separated disk strings to positional parameters:
set -- $VALID_DISKS

DISK_ROOT="${1:-}"
DISK_HOME="${2:-}"
DISK_SWAP="${3:-}"
if [ "$DISK_ROOT" = "" ] ; then
   echo >&2 "ERROR: Root disk not found!"
   exit 1
fi
if [ "$DISK_HOME" = "" ] ; then
   echo >&2 "ERROR: Home disk not found!"
   exit 1
fi
if [ "$DISK_SWAP" = "" ] ; then
   echo >&2 "ERROR: Swap disk not found!"
   exit 1
fi


# ====== Partitioning =======================================================
# Documentation:
# https://wiki.netbsd.org/Installation_on_UEFI_systems/

# Root Disk:
gpt create $DISK_ROOT
gpt add -l "EFI-system" -t efi -s 64m $DISK_ROOT
gpt add -l "Root"       -t ffs $DISK_ROOT

# Find assigned wedge IDs for Root Disk:
WEDGE_EFI=$(dkctl $DISK_ROOT listwedges | grep "EFI-system" | awk -F: '{ print $1 }' | tr -d ' ')
WEDGE_ROOT=$(dkctl $DISK_ROOT listwedges | grep "Root" | awk -F: '{ print $1 }' | tr -d ' ')

newfs_msdos /dev/r$WEDGE_EFI
newfs -O 2 /dev/r$WEDGE_ROOT

# Home Disk:
gpt create $DISK_HOME
gpt add -l "Home" -t ffs $DISK_HOME

# Find assigned wedge ID for Home Disk:
WEDGE_HOME=$(dkctl $DISK_HOME listwedges | grep "Home" | awk -F: '{ print $1 }' | tr -d ' ')
newfs -O 2 /dev/r$WEDGE_HOME

# Swap Disk:
gpt create $DISK_SWAP
gpt add -l "Swap" -t swap $DISK_SWAP

# Find assigned wedge ID for Swap Disk:
WEDGE_SWAP=$(dkctl $DISK_SWAP listwedges | grep "Swap" | awk -F: '{ print $1 }' | tr -d ' ')
swapctl -a /dev/$WEDGE_SWAP


# ====== NetBSD installation ================================================

# ------ Mount filesystems --------------------------------------------------
r=/targetroot
mount /dev/$WEDGE_ROOT $r
mkdir -p $r/boot/efi
mount /dev/$WEDGE_EFI $r/boot/efi
mkdir -p $r/home
mount /dev/$WEDGE_HOME $r/home

# ------ Extract sets -------------------------------------------------------
suffix=tgz
[ -f /amd64/binary/sets/base.tar.xz ] && suffix=tar.xz

# Skipping X11: xbase xcomp xetc xfont xserver
for s in base etc comp games kern-GENERIC man misc modules tests text ; do
   ( cd $r && echo $s && tar --chroot -xpf /amd64/binary/sets/$s.$suffix )
done

# MAKEDEV
( cd $r/dev && sh ./MAKEDEV all )

# fstab
mkdir -p $r/kern
mkdir -p $r/proc
cat <<EOF >$r/etc/fstab
NAME=Root        /            ffs     rw,log        1 1
NAME=EFI-system  /boot/efi    msdos   rw            0 0
NAME=Home        /home        ffs     rw,log        1 2
NAME=Swap        none         swap    sw,dp         0 0
kernfs           /kern        kernfs  rw            0 0
procfs           /proc        procfs  rw            0 0
fdesc            /dev         fdesc   ro,-o=union   0 0
ptyfs            /dev/pts     ptyfs   rw            0 0
tmpfs            /tmp tmpfs   rw,-m1777,-sram%25
EOF


# ====== Boot loader ========================================================
mkdir -p $r/boot/efi/EFI/BOOT
cp /usr/mdec/bootx64.efi $r/boot/efi/EFI/BOOT/BOOTX64.EFI

( cd $r/boot/efi && efi -q -c -l "\\EFI\\BOOT\\BOOTX64.EFI" -L "NetBSD" )


# ====== Basic configuration ================================================

# ------ Set root password --------------------------------------------------
root_hash="$(chroot $r pwhash "<SET_PASSWORD_HERE>")"
chroot $r usermod -p "$root_hash" root

# ------ Configure console --------------------------------------------------
echo 'wscons="YES"' >>$r/etc/rc.conf
cat >>"$r/etc/profile" <<EOF
export LANG="C.UTF-8"
export LC_CTYPE="C.UTF-8"
EOF

# ------ Configure keymap ---------------------------------------------------
keymap="<SET_XKBLAYOUT_HERE>"
if grep -q "^encoding" "$r/etc/wscons.conf"; then
   sed -i "s/^encoding.*/encoding $keymap/" "$r/etc/wscons.conf"
else
   echo "encoding $keymap" >>"$r/etc/wscons.conf"
fi
chroot $r wsconsctl -w encoding=$keymap

# ------ Configure network --------------------------------------------------
interface="$(ifconfig -l | cut -d' ' -f1)"

# shellcheck disable=SC2129
cat >>$r/etc/rc.conf <<EOF
hostname="<SET_HOSTFQDN_HERE>"
ifconfig_$interface="dhcp"
EOF

# ------ Configure time zone ------------------------------------------------
chroot $r ln -sf /usr/share/zoneinfo/UTC /etc/localtime

# ------ Enable basic daemons -----------------------------------------------
echo 'sshd="YES"' >>$r/etc/rc.conf

# Update rc_configured:
sed -e 's/^rc_configured=NO/rc_configured="YES"/' \
   $r/etc/rc.conf >/tmp/rc.conf.updated
mv /tmp/rc.conf.updated $r/etc/rc.conf

# ------ Initialise package database ----------------------------------------

# kill dhcpcd and relaunch it in chroot
kill -TERM "$(cat /var/run/dhcpcd/$interface.pid)" || true
chroot $r dhcpcd $interface

release="$(uname -r | sed -e 's/_.*//')"

chroot $r pkg_add http://ftp.NetBSD.org/pub/pkgsrc/packages/NetBSD/amd64/$release/All/pkgin
# shellcheck disable=SC2016
sed -e 's,^[^#].*$,http://ftp.NetBSD.org/pub/pkgsrc/packages/NetBSD/$arch/'$release'/All,' \
   $r/usr/pkg/etc/pkgin/repositories.conf >/tmp/repositories.conf
mv /tmp/repositories.conf $r/usr/pkg/etc/pkgin/repositories.conf
chroot $r pkgin -y update

# ------ Install required packages ------------------------------------------
chroot $r /usr/pkg/bin/pkgin -y install bash sudo virt-what


# ====== QEMU Guest Agent ===================================================
# QEMU installs already need qemu-guest-agent before first boot:
if [ "$(chroot $r /usr/pkg/sbin/virt-what)" = "kvm" ] ; then
   chroot $r pkgin -y install qemu-guest-agent
   cp $r/usr/pkg/share/examples/rc.d/qemu-guest-agent $r/etc/rc.d/
   echo 'qemu_guest_agent="YES"' >>$r/etc/rc.conf
fi


# ====== User ===============================================================
user_hash="$(chroot $r pwhash "<SET_PASSWORD_HERE>")"

# Create the user natively within the chroot system
chroot $r useradd -u 1000 -m -G wheel -s /usr/pkg/bin/bash -p "$user_hash" -c "<SET_REALNAME_HERE>" "<SET_USERNAME_HERE>"

mkdir -p $r/usr/pkg/etc/sudoers.d
echo "<SET_USERNAME_HERE> ALL=(ALL) NOPASSWD: ALL" >"$r/usr/pkg/etc/sudoers.d/<SET_USERNAME_HERE>"
chmod 0440 "$r/usr/pkg/etc/sudoers.d/<SET_USERNAME_HERE>"


# ====== Reboot =============================================================

# Reboot into the freshly installed system:
reboot
