#!/bin/bash

set -ex


if [ $# -lt 1 ] ; then
   echo >&2 "Usage: $0 vm_address"
   exit 1
fi
address="$1"

ssh-copy-id nornetpp@${address}
ssh -t -oStrictHostKeyChecking=no nornetpp@${address} '
echo "nornetpp ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/99-nornetpp
if ! which git ; then
   if [ -x /usr/bin/apt ] ; then
      sudo /usr/bin/apt install -y git joe
   elif [ -x /usr/bin/dnf ] ; then
      sudo /usr/bin/dnf install -y git joe
   elif [ -x /usr/bin/pkg ] ; then
      sudo /usr/bin/pkg install -y git joe
   fi
fi
if [ ! -d ~/src/vmimage-builder-scripts ] ; then
   git clone https://dreibh@github.com/simula/nornet-vmimage-builder-scripts ~/src/vmimage-builder-scripts
   cd ~/src/vmimage-builder-scripts
   git config pull.rebase true
   git checkout dreibh/freebsd
fi
if [ ! -e ~/.gitconfig ] ; then
   cat >~/.gitconfig <<EOF
[user]
        name = Thomas Dreibholz
        email = dreibh@simula.no
[push]
        default = simple
[color]
        ui = auto
EOF
fi
'

ssh nornetpp@${address}
