#!/bin/bash

packages="
      boost-all
mysql-connector-c++
postgresql-libpqxx
mongo-c-driver
"

sorted="$(echo "${packages}" | xargs -n1 | sort -u)"
echo '   packages="'
for package in ${sorted} ; do
   echo "      ${package}"
done
echo '   "'

echo ""
echo \"${sorted}\" | xargs
