#!/usr/bin/env bash

set -euxo pipefail

if prtdiag | grep -q "QEMU" ; then

  pkg install qemu || [ $? -eq 4 ]

  mkdir -p /etc/qemu
  cat >/etc/qemu/qemu-ga.conf <<EOF
[general]
method = isa-serial
path=/dev/ttya
daemon = false
pidfile = /var/run/qemu-ga.pid
logfile = /var/log/qemu-ga.log
statedir = /var/run
EOF

  cat >/lib/svc/manifest/system/qemu-ga.xml <<EOF
<?xml version='1.0'?>
<!DOCTYPE service_bundle SYSTEM '/usr/share/lib/xml/dtd/service_bundle.dtd.1'>
<service_bundle type='manifest' name='qemu-ga'>
  <service name='system/qemu-ga' type='service' version='1'>
    <dependency name='fs-local' grouping='require_all' restart_on='none' type='service'>
      <service_fmri value='svc:/system/filesystem/local'/>
    </dependency>
    <exec_method type='method' name='start' exec='/usr/bin/qemu-ga -c /etc/qemu/qemu-ga.conf' timeout_seconds='60'>
      <method_context>
        <method_credential user='root' group='root' />
      </method_context>
    </exec_method>
    <exec_method type='method' name='stop' exec=':kill' timeout_seconds='60'/>
    <property_group name='startd' type='framework'>
      <propval name='ignore_error' type='astring' value='core,signal' />
      <propval name='duration' type='astring' value='child' />
    </property_group>
    <instance name='default' enabled='true'/>
    <template>
      <common_name>
        <loctext xml:lang='C'>QEMU Guest Agent</loctext>
      </common_name>
    </template>
  </service>
</service_bundle>
EOF

   svccfg import /lib/svc/manifest/system/qemu-ga.xml
   svcadm enable qemu-ga
   svcadm clear qemu-ga
fi
