#!/usr/bin/env bash
# ==========================================================================
#  ___         _        _ _      _   _            ___         _      _
# |_ _|_ _  __| |_ __ _| | |__ _| |_(_)___ _ _   / __| __ _ _(_)_ __| |_ ___
#  | || ' \(_-<  _/ _` | | / _` |  _| / _ \ ' \  \__ \/ _| '_| | '_ \  _(_-<
# |___|_||_/__/\__\__,_|_|_\__,_|\__|_\___/_||_| |___/\__|_| |_| .__/\__/__/
#                                                              |_|
#
#   --- Virtual Machine Image Builder and System Installation Scripts ---
#            https://www.nntb.no/~dreibh/vmimage-builder-scripts/
# ==========================================================================
#
# System Installation Scripts
# Copyright (C) 2017-2026 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

set -euxo pipefail


# ====== Find disks =========================================================
# Identify the active root disk from rpool:
ROOT_DEV=$(zpool status rpool | awk '/c[0-9]+/ {print $1}' | head -n1)
DISK_ROOT=$(echo "$ROOT_DEV" | sed -E 's/[sp][0-9]+$//')
if [ -z "$DISK_ROOT" ]; then
   echo >&2 "ERROR: Root disk not found!"
   exit 1
fi

# Identify all connected disks:
ALL_DISKS="$(diskinfo -H 2>/dev/null | awk '{print $2}' || ls /dev/dsk/c* 2>/dev/null | sed -E 's|/dev/dsk/||; s/[sp][0-9]+$//' | sort -u)"
DISK_HOME=""
DISK_SWAP=""

# Assign non-root disks to home and swap:
for d in $ALL_DISKS; do
   if [ "$d" != "$DISK_ROOT" ]; then
      if [ -z "$DISK_HOME" ]; then
         DISK_HOME="$d"
      elif [ -z "$DISK_SWAP" ]; then
         DISK_SWAP="$d"
         break
      fi
   fi
done
if [ -z "$DISK_HOME" ]; then
   echo >&2 "ERROR: Home disk not found!"
   exit 1
fi
if [ -z "$DISK_SWAP" ]; then
   echo >&2 "ERROR: Swap disk not found!"
   exit 1
fi

echo "root=$DISK_ROOT home=$DISK_HOME swap=$DISK_SWAP"


# ====== Provision storage ==================================================

# Ensure execution context is outside /home to prevent directory locks
cd /tmp

# Remove swap on rpool (frees space to / automatically):
swap -d /dev/zvol/dsk/rpool/swap || true
zfs destroy -f rpool/swap || true
grep -v '/dev/zvol/dsk/rpool/swap' /etc/vfstab >/tmp/vfstab.tmp && cp /tmp/vfstab.tmp /etc/vfstab && rm /tmp/vfstab.tmp

# Create swap on $DISK_SWAP:
zpool create -f swappool "/dev/dsk/${DISK_SWAP}s0" || zpool create -f swappool "/dev/dsk/${DISK_SWAP}"

# Subtract a 16MB buffer for ZFS pool metadata:
AVAILABLE_BYTES=$(zfs get -Hp -o value avail swappool)
SWAP_SIZE_BYTES=$(( AVAILABLE_BYTES - 16777216 ))

# -o refreserv=none disables strict ZFS volume space reservation:
zfs create -V "${SWAP_SIZE_BYTES}" -o refreserv=none swappool/swap

swap -a /dev/zvol/dsk/swappool/swap
if ! grep -q "swappool/swap" /etc/vfstab; then
   echo "/dev/zvol/dsk/swappool/swap - - swap - no -" >> /etc/vfstab
fi

# Migrate /home to $DISK_HOME:
zpool create -f homepool "/dev/dsk/${DISK_HOME}s0" || zpool create -f homepool "/dev/dsk/${DISK_HOME}"

mkdir -p /mnt/newhome
zfs set mountpoint=/mnt/newhome homepool
if [ -d /export/home ]; then
  cp -a /export/home/. /mnt/newhome/ 2>/dev/null || true
fi

zfs set mountpoint=none homepool
rmdir /mnt/newhome
zfs destroy -r -f rpool/export/home || true
zfs set mountpoint=/export/home homepool


# ====== Install QEMU Guest Agent =========================================
if prtdiag | grep -q "QEMU" ; then

   # ====== Install QEMU Guest Agent =========================================
   # FIXME! The QEMU package is buggy: https://www.illumos.org/issues/18320
   # pkg install qemu || [ $? -eq 4 ]

   # Work-around: install from sources!
   pkg install \
   developer/gcc-14 \
   developer/build/gnu-make \
   developer/build/ninja \
   developer/versioning/git \
   library/glib2 \
   runtime/python-314 \
   developer/build/pkg-config || [ $? -eq 4 ]

   mkdir -p /root/src
   cd /root/src
   if [ ! -d qemu ] ; then
      git clone https://gitlab.com/qemu-project/qemu.git
      cd qemu
   else
      cd qemu
      git pull
   fi

   export CC=gcc
   export CXX=g++
   export MAKE=gmake
   export MAKEFLAGS="-j $(psrinfo -t)"

   mkdir build && cd build
   ../configure \
      --python=/usr/bin/python3.14 \
      --extra-ldflags="-lsocket -lnsl" \
      --disable-system \
      --disable-user \
      --disable-tools \
      --enable-guest-agent

   gmake qemu-ga
   cp qga/qemu-ga /usr/bin/qemu-ga

   # FIXME: qemu-ga contains hard-coded shutdown command paths:
   # * https://gitlab.com/qemu-project/qemu/-/work_items/4141)
   # * https://www.illumos.org/issues/18331
   # Temporary work-around:
   ln -s /usr/sbin/poweroff /sbin/poweroff
   ln -s /usr/sbin/shutdown /sbin/shutdown
   ln -s /usr/sbin/halt     /sbin/halt
   ln -s /usr/sbin/reboot   /sbin/reboot

   # ====== QEMU Guest Agent Service Setup ===================================
   mkdir -p /etc/qemu
   cat >/etc/qemu/qemu-ga.conf <<EOF
[general]
method   = isa-serial
path     = /dev/ttya
daemon   = false
pidfile  = /var/run/qemu-ga.pid
logfile  = /var/log/qemu-ga.log
statedir = /var/run
EOF

  cat >/lib/svc/manifest/system/qemu-ga.xml <<EOF
<?xml version='1.0'?>
<!DOCTYPE service_bundle SYSTEM '/usr/share/lib/xml/dtd/service_bundle.dtd.1'>
<service_bundle type='manifest' name='qemu-ga'>
  <service name='system/qemu-ga' type='service' version='1'>
    <dependency name='fs-local' grouping='require_all' restart_on='none' type='service'>
      <service_fmri value='svc:/system/filesystem/local'/>
    </dependency>
    <exec_method type='method' name='start' exec='/usr/bin/qemu-ga -c /etc/qemu/qemu-ga.conf' timeout_seconds='60'>
      <method_context>
        <method_credential user='root' group='root' />
      </method_context>
    </exec_method>
    <exec_method type='method' name='stop' exec=':kill' timeout_seconds='60'/>
    <property_group name='startd' type='framework'>
      <propval name='ignore_error' type='astring' value='core,signal' />
      <propval name='duration' type='astring' value='child' />
    </property_group>
    <instance name='default' enabled='true'/>
    <template>
      <common_name>
        <loctext xml:lang='C'>QEMU Guest Agent</loctext>
      </common_name>
    </template>
  </service>
</service_bundle>
EOF

   svccfg import /lib/svc/manifest/system/qemu-ga.xml
   svcadm enable qemu-ga
   svcadm clear qemu-ga || true
fi
