#!/usr/bin/env bash
#
# MAAS Image Builder Script
# Copyright (C) 2017-2021 by Thomas Dreibholz <dreibh@simula.no>
# Copyright (C) 2020 by Lee Trager <lee.trager@canonical.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

set -e


# ====== Output name ========================================================
BUILD_NAME=`realpath . --relative-base=.. | sed -e "s/^QEMU-//g"`
DISK_IMAGE="`realpath ${BUILD_NAME}/${BUILD_NAME}`"
if [ ! -f "${DISK_IMAGE}" ] ; then
   echo "ERROR: \$DISK_IMAGE has to be set to the output image name!"
   exit 1
fi
PARTITION_ROOT="p2"   # Root partition is the second partition on the disk!
MAAS_IMAGE="${DISK_IMAGE}.tar.gz"


# ====== Set up NBD =========================================================
# Based on setup-nbd from  https://github.com/canonical/packer-maas

if [ ${UID} -ne 0 ]; then
    echo "ERROR: Must be run as root!" >&2
    exit 1
fi

echo "Loading nbd ..."
shopt -s extglob
modprobe nbd
for nbd in /sys/class/block/nbd+([0-9]); do
   if [ "$(cat ${nbd}/size)" -eq 0 ]; then
      nbd="/dev/$(basename ${nbd})"
      echo "Using ${nbd}"
      break
   fi
done

if [ -z "${nbd}" ] || ! echo ${nbd} | grep -q "/dev"; then
   echo "ERROR: Unable to find nbd device to mount image!" >&2
   exit 1
fi

echo "Binding image to ${nbd} ..."
qemu-nbd -d ${nbd}
if [ -n "$IMG_FMT" ]; then
   qemu-nbd -c ${nbd} -f "$IMG_FMT" -n ${DISK_IMAGE}
else
   qemu-nbd -c ${nbd} -n ${DISK_IMAGE}
fi
echo "Waiting for partitions to be created ..."
tries=0
while [ ! -e "${nbd}${PARTITION_ROOT}" -a $tries -lt 60 ]; do
    sleep 1
    tries=$((tries+1))
done


# ====== Create tarball =====================================================
# Based on tar-root from  https://github.com/canonical/packer-maas

DISK_MOUNTPOINT=$(mktemp -d /tmp/maas-XXXXXXXXXX)

echo "Mounting root partition ..."
mount "${nbd}${PARTITION_ROOT}" ${DISK_MOUNTPOINT}
if [ -e "${DISK_MOUNTPOINT}/@" -o -e "${DISK_MOUNTPOINT}/@home" ] ; then
   # BTRFS: mount sub-volumes instead!
   umount ${DISK_MOUNTPOINT}
   mount -o subvol=@     "${nbd}${PARTITION_ROOT}" ${DISK_MOUNTPOINT}
   mount -o subvol=@home "${nbd}${PARTITION_ROOT}" ${DISK_MOUNTPOINT}/home
fi

if [ -d curtin ] || [ -d "${CURTIN_HOOKS}" ]; then
    echo "Adding Curtin hooks ..."
    cp -r ${CURTIN_HOOKS:-curtin} ${DISK_MOUNTPOINT}
fi

echo "Creating MAAS image ${MAAS_IMAGE} ..."
tar -Sczpf ${MAAS_IMAGE} --acls --selinux --xattrs -C ${DISK_MOUNTPOINT} .

if [ -n "${MANIFEST}" ]; then
    echo "Creating manifest ..."
    # RPM on CentOS/RHEL 7 needs /dev mounted so it can use /dev/urandom
    mount -o bind /dev ${DISK_MOUNTPOINT}/dev
    chroot ${DISK_MOUNTPOINT} rpm -qa | sort -u -o ${MANIFEST}
    umount ${DISK_MOUNTPOINT}/dev
fi

echo "Unmounting image ..."
umount ${DISK_MOUNTPOINT}/home 2>/dev/null || true
umount ${DISK_MOUNTPOINT}
qemu-nbd -d $nbd
rmdir ${DISK_MOUNTPOINT}

echo "Done!"
