#!/usr/bin/env bash
# ==========================================================================
#         ____            _                     _____           _
#        / ___| _   _ ___| |_ ___ _ __ ___     |_   _|__   ___ | |___
#        \___ \| | | / __| __/ _ \ '_ ` _ \ _____| |/ _ \ / _ \| / __|
#         ___) | |_| \__ \ ||  __/ | | | | |_____| | (_) | (_) | \__ \
#        |____/ \__, |___/\__\___|_| |_| |_|     |_|\___/ \___/|_|___/
#               |___/
#                             --- System-Tools ---
#                  https://www.nntb.no/~dreibh/system-tools/
# ==========================================================================
#
# GIMP Scripts
# Copyright (C) 2013-2026 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

# Bash options:
set -euo pipefail


# ###### Usage ##############################################################
usage () {
   local exitCode="$1"
   echo >&2 "Usage: $0 output_filename caption_width caption_height caption_text [-F|--font-name font] [-S|--font-size percentage] [-f|--foreground color] [-b|--background color] [|-t|--transparency percentage] [-w|--verbose] [-q|--quiet] [-h|--help] [-v|--version]"
   exit "${exitCode}"
}


# ###### Version ############################################################
version () {
   echo "gs-caption @BUILD_MAJOR@.@BUILD_MINOR@.@BUILD_PATCH@"
   exit 0
}



# ###### Main program #######################################################

# ====== Handle arguments ===================================================
GETOPT="$(PATH=/usr/local/bin:$PATH which getopt)"
# shellcheck disable=SC2068
options="$(${GETOPT} -o F:S:f:b:t:wqhv --long font-name:,font-size:,foreground:,background:,transparency:,verbose,quiet,help,version -a -- "$@")"
eval set -- "${options}"

COLOR_FOREGROUND="#02266b"   # Dark Blue
COLOR_BACKGROUND="#ffd700"   # Gold
FONT_NAME="Noto Sans Bold"
FONT_SIZE="50"
TRANSPARENCY=25              # in %
VERBOSE=0
while [ $# -gt 0 ] ; do
   case "$1" in
      -F | --font-name)
         FONT_NAME="$2"
         shift 2
         ;;
      -S | --font-size)
         FONT_SIZE="$2"
         if [[ ! "${FONT_SIZE}" =~ ^[0-9]+$ ]] || [ "${FONT_SIZE}" -lt 1 ] || [ "${FONT_SIZE}" -gt 100 ] ; then
            echo >&2 "ERROR: Invalid value ${FONT_SIZE} for -s|--font-size!"
            exit 1
         fi
         shift 2
         ;;
      -f | --foreground)
         COLOR_FOREGROUND="$2"
         if [[ ! "${COLOR_FOREGROUND}" =~ ^#[0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]$ ]] ; then
            echo >&2 "ERROR: Invalid value ${COLOR_FOREGROUND} for -f|--foreground!"
            exit 1
         fi
         shift 2
         ;;
      -b | --background)
         COLOR_BACKGROUND="$2"
         if [[ ! "${COLOR_BACKGROUND}" =~ ^#[0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]$ ]] ; then
            echo >&2 "ERROR: Invalid value ${COLOR_BACKGROUND} for -b|--background!"
            exit 1
         fi
         shift 2
         ;;
      -t | --transparency)
         TRANSPARENCY="$2"
         if [[ ! "${TRANSPARENCY}" =~ ^[0-9]+$ ]] || [ "${TRANSPARENCY}" -lt 0 ] || [ "${TRANSPARENCY}" -gt 100 ]; then
            echo >&2 "ERROR: Invalid value ${TRANSPARENCY} for -t|--transparency!"
            exit 1
         fi
         TRANSPARENCY="$2"
         shift 2
         ;;
      -w | --verbose)
         VERBOSE=1
         shift
         ;;
      -q | --quiet)
         VERBOSE=0
         shift
         ;;
      -h | --help)
         usage 0
         ;;
      -v | --version)
         version
         # shift
         ;;
      --)
         shift
         break
         ;;
      *)
         usage 1
         ;;
  esac
done

if [ $# -ne 4 ] ; then
   usage 1
fi
OUTPUT_FILENAME="$1"
CAPTION_WIDTH="$2"
CAPTION_HEIGHT="$3"
CAPTION_TEXT="$4"

if [[ ! "${CAPTION_WIDTH}" =~ ^([0-9]+)$ ]] || [ "${CAPTION_WIDTH}" -lt 1 ]; then
   echo >&2 "ERROR: Invalid caption width!"
   exit 1
fi
if [[ ! "${CAPTION_HEIGHT}" =~ ^([0-9]+)$ ]] || [ "${CAPTION_HEIGHT}" -lt 1 ]; then
   echo >&2 "ERROR: Invalid caption height!"
   exit 1
fi


# ====== Detect GIMP, and determine version-specific call options ===========
GIMP_CONSOLE="$(which gimp-console 2>/dev/null || true)"
if [ "${GIMP_CONSOLE}" == "" ] ; then
   echo >&2 "ERROR: GIMP is not installed!"
   echo >&2 "* Ubuntu:  sudo apt install -y gimp"
   echo >&2 "* Fedora:  sudo dnf install -y gimp"
   echo >&2 "* SuSE     sudo zypper install -y gimp"
   echo >&2 "* Alpine:  sudo apk add gimp"
   echo >&2 "* FreeBSD: sudo pkg install -y gimp3-app"
   exit 1
fi
GIMP_VERSION="$(LC_ALL=C.UTF-8 "${GIMP_CONSOLE}" --version | sed -e 's/GNU Image Manipulation Program version //')"
if [[ "${GIMP_VERSION}" =~ ^[012] ]] ; then
   # GIMP 2.x:
   GIMP_OPTIONS="--new-instance --no-interface --no-splash --batch-interpreter plug-in-script-fu-eval --batch -"
else
   # GIMP 3.x:
   GIMP_OPTIONS="--quit --new-instance --no-interface --no-splash --batch-interpreter plug-in-script-fu-eval --batch -"
fi

# This script does not use gradients/palettes/brushes:
GIMP_OPTIONS="${GIMP_OPTIONS} --no-data"


# ====== Call GIMP ==========================================================
rm -f "${OUTPUT_FILENAME}"
# shellcheck disable=SC2086
( cat <<EOF

; GIMP 2.8 compatibility:
(cond ((not (defined? 'LAYER-MODE-NORMAL-LEGACY)) (define LAYER-MODE-NORMAL-LEGACY NORMAL-MODE)))
(cond ((not (defined? 'FILL-BACKGROUND)) (define FILL-BACKGROUND BACKGROUND-FILL)))

(let*
   ; ------ Initialise ------------------------------------------------------
   ((outputFileName   "${OUTPUT_FILENAME}")
    (captionText      "${CAPTION_TEXT}")
    (captionWidth     ${CAPTION_WIDTH})
    (captionHeight    ${CAPTION_HEIGHT})
    (captionFont)
    (captionFontSize  (/ (* ${FONT_SIZE} captionHeight) 100))
    (captionOpacity   (- 100 ${TRANSPARENCY}))
    (captionFGColor   "${COLOR_FOREGROUND}")
    (captionBGColor   "${COLOR_BACKGROUND}")
    (theText)
    (image (car (gimp-image-new captionWidth captionHeight RGB)))
    ; (layer1 (car (gimp-layer-new image captionWidth captionHeight RGBA-IMAGE "Layer 1" captionOpacity LAYER-MODE-NORMAL-LEGACY)))
    (layer1           (if (not (defined? 'gimp-image-get-active-layer))
                         ; New GIMP 3.0 API:
                         (car (gimp-layer-new image "Layer 1" captionWidth captionHeight RGBA-IMAGE captionOpacity LAYER-MODE-NORMAL-LEGACY))
                         ; Old GIMP 2.x API:
                         (car (gimp-layer-new image captionWidth captionHeight RGBA-IMAGE "Layer 1" captionOpacity LAYER-MODE-NORMAL-LEGACY))
                      ))
    ; (layer2 (car (gimp-layer-new image captionWidth captionHeight RGBA-IMAGE "Layer 2" 100 LAYER-MODE-NORMAL-LEGACY)))
    (layer2           (if (not (defined? 'gimp-image-get-active-layer))
                         ; New GIMP 3.0 API:
                         (car (gimp-layer-new image "Layer 2" captionWidth captionHeight RGBA-IMAGE 100 LAYER-MODE-NORMAL-LEGACY))
                         ; Old GIMP 2.x API:
                         (car (gimp-layer-new image captionWidth captionHeight RGBA-IMAGE "Layer 2" 100 LAYER-MODE-NORMAL-LEGACY))
                      ))
   )

   (if (not (defined? 'gimp-image-get-active-layer))
      (set! captionFont (car (gimp-font-get-by-name "${FONT_NAME}")))
      (set! captionFont "${FONT_NAME}"))
   ; (newline) (display "captionFont=") (display captionFont) (newline)
   (if (and (not (defined? 'gimp-image-get-active-layer)) (= captionFont -1)) (
      (gimp-message "ERROR: Font \"${FONT_NAME}\" is not available! Check installed fonts with fc-list!")
      (quit FALSE)
   ))

   ; ------ Generate caption ------------------------------------------------
   (gimp-image-insert-layer image layer1 -1 0)
   (gimp-image-insert-layer image layer2 -1 0)
   (gimp-context-set-background captionBGColor)
   (gimp-context-set-foreground captionFGColor)
   (gimp-drawable-fill layer1 FILL-BACKGROUND)

   (if (defined? 'gimp-drawable-merge-new-filter)
      (begin  ; New GIMP >= 3.0 API:
         (set! theText (car (gimp-text-font image layer2 0 0 captionText 0 TRUE captionFontSize captionFont) ))
         (gimp-layer-set-offsets
            theText
            (/ (- captionWidth  (car (gimp-drawable-get-width  theText))) 2)
            (/ (- captionHeight (car (gimp-drawable-get-height theText))) 2))
      )
      (begin  ; Old GIMP < 3.0 API:
         (set! theText (car (gimp-text-fontname image layer2 0 0 captionText 0 TRUE captionFontSize PIXELS captionFont) ) )
         (gimp-layer-set-offsets
           theText
           (/ (- captionWidth  (car (gimp-drawable-width  theText))) 2)
           (/ (- captionHeight (car (gimp-drawable-height theText))) 2))
      )
   )

   (gimp-image-merge-visible-layers image CLIP-TO-IMAGE)
   ; (gimp-display-new image)

   ; ------ Save result -----------------------------------------------------
   (if (defined? 'gimp-drawable-merge-new-filter)
      (begin  ; New GIMP >= 3.0 API:
         ; FIXME: This does not work when running in GIMP 2.x!
         ; (file-png-export
         ;    #:run-mode         RUN-NONINTERACTIVE
         ;    #:image            image
         ;    #:file             outputFileName
         ;    #:options          -1
         ;    #:interlaced       TRUE
         ;    #:compression      6
         ;    #:bkgd             TRUE
         ;    #:offs             FALSE
         ;    #:phys             TRUE
         ;    #:time             TRUE
         ;    #:save-transparent FALSE
         ;    #:optimize-palette TRUE
         ; )
         (file-png-export RUN-NONINTERACTIVE image
            outputFileName -1
            TRUE 6 TRUE FALSE TRUE TRUE FALSE TRUE)
      )
      (begin  ; Old GIMP < 3.0 API:
         (file-png-save2 RUN-NONINTERACTIVE image
            (car (gimp-image-get-active-layer image))
            outputFileName outputFileName
            TRUE 6 TRUE TRUE FALSE TRUE TRUE FALSE TRUE)
      )
   )

   ; ------ Clean up --------------------------------------------------------
   (gimp-image-delete image)
)
(gimp-quit TRUE)
EOF
) | env LC_ALL=C.UTF-8 HOME=/tmp "${GIMP_CONSOLE}" ${GIMP_OPTIONS} 2>&1 | \
(
   if [ ${VERBOSE} -ne 0 ] ; then
      cat
   else
      grep -vE "^ts>|(#t)|^Copyright|Welcome to (GIMP|TinyScheme)|^using gegl copy|^gimp_color_transform_new: using babl|scriptfu-WARNING|-WARNING|^Please use named arguments:|^script quit with code:|^$" || true
   fi
)


# ====== Check result =======================================================
if [ ! -e "${OUTPUT_FILENAME}" ] ; then
   echo >&2 "ERROR: ${OUTPUT_FILENAME} has not been produced. Something went wrong!"
   exit 1
fi
