#!/usr/bin/env bash
# ==========================================================================
#         ____            _                     _____           _
#        / ___| _   _ ___| |_ ___ _ __ ___     |_   _|__   ___ | |___
#        \___ \| | | / __| __/ _ \ '_ ` _ \ _____| |/ _ \ / _ \| / __|
#         ___) | |_| \__ \ ||  __/ | | | | |_____| | (_) | (_) | \__ \
#        |____/ \__, |___/\__\___|_| |_| |_|     |_|\___/ \___/|_|___/
#               |___/
#                             --- System-Tools ---
#                  https://www.nntb.no/~dreibh/system-tools/
# ==========================================================================
#
# GIMP Scripts
# Copyright (C) 2013-2026 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

# Bash options:
set -euo pipefail


# ###### Usage ##############################################################
usage () {
   local exitCode="$1"
   echo >&2 "Usage: $0 [-w|--verbose] [-q|--quiet] [-h|--help] [-v|--version]"
   exit "${exitCode}"
}


# ###### Version ############################################################
version () {
   echo "gs-test-gimp 2.7.10"
   exit 0
}



# ###### Main program #######################################################

# ====== Handle arguments ===================================================
if (( BASH_VERSINFO[0] < 4 )) || (( (BASH_VERSINFO[0] == 4) && (BASH_VERSINFO[1] < 2) )) ; then
   echo "ERROR: Bash 4.2 or higher is required, but Bash ${BASH_VERSINFO[0]}.${BASH_VERSINFO[1]} is installed!"
   exit 1
fi
UNAME="$(uname)"
case "${UNAME}" in
   FreeBSD)
      GETOPT="$(PATH="/usr/local/bin:${PATH}" command -v getopt || true)"
      ;;
   NetBSD)
      GETOPT="$(PATH="/usr/pkg/bin:${PATH}" command -v getopt || true)"
      ;;
   OpenBSD)
      GETOPT="$(command -v gnugetopt || true)"
      ;;
   SunOS)
      GETOPT="$(PATH="/usr/gnu/bin:${PATH}" command -v getopt || true)"
      ;;
   Darwin)
      GETOPT="$(env PATH="/opt/homebrew/opt/gnu-getopt/bin:${PATH}" command -v getopt || true)"
      ;;
   *)
      GETOPT="$(command -v getopt || true)"
      ;;
esac
if "${GETOPT}" -T >/dev/null 2>&1 || [[ $? -ne 4 ]]; then
   echo >&2 "ERROR: Enhanced/GNU getopt is required!"
   exit 1
fi
options="$(${GETOPT} -o wqhv --long verbose,quiet,help,version -a -- "$@")"
# shellcheck disable=SC2181
if [[ $? -ne 0 ]]; then
   usage 1
fi

eval set -- "${options}"

VERBOSE=0
while [ $# -gt 0 ] ; do
   case "$1" in
      -w | --verbose)
         VERBOSE=1
         ;;
      -q | --quiet)
         VERBOSE=0
         ;;
      -h | --help)
         usage 0
         ;;
      -v | --version)
         version
         ;;
      --)
         shift
         break
         ;;
      *)
         # This should not happen: wrong getopt parameters, or missing case?
         echo >&2 "INTERNAL ERROR: Unhandled option $1!"
         exit 1
         ;;
  esac
  shift
done

if [ $# -ne 0 ] ; then
   usage 1
fi

if [ ! -v GIMP3_DIRECTORY ] ; then
   echo >&2 "ERROR: Environment variable GIMP3_DIRECTORY is not defined!"
   exit 1
fi


# ====== Make sure that GIMP directory exists ===============================
if [ "${GIMP3_DIRECTORY}" != "" ] ; then
   echo "Creating GIMP directory ${GIMP3_DIRECTORY} ..."
   for subdir in brushes dynamics patterns gradients palettes ; do
      mkdir -p "${GIMP3_DIRECTORY}/${subdir}"
   done

   # ====== Create gimprc ===================================================
   (
      # FIXME!
      # GIMP 3.0 fix: GIMP wastes a lot of CPU, for whatever reason. Just
      # using 1 core seems to provide the best performance:
      echo "(num-processors 1)"

      # Darwin fix: add global fonts directory to gimprc
      if [ "${UNAME}" == "Darwin" ] ; then
         echo "(font-path \"\${gimp_dir}/fonts:\${gimp_data_dir}/fonts:/Users/runner/Library/Fonts\")"
      fi
   ) >"${GIMP3_DIRECTORY}/gimprc"
fi


# ====== Detect GIMP, and determine version-specific call options ===========
GIMP_CONSOLE="$(command -v gimp-console || command -v /Applications/GIMP.app/Contents/MacOS/gimp-console-3 || true)"
if [ "${GIMP_CONSOLE}" == "" ] ; then
   echo >&2 "ERROR: GIMP is not installed! Try:"
   echo >&2 " * Ubuntu/Debian: sudo apt install -y gimp"
   echo >&2 " * Fedora:        sudo dnf install -y gimp"
   echo >&2 " * SuSE           sudo zypper install -y gimp"
   echo >&2 " * Alpine:        sudo apk add gimp"
   echo >&2 " * FreeBSD:       sudo pkg install -y gimp3-app"
   echo >&2 " * NetBSD:        sudo pkgin -y install gimp"
   echo >&2 " * OpenBSD:       sudo pkg_add gimp"
   echo >&2 " * Apple:         brew install gimp"
   exit 1
fi
GIMP_VERSION="$(LC_ALL=C.UTF-8 "${GIMP_CONSOLE}" --version | sed -e 's/GNU Image Manipulation Program version //')"
if [[ "${GIMP_VERSION}" =~ ^[012] ]] ; then
   # GIMP 2.x:
   GIMP_OPTIONS="--new-instance --no-interface --no-splash --batch-interpreter plug-in-script-fu-eval --batch -"
else
   # GIMP 3.x:
   GIMP_OPTIONS="--quit --new-instance --no-interface --no-splash --batch-interpreter plug-in-script-fu-eval --batch -"
fi


# ====== Try to start GIMP ==================================================
# shellcheck disable=SC2086
( cat <<EOF
(gimp-quit TRUE)
EOF
) | env LC_ALL=C.UTF-8 HOME=/tmp "${GIMP_CONSOLE}" ${GIMP_OPTIONS} 2>&1 | \
(
   if [ ${VERBOSE} -ne 0 ] ; then
      cat
   else
      grep -vE "^ts>|(#t)|^Copyright|Welcome to (GIMP|TinyScheme)|^using gegl copy|^gimp_color_transform_new: using babl|scriptfu-WARNING|-WARNING|^Warning: Unknown input_id|^Failed to parse tag cache|^Please use named arguments:|^script quit with code:|^GIMP is started|^$" || true
   fi
)
