#!/usr/bin/env bash
#
# Test GIMP
# Copyright (C) 2018-2024 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY# without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

# Bash options:
set -e


# ====== Make sure that GIMP directory exists ===============================
if [ "${GIMP2_DIRECTORY}" != "" ] ; then
   echo "Creating GIMP directory ${GIMP2_DIRECTORY}"
   for subdir in brushes dynamics patterns gradients palettes ; do
      mkdir -p "${GIMP2_DIRECTORY}/${subdir}"
   done
fi


# ====== Try to start GIMP ==================================================
( cat <<EOF
(gimp-quit TRUE)
EOF
) | env LANG=C HOME=/tmp gimp --new-instance --no-interface --no-splash --batch - 2>&1 | \
       ( grep -vE "^ts>|(#t)|^Copyright|^Welcome|GLib-GObject-WARNING|GEGL-gegl-operation.c-WARNING|GEGL-CRITICAL|missing babl fast path|Missing fast-path babl|accelerates GEGL|first occurance of formats|programmatically by bab|GeglBuffers leaked|Failed to parse tag cache|^$" || true )
