#!/usr/bin/env bash
#
# Print system information
# Copyright (C) 2013-2024 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

set -eu

# Helper function library -> just return when it is not available.
# Exit code 0 will let System-Info continue with the next script!
# shellcheck disable=SC1091
. "$(dirname "$0")/banner-helper" || exit 0


# ====== Print banner =======================================================

# Using 24-bit color codes. This may not work with all terminals!
reset="\x1b[0m"
color1="\x1b[34m"
color2="\x1b[31m"

# ------ Print top separator ------------------------------------------------
echo -en "${color1}"
separator " *💻" "=" "💻*"
echo ""
center "${color1}-- ${color2}$(gettext "Welcome on the System") ${color1}--"

# ------ Print the hostname FQDN as banner ----------------------------------
(
   maxWidth=$(tput cols)   # Console width in characters
   # Try the FQDN hostname as banner first. But it may be too long.
   if ! make-banner "$(hostname -f)" "${maxWidth}" ; then
      # Try the hostname only, if the FQDN is too long.
      if ! make-banner "$(hostname -s)" "${maxWidth}" ; then
         # Something went wrong. Just print the hostname as non-banner string.
         hostname -f
      fi
   fi
) | while IFS= read -r line ; do
   center "${line}"
done

# ------ Print bottom separator ---------------------------------------------
echo -en "${reset}${color1}"
separator " *💻" "=" "💻*"
echo -e "${reset}"


# ====== Finish =============================================================

# With exit code 1, no further files in /etc/system-info.d are processed.
# Use exit code 0 to continue processing files.
exit 1   # 1 => No further processing
