#!/usr/bin/env bash
# ==========================================================================
#  ___         _        _ _      _   _            ___         _      _
# |_ _|_ _  __| |_ __ _| | |__ _| |_(_)___ _ _   / __| __ _ _(_)_ __| |_ ___
#  | || ' \(_-<  _/ _` | | / _` |  _| / _ \ ' \  \__ \/ _| '_| | '_ \  _(_-<
# |___|_||_/__/\__\__,_|_|_\__,_|\__|_\___/_||_| |___/\__|_| |_| .__/\__/__/
#                                                              |_|
#
#   --- Virtual Machine Image Builder and System Installation Scripts ---
#            https://www.nntb.no/~dreibh/vmimage-builder-scripts/
# ==========================================================================
#
# System Installation Scripts
# Copyright (C) 2017-2026 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

# Bash options:
set -euo pipefail


# ###########################################################################
# The Minimal installation only contains the default packages of the
# distribution's installer, as well as tools needed for the initial system
# installation with these scripts:
# * [Bash](https://www.gnu.org/software/bash/) (shell)
# * [cURL](https://curl.se/) (download tool)
# * [Git](https://git-scm.com/) (revision management)
# * [GnuPG](https://www.gnupg.org/) (cryptography for signature checks)
# * [Ping](https://linux.die.net/man/8/ping) (network connectivity check)
# * [Sudo](https://www.sudo.ws/) (privileged command execution)
# * [Virt-What](https://people.redhat.com/~rjones/virt-what/) (identification of virtualisation environment)
# ###########################################################################


# ###### Print script name, to make Packer output easier readable ###########
if command -v figlet >/dev/null && command -v print-utf8 >/dev/null ; then
   echo
   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;31m█" "▀" "█\e[0m"
   figlet -w 156 "$(basename "$0")" | LC_ALL=C.UTF-8 print-utf8 -x 160 -n -C "\e[1;31m█\e[22m" "\e[1;31m█\e[0m"
   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;31m█" "▄" "█\e[0m"
else
   echo -e "\e[1;31;22m########## $(basename "$0") ##########\e[0m"
fi

# Enable printing the command-lines executed:
set -x


# ###### Main program #######################################################

# ====== Obtain system details ==============================================
UNAME="$(uname)"
NAME="${UNAME}"
ID="${UNAME,,}"
VERSION="$(uname -r)"
VERSION_ID="${VERSION/_*/}"
if [ -f /etc/os-release ] ; then
   . /etc/os-release
fi


# ====== Package installation ===============================================

# ------ Ubuntu/Debian ------------------------------------------------------
if [ "${ID}" == "ubuntu" ] || [ "${ID}" == "debian" ] ; then

   # Make 3 APT package download retries, in case of network problems:
   echo 'Acquire::Retries "3";' >/etc/apt/apt.conf.d/80retries

   # ------ Ubuntu: add PPA dreibh/ppa --------------------------------------
   if [ "${ID}" == "ubuntu" ] ; then
      apt-get update
      env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
         software-properties-common
      if [[ "${VERSION_ID}" =~ ^22\.[01][04]$ ]] ; then
         # Ubuntu 22.04 fix: gpg-agent + dirmngr are needed.
         env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
            gpg-agent dirmngr
      fi
      apt-add-repository -y ppa:dreibh/ppa

   # ------ Debian: add Open Build Service PPA home:dreibh ------------------
   elif [ "${ID}" == "debian" ] ; then
      apt-get update
      env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
         gnupg curl

      if [[ "${VERSION_ID}" =~ ^[0-9]+$ ]] ; then
         ppaDistribution="Debian_${VERSION_ID^}"
      else
         suites="$(grep "^Suites:" /etc/apt/sources.list.d/debian.sources | sed -e "s/.*://" | head -n1) "   # Note the trailing space!
         if [[ "${suites}" =~ ( unstable ) ]] ; then
            ppaDistribution="Debian_Unstable"
         elif [[ "${suites}" =~ ( testing ) ]] ; then
            ppaDistribution="Debian_Testing"
         else
            ppaDistribution="Debian_${VERSION_CODENAME^}"
         fi
      fi
      echo "ppaDistribution=${ppaDistribution}"

      curl -fsSL "https://build.opensuse.org/projects/home:dreibh/signing_keys/download?kind=gpg" \
         | gpg --dearmor \
         | tee /etc/apt/keyrings/dreibh-obs.gpg >/dev/null
      (
         cat <<EOF
deb [signed-by=/etc/apt/keyrings/dreibh-obs.gpg] https://download.opensuse.org/repositories/home:/dreibh/${ppaDistribution}/ /
# deb-src [signed-by=/etc/apt/keyrings/dreibh-obs.gpg] https://download.opensuse.org/repositories/home:/dreibh/${ppaDistribution}/ /
EOF
      ) | tee /etc/apt/sources.list.d/obs-dreibh.list >/dev/null
   fi

   # Ensure that the installed packages are up-to-date:
   apt-get update
   env DEBIAN_FRONTEND=noninteractive apt-get dist-upgrade -y

   packages=(
      bash
      bash-completion
      ca-certificates
      curl
      git
      gnupg
      iputils-ping
      openssh-server
      sudo
      virt-what
   )

   # Old Ubuntu versions 12.04/14.04/16.04 show a splash image during boot,
   # which may lead to a blank screen -> turning splash off as work-around:
   if [ "${ID}" == "ubuntu" ] && [[ "${VERSION_ID}" =~ ^1[246]\.[01][04]$ ]] ; then
      if [ -e /etc/default/grub ] ; then
         sed -e 's/^GRUB_CMDLINE_LINUX_DEFAULT=\(.*\) splash\(.*\)$/GRUB_CMDLINE_LINUX_DEFAULT=\1\2/' \
             -i /etc/default/grub
         update-grub
      fi
   fi

   env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends "${packages[@]}"

   # Remove unused Canonical stuff:
   if [ "${ID}" == "ubuntu" ] ; then
      env DEBIAN_FRONTEND=noninteractive apt-get autoremove -y --purge \
         ubuntu-pro-client landscape-common || true
   fi

# ------ Fedora -------------------------------------------------------------
elif [ "${ID}" == "fedora" ] ; then

   # Make sure that DNF has COPR support:
   dnf install --setopt=install_weak_deps=False -y 'dnf-command(copr)'

   # Add COPR PPA dreibh/ppa:
   dnf copr enable -y dreibh/ppa

   # Ensure that the installed packages are up-to-date:
   dnf upgrade -y

   packages=(
      bash
      bash-completion
      ca-certificates
      curl
      dnf-automatic
      git
      gnupg2
      iputils
      kernel-modules-extra
      openssh-server
      sudo
      virt-what
   )

   dnf install --setopt=install_weak_deps=False -y "${packages[@]}"

# ------ OpenSUSE -----------------------------------------------------------
elif [[ "${ID}" =~ ^opensuse- ]] ; then

   # Add Open Build Service PPA home:dreibh
   if [[ "${VERSION_ID}" =~ ^[0-9]+\.[0-9]+$ ]] ; then
      ppaDistribution="${VERSION_ID}"
   else
      ppaDistribution="${NAME/ /_}"
   fi
   echo "ppaDistribution=${ppaDistribution}"
   rpm --import "https://download.opensuse.org/repositories/home:/dreibh/${ppaDistribution}/repodata/repomd.xml.key"
   zypper addrepo -f "https://download.opensuse.org/repositories/home:/dreibh/${ppaDistribution}/" dreibh-obs || true

   # Ensure that the installed packages are up-to-date:
   zypper --non-interactive update -y

   packages=(
      bash
      bash-completion
      ca-certificates
      curl
      dnf-automatic
      git
      gnupg
      iputils
      openssh-server
      sudo
      virt-what
   )

   zypper --non-interactive install --no-recommends -y "${packages[@]}"

# ------ Alpine -------------------------------------------------------------
elif [ "${ID}" == "alpine" ] ; then

   # Add Open Build Service PPA home:dreibh
   ppaDistribution="Alpine_Latest_community"
   sudo wget -O \
      /etc/apk/keys/home:dreibh@build.opensuse.org-527a4e72.rsa.pub \
      https://download.opensuse.org/repositories/home:/dreibh/${ppaDistribution}/x86_64/home:dreibh%40build.opensuse.org-527a4e72.rsa.pub
   echo "https://download.opensuse.org/repositories/home:/dreibh/${ppaDistribution}" | \
      sudo tee -a /etc/apk/repositories >/dev/null

   packages=(
      bash
      bash-completion
      ca-certificates
      curl
      fstrim
      git
      gnupg
      iputils
      musl-locales
      openssh-server
      shadow
      sudo
      virt-what
   )

   apk add "${packages[@]}"

# ------ FreeBSD ------------------------------------------------------------
elif [ "${ID}" == "freebsd" ] ; then

   # Ensure that the installed packages are up-to-date:
   env ASSUME_ALWAYS_YES=yes pkg upgrade -y

   packages=(
      bash
      bash-completion
      curl
      git
      gnupg
      sudo
      virt-what
   )
   pkg install -y "${packages[@]}"

   # ------ Prepare FreeBSD Sources -----------------------------------------
   mkdir -p /usr/src
   cd /usr/src
   if [ ! -e .git/config ] ; then
      git init -b main
      git remote add freebsd https://github.com/freebsd/freebsd.git
      git config --add remote.freebsd.fetch "+refs/notes/*:refs/notes/*"
      git config pull.rebase true
      # Not running this here:
      # git fetch freebsd
      # git checkout main
   fi

   # ------ Prepare FreeBSD Ports Collection --------------------------------
   mkdir -p /usr/ports
   cd /usr/ports
   # See: https://wiki.freebsd.org/Ports/GitQuickStart
   if [ ! -e .git/config ] ; then
      git init -b main
      git remote add freebsd https://git.freebsd.org/ports.git
      git remote set-url --push freebsd ssh://git@gitrepo.freebsd.org/ports.git
      git config --add remote.freebsd.fetch "+refs/notes/*:refs/notes/*"
      git config pull.rebase true
      # Not running this here:
      # git fetch freebsd
      # git checkout main
   fi

# ------ NetBSD -------------------------------------------------------------
elif [ "${ID}" == "netbsd" ] ; then

   pkgin update
   pkgin -y upgrade

   packages=(
      bash
      bash-completion
      curl
      git
      gnupg2
      mozilla-rootcerts-openssl
      pkg_alternatives
      sudo
      virt-what
   )
   pkgin -y install "${packages[@]}"

   # ------ Prepare NetBSD Ports Collection ---------------------------------
   mkdir -p /usr/pkgsrc
   cd /usr/pkgsrc
   if [ ! -e .git/config ] ; then
      git init -b trunk
      git remote add origin https://github.com/NetBSD/pkgsrc.git
      git config pull.rebase true
      # Not running this here:
      # git fetch trunk
      # git checkout trunk
   fi

# ------ OpenBSD ------------------------------------------------------------
elif [ "${ID}" == "openbsd" ] ; then

   packages=(
      bash
      bash-completion
      curl
      git
      gnupg
      sudo--
      virt-what
   )
   pkg_add -r -I "${packages[@]}"

   # ------ Prepare OpenBSD Ports Collection --------------------------------
   mkdir -p /usr/ports
   chgrp wsrc /usr/ports
   chmod 775 /usr/ports
   cd /usr/ports
   if [ ! -e .git/config ] ; then
      git init -b master
      git remote add origin https://github.com/openbsd/ports.git
      git config pull.rebase true
      # Not running this here:
      # git fetch master
      # git checkout master
   fi

# ------ Solaris ------------------------------------------------------------
elif [ "${ID}" == "sunos" ] ; then

   packages=(
      bash
      bash-completion
      curl
      git
      gnupg
      sudo
      # virt-what
   )
   pkg install "${packages[@]}" || [ $? -eq 4 ]

   # Add Spec Files Extra (SFE) repository:
   pkg set-publisher -G '*' -g https://sfe.opencsw.org/localhostoih localhostoih

   # Running "sudo" as root has to be allowed (root is superuser):
   echo "Defaults:root !pam_acct_mgmt" >/etc/sudoers.d/01-sudo-no_pam_acct_mgmt
   chown root:root /etc/sudoers.d/01-sudo-no_pam_acct_mgmt
   chmod 0440 /etc/sudoers.d/01-sudo-no_pam_acct_mgmt
   visudo -c

# ------ Unknown ------------------------------------------------------------
else

   echo >&2 "ERROR: Unknown ID ${ID} in /etc/os-release. The installation script may need an update for supporting this system!"
   exit 1

fi


# ====== Verify command availability ========================================

# ------ Prepare list of required commands ----------------------------------
programs=(
   bash
   curl
   git
   gpg
   ping
   sudo
)

if [ "${ID}" == "sunos" ] ; then
   true   # No virt-what for Solaris
else
   programs+=( virt-what )
fi


# ------ Verify command availability ----------------------------------------
set +x
echo "Verifying command availability:"
errors=0
missing=()
for command in "${programs[@]}" ; do
   if ! command -v "${command}" >/dev/null 2>&1 ; then
      errors=$((errors+1))
      missing+=( "${command}" )
   fi
done
if [ ${errors} -gt 0 ] ; then
   echo >&2 "ERROR: ${errors} commands are missing:"
   (
      for program in "${missing[@]}" ; do
         echo >&2 " * ${program}"
      done
   ) | sort
   exit 1
else
   echo "OK"
fi
set -x
