#!/usr/bin/env bash
#
# Autoinstall Scripts
# Copyright (C) 2017-2024 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

# Bash options:
set -e


# ###########################################################################
# The Minimal installation only contains the default packages of the
# distribution's installer, as well as tools needed for the initial system
# installation with these scripts:
# - Bash (shell)
# - cURL (download tool)
# - Git (revision management)
# - GnuPG (cryptography for signature checks)
# - Ping (network connectivity check)
# - Sudo (privileged command execution)
# - Virt-What (identification of virtualisation environment)
#
# Further properties:
# - Bash as default shell
# - ECN enabled
# - SCTP enabled
# - SSH server enabled
# - Hardened SSH server and client settings
# - UTF-8 character encoding
# ###########################################################################


# ====== Package installation ===============================================

# ------ Ubuntu -------------------------------------------------------------
if [ -e /usr/bin/apt-get ] ; then

   # Make 3 APT package download retries, in case of network problems:
   echo 'Acquire::Retries "3";' >/etc/apt/apt.conf.d/80retries

   # Ensure that the package database is up-to-date:
   /usr/bin/apt-get update

   packages="
      bash
      bash-completion
      curl
      git
      gpg
      sudo
      virt-what
   "

   # shellcheck disable=SC2086
   env DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get install -y --no-install-recommends ${packages}

# ------ Fedora -------------------------------------------------------------
elif [ -e /usr/bin/dnf ] ; then

   packages="
      bash
      bash-completion
      curl
      git
      gpg
      sudo
      virt-what
   "

   # shellcheck disable=SC2086
   /usr/bin/dnf install -y sddm ${packages}

# ------ FreeBSD ------------------------------------------------------------
elif [ -e /usr/sbin/pkg ] ; then

   packages="
      bash
      bash-completion
      curl
      git
      gnupg
      sudo
      virt-what
   "

   # shellcheck disable=SC2086
   /usr/sbin/pkg install -y ${packages}

   # ------ Prepare FreeBSD Sources -----------------------------------------
   cd /usr/src
   /usr/local/bin/git init -b main
   /usr/local/bin/git remote add freebsd https://github.com/freebsd/freebsd.git
   /usr/local/bin/git config --add remote.freebsd.fetch "+refs/notes/*:refs/notes/*"
   /usr/local/bin/git config pull.rebase true
   # Not running this here:
   # /usr/local/bin/git fetch freebsd
   # /usr/local/bin/git checkout main

   # ------ Prepare FreeBSD Ports Collection --------------------------------
   # See: https://wiki.freebsd.org/Ports/GitQuickStart
   cd /usr/ports
   /usr/local/bin/git init -b main
   /usr/local/bin/git remote add freebsd https://git.freebsd.org/ports.git
   /usr/local/bin/git remote set-url --push freebsd ssh://git@gitrepo.freebsd.org/ports.git
   /usr/local/bin/git config --add remote.freebsd.fetch "+refs/notes/*:refs/notes/*"
   /usr/local/bin/git config pull.rebase true
   # Not running this here:
   # /usr/local/bin/git fetch freebsd
   # /usr/local/bin/git checkout main

fi


# ====== Verify command availability ========================================
echo "Verifying command availability:"
errors=0
for command in bash curl git gpg ping sudo virt-what ; do
   echo -n "${command}: "
   if which ${command} >/dev/null ; then
      echo "OK"
   else
      echo "FAILED!"
      errors=$((errors+1))
   fi
done
if [ ${errors} -gt 0 ] ; then
   echo >&2 "ERROR: ${errors} packages are missing!"
   exit 1
fi
