#!/usr/bin/env bash
# ==========================================================================
#  ___         _        _ _      _   _            ___         _      _
# |_ _|_ _  __| |_ __ _| | |__ _| |_(_)___ _ _   / __| __ _ _(_)_ __| |_ ___
#  | || ' \(_-<  _/ _` | | / _` |  _| / _ \ ' \  \__ \/ _| '_| | '_ \  _(_-<
# |___|_||_/__/\__\__,_|_|_\__,_|\__|_\___/_||_| |___/\__|_| |_| .__/\__/__/
#                                                              |_|
#
#   --- Virtual Machine Image Builder and System Installation Scripts ---
#            https://www.nntb.no/~dreibh/vmimage-builder-scripts/
# ==========================================================================
#
# System Installation Scripts
# Copyright (C) 2017-2026 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

# Bash options:
set -euo pipefail


# ###### Print script name, to make Packer output easier readable ###########
if command -v figlet >/dev/null && command -v print-utf8 >/dev/null ; then
   echo
   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;31m█" "▀" "█\e[0m"
   figlet -w 156 "$(basename "$0")" | LC_ALL=C.UTF-8 print-utf8 -x 160 -n -C "\e[1;31m█\e[22m" "\e[1;31m█\e[0m"
   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;31m█" "▄" "█\e[0m"
else
   echo -e "\e[1;31;22m########## $(basename "$0") ##########\e[0m"
fi

# Enable printing the command-lines executed:
set -x


# ###### Main program #######################################################

# ====== Check/set environment variables ====================================
if [ ! -v LOCALES ] || [ "${LOCALES}" == "" ] ; then
   echo >&2 "Usage: env LOCALES=\"locales,...\" $0"
   echo >&2 "Example: sudo env LOCALES=\"de_DE en_IE en_US nb_NO\" $0"
   exit 1
fi

# ====== Obtain system details ==============================================
UNAME="$(uname)"
NAME="${UNAME}"
ID="${UNAME,,}"
VERSION="$(uname -r)"
VERSION_ID="${VERSION/_*/}"
if [ -f /etc/os-release ] ; then
   . /etc/os-release
fi


# ====== Package installation ===============================================

# ------ Ubuntu/Debian ------------------------------------------------------
if [ "${ID}" == "ubuntu" ] || [ "${ID}" == "debian" ] ; then

   packages=(
      locales
      tzdata
   )
   env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends "${packages[@]}"

   # Locales:
   for locale in ${LOCALES} ; do
      if grep -q -E "^#[[:blank:]]*${locale}\.UTF-8" /etc/locale.gen; then
         sed -i -E "s/^#[[:blank:]]*(${locale}\.UTF-8[[:blank:]]+UTF-8)/\1/" /etc/locale.gen
      elif ! grep -q "^${locale}\.UTF-8" /etc/locale.gen; then
         echo "${locale}.UTF-8 UTF-8" >>/etc/locale.gen
      fi
   done
   locale-gen

# ------ Fedora -------------------------------------------------------------
elif [ "${ID}" == "fedora" ] ; then

   packages=(
      glibc-locale-source
   )
   dnf install --setopt=install_weak_deps=False -y "${packages[@]}"

   # Locales:
   for locale in ${LOCALES} ; do
      localedef -c -i "${locale}" -f UTF-8 "${locale}.UTF-8"
   done

# ------ OpenSUSE -----------------------------------------------------------
elif [[ "${ID}" =~ ^opensuse- ]] ; then

   packages=(
      glibc-i18ndata
   )
   zypper --non-interactive install --no-recommends -y "${packages[@]}"

   # Locales:
   for locale in ${LOCALES} ; do
      localedef -c -i "${locale}" -f UTF-8 "${locale}.UTF-8"
   done

# ------ Alpine -------------------------------------------------------------
elif [ "${ID}" == "alpine" ] ; then

   packages=(
      musl-locales
      musl-locales-lang
      tzdata
   )
   apk add "${packages[@]}"

# ------ FreeBSD, NetBSD, OpenBSD -------------------------------------------
elif [ "${UNAME}" == "FreeBSD" ] ||
     [ "${UNAME}" == "NetBSD"  ] ||
     [ "${UNAME}" == "OpenBSD" ] ||
     [ "${UNAME}" == "SunOS" ] ; then

   # All locales should already be there!
   true

# ------ Unknown ------------------------------------------------------------
else

   echo >&2 "ERROR: Unknown ID ${ID} in /etc/os-release. The installation script may need an update for supporting this system!"
   exit 1

fi


# ====== Show available locales =============================================
set +x

# ------ Show available locales ---------------------------------------------
installedLocales="$(locale -a | sed -e 's/\..*//' | sort -u)"
echo "Available locales:"
echo "${installedLocales}" | xargs

# ------ Verify availability of requested locales ---------------------------
missingLocales=()
for locale in ${LOCALES} ; do
   if ! grep -iq "^${locale}" <<< "${installedLocales}" ; then
      missingLocales+=("${locale}")
   fi
done
if [ ${#missingLocales[@]} -ne 0 ] ; then
   if [ "${UNAME}" == "FreeBSD" ] ||
      [ "${UNAME}" == "NetBSD"  ] ||
      [ "${UNAME}" == "OpenBSD" ] ||
      [ "${UNAME}" == "SunOS" ] ; then
      # Some locales are missing, e.g. ar_YE, bs_BA, en_DK.
      # This can only be fixed upstream.
      echo >&2 "WARNING: Some locales are missing: ${missingLocales[*]}!"
   else
      echo >&2 "ERROR: Some locales are missing: ${missingLocales[*]}!"
      exit 1
   fi
fi
set -x
