#!/usr/bin/env bash
# ==========================================================================
#  ___         _        _ _      _   _            ___         _      _
# |_ _|_ _  __| |_ __ _| | |__ _| |_(_)___ _ _   / __| __ _ _(_)_ __| |_ ___
#  | || ' \(_-<  _/ _` | | / _` |  _| / _ \ ' \  \__ \/ _| '_| | '_ \  _(_-<
# |___|_||_/__/\__\__,_|_|_\__,_|\__|_\___/_||_| |___/\__|_| |_| .__/\__/__/
#                                                              |_|
#
#   --- Virtual Machine Image Builder and System Installation Scripts ---
#            https://www.nntb.no/~dreibh/vmimage-builder-scripts/
# ==========================================================================
#
# System Installation Scripts
# Copyright (C) 2017-2026 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

# Bash options:
set -euo pipefail


# ###### Print script name, to make Packer output easier readable ###########
if command -v figlet >/dev/null && command -v print-utf8 >/dev/null ; then
   echo
   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;31m█" "▀" "█\e[0m"
   figlet -w 156 "$(basename "$0")" | LC_ALL=C.UTF-8 print-utf8 -x 160 -n -C "\e[1;31m█\e[22m" "\e[1;31m█\e[0m"
   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;31m█" "▄" "█\e[0m"
else
   echo -e "\e[1;31;22m########## $(basename "$0") ##########\e[0m"
fi

# Enable printing the command-lines executed:
set -x


# ###### Main program #######################################################

# ====== Check/set environment variables ====================================
if [ ! -v USER_NAME ]     || [ "${USER_NAME}"     == "" ] || \
   [ ! -v USER_REALNAME ] || [ "${USER_REALNAME}" == "" ] ; then
   echo >&2 "Usage: env USER_NAME=<user> USER_REALNAME=\"<full user name>\" $0"
   echo >&2 "Example: sudo env USER_NAME=nornetpp USER_REALNAME=\"NorNet Praesum Presum\" $0"
   exit 1
fi
USER_GROUP="$(id -gn "${USER_NAME}")"
USER_HOME="$(getent passwd "${USER_NAME}" | cut -d: -f6 || awk -F: -v user="${USER_NAME}" '$1==user { print $6 }' /etc/passwd)"

# ====== Obtain system details ==============================================
UNAME="$(uname)"
NAME="${UNAME}"
ID="${UNAME,,}"
VERSION="$(uname -r)"
VERSION_ID="${VERSION/_*/}"
if [ -f /etc/os-release ] ; then
   . /etc/os-release
fi


# ====== Initial .bashrc ====================================================
if [ -e /tmp/configuration-files/bashrc ] ; then
   cp /tmp/configuration-files/bashrc "${USER_HOME}/.bashrc"
   if [ "${ID}" == "freebsd" ]  ; then
      cp /tmp/configuration-files/bashrc /usr/share/skel/.bashrc
   else
      cp /tmp/configuration-files/bashrc /etc/skel/.bashrc
   fi
fi

if [ "${ID}" == "freebsd" ] ; then
   if [ ! -e "${USER_HOME}/.bash_profile" ] ; then
      cat >"${USER_HOME}/.bash_profile" <<EOF
test -f ~/.bashrc && source ~/.bashrc
EOF
   fi
   chown "${USER_NAME}":"${USER_GROUP}" "${USER_HOME}/.bash_profile"
fi


# ====== Make some additions to .bashrc =====================================
if [ ! -e "${USER_HOME}/.bashrc" ] ; then
   touch "${USER_HOME}/.bashrc"
fi
cat >>"${USER_HOME}/.bashrc" <<EOF


# ---------------------------------------------------------------------------

alias runws="sudo echo Starting Wireshark && ( sudo wireshark & )"

ulimit -c unlimited

export EDITOR=joe
export CVSEDITOR=\${EDITOR}
export SVN_EDITOR=\${EDITOR}
export XZ_DEFAULTS="--threads=0"

if [ "\$(uname)" = "FreeBSD" ] ; then
   cores=\$(sysctl -n hw.ncpu 2>/dev/null || echo "1")
else
   cores=\$(getconf _NPROCESSORS_ONLN 2>/dev/null || echo "1")
fi
if [ -n "\${cores}" ] && [ "\${cores}" -gt 1 ] ; then
   export MAKEFLAGS="-j\${cores}"
fi
EOF
chown "${USER_NAME}":"${USER_GROUP}" "${USER_HOME}/.bashrc"


# ====== Make some directories ==============================================
sudo -u "${USER_NAME}" mkdir -p "${USER_HOME}/src"
if command -v chattr 2>/dev/null ; then
   sudo -u "${USER_NAME}" chattr +c "${USER_HOME}/src" || true
fi
sudo -u "${USER_NAME}" mkdir -p "${USER_HOME}/tmp"

sudo -u "${USER_NAME}" mkdir -p "${USER_HOME}/.ssh"
sudo -u "${USER_NAME}" chmod 700 "${USER_HOME}/.ssh"
sudo -u "${USER_NAME}" touch "${USER_HOME}/.ssh/authorized_keys"
sudo -u "${USER_NAME}" chmod 600 "${USER_HOME}/.ssh/authorized_keys"

sudo -u "${USER_NAME}" mkdir -p "${USER_HOME}/.cache"
sudo -u "${USER_NAME}" chmod 700 "${USER_HOME}/.cache"


# ====== Git configuration file =============================================
if ! sudo -u "${USER_NAME}" test -e "${USER_HOME}/.gitconfig" ; then
   hostname="$(hostname -f 2>/dev/null || hostname 2>/dev/null || echo "localhost")"
   (
      cat <<EOF
[user]
	name = ${USER_REALNAME}
	email = ${USER_NAME}@${hostname}
[push]
	default = simple
	autoSetupRemote = true
[pull]
	rebase = false
[init]
	defaultBranch = master
[commit]
	# Enable GnuPG by default signing here (needs key setup first):
	# gpgsign = true
[color]
	ui = auto
EOF
   ) | sudo -u "${USER_NAME}" tee "${USER_HOME}/.gitconfig"
fi


# ====== GDB configuration file =============================================
if ! sudo -u "${USER_NAME}" test -e "${USER_HOME}/.gdbinit" ; then
   (
      cat <<EOF
# Enable project-specific local configuration:
set auto-load safe-path /
set auto-load local-gdbinit on

# Load missing debug information:
set debuginfod enabled on

# Disable pagination:
set pagination off

# Enable Text User Interface (TUI):
tui enable
focus cmd
# NOTE: <Shift> key is needed for normal console text selection!
#       This can be turned off here:
# set tui mouse-events off

# Command history:
set history save on
set history filename ~/.gdb_history
set history size 10000

# Pretty printing for libstdc++:
python
import os
import sys
gcc_python_path = '/usr/share/gcc/python'
if os.path.exists(gcc_python_path):
   sys.path.insert(0, gcc_python_path)
   try:
      from libstdcxx.v6.printers import register_libstdcxx_printers
      register_libstdcxx_printers (None)
   except ImportError:
      pass
end
EOF
   ) | sudo -u "${USER_NAME}" tee "${USER_HOME}/.gdbinit"
fi


# ====== User icon ==========================================================
if [ "${UNAME}" == "Linux" ] ; then
   if [ -e /tmp/face-icons/Face-Tux.png ] ; then
      sudo -u "${USER_NAME}" cp /tmp/face-icons/Face-Tux.png "${USER_HOME}/.face.icon"
   fi
elif [ "${UNAME}" == "FreeBSD" ] ; then
   if [ -e /tmp/face-icons/Face-Beastie.png ] ; then
      sudo -u "${USER_NAME}" cp /tmp/face-icons/Face-Beastie.png "${USER_HOME}/.face.icon"
   fi
fi


# ====== GnuPG configuration file ===========================================
if ! sudo -u "${USER_NAME}" test -e "${USER_HOME}/.gnupg/gpg.conf" ; then
   sudo -u "${USER_NAME}" mkdir -p "${USER_HOME}/.gnupg"
   sudo -u "${USER_NAME}" chmod 700 "${USER_HOME}/.gnupg"
   (
      cat <<EOF
# use-agent
# default-key       <YOUR_DEFAULT_KEY_ID>
keyserver         hkps://keyserver.ubuntu.com
keyserver-options no-self-sigs-only
EOF
   ) | sudo -u "${USER_NAME}" tee "${USER_HOME}/.gnupg/gpg.conf"
fi


# ====== Import GnuPG public keys ===========================================
# Thomas Dreibholz's public keys for verifying package and Git signatures:
KEYS="21412672518D8B2D1862EFEF5CD5D12AA0877B49"
KEYSERVERS="keyserver.ubuntu.com"   # 162.213.33.8 162.213.33.9
for key in ${KEYS} ; do
   foundKey=0
   # ------ First, try to fetch the key from a key server -------------------
   # GnuPG is picky with the DNS server response, and OsloMet has a lot of
   # obscure firewall rules as well => this may fail here!
   for keyServer in ${KEYSERVERS} ; do
      if sudo -u "${USER_NAME}" gpg \
            --homedir "${USER_HOME}/.gnupg" \
            --keyserver "hkps://${keyServer}" \
            --keyserver-options no-self-sigs-only \
            --recv-keys "${key}" ; then
         echo "Got ${key} from ${keyServer}!"
         foundKey=1
         break
      fi
   done
   # ------ If this fails, try to fetch the key from the NNTB server --------
   if [ ${foundKey} -eq 0 ] ; then
      if command -v wget 2>/dev/null ; then
         wget "https://www.nntb.no/~dreibh/${key}.asc" -O "/tmp/${key}.asc" || true
      else
         curl "https://www.nntb.no/~dreibh/${key}.asc" >"/tmp/${key}.asc" || true
      fi
      if [ -f "/tmp/${key}.asc" ] ; then
         if sudo -u "${USER_NAME}" gpg \
               --homedir "${USER_HOME}/.gnupg" \
               --import "/tmp/${key}.asc" ; then
            echo "Got ${key} from NNTB web server!"
            foundKey=1
            break
         fi
      fi
   fi
   # ------ Check for success -----------------------------------------------
   if [ ${foundKey} -eq 0 ] ; then
      echo >&2 "ERROR: Unable to fetch key ${key}!"
      exit 1
   fi
done
