#!/usr/bin/env bash
# ==========================================================================
#  ___         _        _ _      _   _            ___         _      _
# |_ _|_ _  __| |_ __ _| | |__ _| |_(_)___ _ _   / __| __ _ _(_)_ __| |_ ___
#  | || ' \(_-<  _/ _` | | / _` |  _| / _ \ ' \  \__ \/ _| '_| | '_ \  _(_-<
# |___|_||_/__/\__\__,_|_|_\__,_|\__|_\___/_||_| |___/\__|_| |_| .__/\__/__/
#                                                              |_|
#
#   --- Virtual Machine Image Builder and System Installation Scripts ---
#            https://www.nntb.no/~dreibh/vmimage-builder-scripts/
# ==========================================================================
#
# System Installation Scripts
# Copyright (C) 2017-2026 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

# Bash options:
set -euo pipefail


# ###### Main program #######################################################

# ====== Print script name, to make Packer output easier readable ===========
SCRIPT="05-user-settings"   # Set to "$(basename "$0")" of this file!
if command -v figlet >/dev/null && command -v print-utf8 >/dev/null ; then
   echo
   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;31m█" "▀" "█\e[0m"
   figlet -w 156 "${SCRIPT}" | LC_ALL=C.UTF-8 print-utf8 -x 160 -n -C "\e[1;31m█\e[22m" "\e[1;31m█\e[0m"
   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;31m█" "▄" "█\e[0m"
else
   echo -e "\e[1;31;22m########## ${SCRIPT} ##########\e[0m"
fi

# ====== Check/set environment variables ====================================
if [ ! -v USER_NAME ]     || [ "${USER_NAME}"     == "" ] || \
   [ ! -v USER_REALNAME ] || [ "${USER_REALNAME}" == "" ] ; then
   echo >&2 "Usage: env USER_NAME=<user> USER_REALNAME=\"<full user name>\" $0"
   echo >&2 "Example: sudo env USER_NAME=nornetpp USER_REALNAME=\"NorNet Praesum Presum\" $0"
   exit 1
fi

# Enable printing the command-lines executed:
set -x

USER_GROUP="$(id -gn "${USER_NAME}")"
USER_HOME="$(getent passwd "${USER_NAME}" | cut -d: -f6 || awk -F: -v user="${USER_NAME}" '$1==user { print $6 }' /etc/passwd)"

# ====== Obtain system details ==============================================
UNAME="$(uname)"
NAME="${UNAME}"
ID="${UNAME,,}"
VERSION="$(uname -r)"
VERSION_ID="${VERSION/_*/}"
if [ -f /etc/os-release ] ; then
   . /etc/os-release
fi


# ====== Prepare skel directory =============================================
skelDirectory=""
skelDotPrefix=""
if [ "${ID}" == "freebsd" ]  ; then
   skelDirectory="/usr/share/skel"
   skelDotPrefix="dot."
else
   skelDirectory="/etc/skel"
   skelDotPrefix="."
fi
mkdir -p "${skelDirectory}"

if [ -f /tmp/installtmp/configuration-files/bashrc ] ; then
   cp /tmp/installtmp/configuration-files/bashrc  "${skelDirectory}/${skelDotPrefix}bashrc"
fi
if [ -f /tmp/installtmp/configuration-files/profile ] ; then
   cp /tmp/installtmp/configuration-files/profile "${skelDirectory}/${skelDotPrefix}profile"
fi
if [ -f /tmp/installtmp/configuration-files/gdbinit ] ; then
   cp /tmp/installtmp/configuration-files/gdbinit "${skelDirectory}/${skelDotPrefix}gdbinit"
fi
if [ -f /tmp/installtmp/configuration-files/gitconfig ] ; then
   cp /tmp/installtmp/configuration-files/gitconfig "${skelDirectory}/${skelDotPrefix}gitconfig"
fi

if [ "${UNAME}" == "Linux" ] ; then
   if [ -f /tmp/installtmp/face-icons/Face-Tux.png ] ; then
      cp /tmp/installtmp/face-icons/Face-Tux.png "${skelDirectory}/${skelDotPrefix}face.icon"
   fi
elif [ "${UNAME}" == "FreeBSD" ] ; then
   if [ -f /tmp/installtmp/face-icons/Face-Beastie.png ] ; then
      cp /tmp/installtmp/face-icons/Face-Beastie.png "${skelDirectory}/${skelDotPrefix}face.icon"
   fi
fi


# ====== Prepare user's .profile ============================================
if [ -f "${skelDirectory}/${skelDotPrefix}profile" ] ; then
   cp "${skelDirectory}/${skelDotPrefix}profile" "${USER_HOME}/.profile"
   chown "${USER_NAME}":"${USER_GROUP}" "${USER_HOME}/.profile"
fi


# ====== Prepare user's .bashrc =============================================
if [ ! -f "${USER_HOME}/.bashrc" ] || \
   ! grep -q "User Customisation" "${USER_HOME}/.bashrc" ; then
   if [ -f "${skelDirectory}/${skelDotPrefix}bashrc" ] ; then
      cp "${skelDirectory}/${skelDotPrefix}bashrc" "${USER_HOME}/.bashrc"
      chown "${USER_NAME}":"${USER_GROUP}" "${USER_HOME}/.bashrc"
   fi
fi


# ====== Prepare user's .gdbinit ============================================
if [ ! -f "${USER_HOME}/.gdbinit" ] && [ -f "${skelDirectory}/${skelDotPrefix}gdbinit" ] ; then
   cp "${skelDirectory}/${skelDotPrefix}gdbinit" "${USER_HOME}/.gdbinit"
   chown "${USER_NAME}":"${USER_GROUP}" "${USER_HOME}/.gdbinit"
fi


# ====== Prepare user's .gitconfig ==========================================
if [ ! -f "${USER_HOME}/.gitconfig" ] && [ -f "${skelDirectory}/${skelDotPrefix}gitconfig" ] ; then
   hostname="$(hostname -f 2>/dev/null || hostname 2>/dev/null || echo "localhost")"
   sed -e "s/^\([ \t]*\)\(#[ \t]*name[ \t]*=.*\)$/\1name = ${USER_REALNAME}/" \
       -e "s/^\([ \t]*\)\(#[ \t]*email[ \t]*=.*\)$/\1email = ${USER_NAME}@${hostname}/" \
       <"${skelDirectory}/${skelDotPrefix}gitconfig" >"${USER_HOME}/.gitconfig"
   chown "${USER_NAME}":"${USER_GROUP}" "${USER_HOME}/.gitconfig"
fi


# ====== User user's icon ===================================================
if [ -f "${skelDirectory}/${skelDotPrefix}face.icon" ] && [ -f "${skelDirectory}/${skelDotPrefix}face.icon" ] ; then
   cp "${skelDirectory}/${skelDotPrefix}face.icon" "${USER_HOME}/.face.icon"
   chown "${USER_NAME}":"${USER_GROUP}" "${USER_HOME}/.face.icon"
fi


# ====== Prepare user's directories =========================================
mkdir -p "${USER_HOME}/src"
if command -v chattr 2>/dev/null ; then
   chattr +c "${USER_HOME}/src" || true
fi
mkdir -p "${USER_HOME}/tmp"
chown "${USER_NAME}":"${USER_GROUP}" "${USER_HOME}/tmp"

mkdir -p "${USER_HOME}/.ssh"
chmod 700 "${USER_HOME}/.ssh"
chown "${USER_NAME}":"${USER_GROUP}" "${USER_HOME}/.ssh"
touch "${USER_HOME}/.ssh/authorized_keys"
chmod 600 "${USER_HOME}/.ssh/authorized_keys"
chown "${USER_NAME}":"${USER_GROUP}" "${USER_HOME}/.ssh/authorized_keys"

mkdir -p "${USER_HOME}/.cache"
chmod 700 "${USER_HOME}/.cache"
chown "${USER_NAME}":"${USER_GROUP}" "${USER_HOME}/.cache"


# ====== GnuPG configuration file ===========================================
if [ ! -f "${USER_HOME}/.gnupg/gpg.conf" ] ; then
   sudo -u "${USER_NAME}" mkdir -p "${USER_HOME}/.gnupg"
   sudo -u "${USER_NAME}" chmod 700 "${USER_HOME}/.gnupg"
   chown "${USER_NAME}":"${USER_GROUP}" "${USER_HOME}/.gnupg"
   cat >"${USER_HOME}/.gnupg/gpg.conf" <<EOF
# use-agent
# default-key       <YOUR_DEFAULT_KEY_ID>
keyserver         hkps://keyserver.ubuntu.com
keyserver-options no-self-sigs-only
EOF
   chmod 600 "${USER_HOME}/.gnupg/gpg.conf"
   chown "${USER_NAME}":"${USER_GROUP}" "${USER_HOME}/.gnupg/gpg.conf"
fi


# ====== Import GnuPG public keys ===========================================
# Thomas Dreibholz's public keys for verifying package and Git signatures:
KEYS="21412672518D8B2D1862EFEF5CD5D12AA0877B49"
KEYSERVERS="keyserver.ubuntu.com"   # 162.213.33.8 162.213.33.9
for key in ${KEYS} ; do
   foundKey=0
   # ------ First, try to fetch the key from a key server -------------------
   # GnuPG is picky with the DNS server response, and OsloMet has a lot of
   # obscure firewall rules as well => this may fail here!
   for keyServer in ${KEYSERVERS} ; do
      if sudo -u "${USER_NAME}" gpg \
            --homedir "${USER_HOME}/.gnupg" \
            --keyserver "hkps://${keyServer}" \
            --keyserver-options no-self-sigs-only \
            --recv-keys "${key}" ; then
         echo "Got ${key} from ${keyServer}!"
         foundKey=1
         break
      fi
   done
   # ------ If this fails, try to fetch the key from the NNTB server --------
   if [ ${foundKey} -eq 0 ] ; then
      if command -v wget 2>/dev/null ; then
         wget "https://www.nntb.no/~dreibh/${key}.asc" -O "/tmp/installtmp/${key}.asc" || true
      else
         curl "https://www.nntb.no/~dreibh/${key}.asc" >"/tmp/installtmp/${key}.asc" || true
      fi
      if [ -f "/tmp/installtmp/${key}.asc" ] ; then
         if sudo -u "${USER_NAME}" gpg \
               --homedir "${USER_HOME}/.gnupg" \
               --import "/tmp/installtmp/${key}.asc" ; then
            echo "Got ${key} from NNTB web server!"
            foundKey=1
            break
         fi
      fi
   fi
   # ------ Check for success -----------------------------------------------
   if [ ${foundKey} -eq 0 ] ; then
      echo >&2 "ERROR: Unable to fetch key ${key}!"
      exit 1
   fi
done
