#!/usr/bin/env bash
# ==========================================================================
#  ___         _        _ _      _   _            ___         _      _
# |_ _|_ _  __| |_ __ _| | |__ _| |_(_)___ _ _   / __| __ _ _(_)_ __| |_ ___
#  | || ' \(_-<  _/ _` | | / _` |  _| / _ \ ' \  \__ \/ _| '_| | '_ \  _(_-<
# |___|_||_/__/\__\__,_|_|_\__,_|\__|_\___/_||_| |___/\__|_| |_| .__/\__/__/
#                                                              |_|
#
#   --- Virtual Machine Image Builder and System Installation Scripts ---
#            https://www.nntb.no/~dreibh/vmimage-builder-scripts/
# ==========================================================================
#
# System Installation Scripts
# Copyright (C) 2017-2026 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

# Bash options:
set -euo pipefail


# WARNING:
# Make sure to only add this script if the password-less sudo is intended
# for the purpose of the VM!


# ###### Print script name, to make Packer output easier readable ###########
SCRIPT="06-sudo-without-password"   # Set to "$(basename "$0")" of this file!
if command -v figlet >/dev/null && command -v print-utf8 >/dev/null ; then
   echo
   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;31m█" "▀" "█\e[0m"
   figlet -w 156 "${SCRIPT}" | LC_ALL=C.UTF-8 print-utf8 -x 160 -n -C "\e[1;31m█\e[22m" "\e[1;31m█\e[0m"
   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;31m█" "▄" "█\e[0m"
else
   echo -e "\e[1;31;22m########## ${SCRIPT} ##########\e[0m"
fi

# Enable printing the command-lines executed:
set -x


# ###### Main program #######################################################

# ====== Check/set environment variables ====================================
if [ ! -v USER_NAME ] || [ "${USER_NAME}" == "" ] ; then
   echo >&2 "Usage: env USER_NAME=<user> $0"
   echo >&2 "Example: sudo env USER_NAME=nornetpp $0"
   exit 1
fi

# ====== Obtain system details ==============================================
UNAME="$(uname)"
NAME="${UNAME}"
ID="${UNAME,,}"
VERSION="$(uname -r)"
VERSION_ID="${VERSION/_*/}"
if [ -f /etc/os-release ] ; then
   . /etc/os-release
fi


# ====== Password-less "sudo" for the default user ==========================
if [ "${UNAME}" == "FreeBSD" ] ; then
   sudoersFile="/usr/local/etc/sudoers.d/99-${USER_NAME}"
elif [ "${UNAME}" == "NetBSD" ] ; then
   sudoersFile="/usr/pkg/etc/sudoers.d/99-${USER_NAME}"
else
   sudoersFile="/etc/sudoers.d/99-${USER_NAME}"
fi
mkdir -p "$(dirname "${sudoersFile}")"
cat >"${sudoersFile}" << EOF
# Allow password-less sudo for ${USER_NAME}:
${USER_NAME} ALL=(ALL:ALL) NOPASSWD: ALL
EOF
chown 0:0 "${sudoersFile}"
chmod 0440 "${sudoersFile}"
visudo -c

# FreeBSD: Ensure the main sudoers configuration imports the sudoers.d directory:
if [ "${UNAME}" == "FreeBSD" ] ; then
   if [ -e /usr/local/etc/sudoers ] && \
      ! grep -q "^@includedir" /usr/local/etc/sudoers ; then
      echo "" >>/usr/local/etc/sudoers
      echo "@includedir /usr/local/etc/sudoers.d" >>/usr/local/etc/sudoers
   fi
fi


# ===== Validate sudoers syntax =============================================
if command -v visudo >/dev/null 2>&1 ; then
   visudo -c -f "${sudoersFile}"
fi
