#!/usr/bin/env bash
#
# Autoinstall Scripts
# Copyright (C) 2017-2024 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

# Bash options:
set -ex


# WARNING:
# Make sure to only add this script if the password-less sudo is intended
# for the purpose of the VM!


# ====== Check environment variables ========================================
if [ "${USER_NAME}" == "" ] ; then
   echo >&2 "Usage: env USER_NAME=<user> $0"
   echo >&2 "Example: sudo env USER_NAME=nornetpp $0"
   exit 1
fi


# ====== Password-less "sudo" for the default user ==========================
if [ "$(uname)" == "FreeBSD" ] ; then
   sudoersFile="/usr/local/etc/sudoers.d/99-${USER_NAME}"
else
   sudoersFile="/etc/sudoers.d/99-${USER_NAME}"
fi

cat >"${sudoersFile}" << EOF
# Allow password-less sudo for ${USER_NAME}:
${USER_NAME} ALL=(ALL) NOPASSWD:ALL
EOF
