#!/usr/bin/env bash
# ==========================================================================
#  ___         _        _ _      _   _            ___         _      _
# |_ _|_ _  __| |_ __ _| | |__ _| |_(_)___ _ _   / __| __ _ _(_)_ __| |_ ___
#  | || ' \(_-<  _/ _` | | / _` |  _| / _ \ ' \  \__ \/ _| '_| | '_ \  _(_-<
# |___|_||_/__/\__\__,_|_|_\__,_|\__|_\___/_||_| |___/\__|_| |_| .__/\__/__/
#                                                              |_|
#
#   --- Virtual Machine Image Builder and System Installation Scripts ---
#            https://www.nntb.no/~dreibh/vmimage-builder-scripts/
# ==========================================================================
#
# System Installation Scripts
# Copyright (C) 2017-2026 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

# Bash options:
set -euo pipefail


# ###########################################################################
# The "Basic" installation is based on the "Minimal" installation.
# It must contain the following packages:
# * [ACL](https://savannah.nongnu.org/projects/acl/) (Tools for ACL configuration, particularly getfacl and setfacl commands)
# * [Base64](https://linux.die.net/man/1/base64) (base64 tool)
# * [BIND Tools](https://www.isc.org/bind/) (DNS testing, particularly dig and delv commands)
# * [BWM-NG](https://github.com/vgropp/bwm-ng) (simple bandwidth monitor)
# * [BZip2](https://sourceware.org/bzip2/) (compression tool)
# * [EthTool](https://mirrors.edge.kernel.org/pub/software/network/ethtool/) (Ethernet card configuration tool; on Linux systems only!)
# * [Fail2Ban](https://github.com/fail2ban/fail2ban) (prevent brute-force SSH attacks)
# * [GDisk](https://sourceforge.net/projects/gptfdisk/) (GPT partitioning tool)
# * [GrowPart](https://manpages.ubuntu.com/manpages/resolute/en/man1/growpart.1.html) (Partition growing tool; on Linux systems only!)
# * [IDN](https://www.gnu.org/software/libidn/manual/html_node/Invoking-idn.html) (Internationalised Domain Names command line tool)
# * [GNU Parallel](https://www.gnu.org/software/parallel/) (Parallel job execution)
# * [GNU Wget](https://www.gnu.org/software/wget/) (download tool)
# * [HiPerConTracer](https://www.nntb.no/~dreibh/hipercontracer/) (high-performance network tracing tool)
# * [HTop](https://htop.dev/) (process monitor)
# * [ifconfig](https://linux.die.net/man/8/ifconfig) (basic networking tools)
# * [Joe](https://joe-editor.sourceforge.io/) (editor)
# * [JQ](https://jqlang.github.io/jq/) (JSON editing tool)
# * [Less](https://github.com/gwsw/less) (Terminal pager)
# * [NMap](https://nmap.org/) (network testing tool)
# * [Manual page utilities](https://man7.org/linux/man-pages/man1/man.1.html) (manual page viewer)
# * [NetPerfMeter](https://www.nntb.no/~dreibh/netperfmeter/) (network performance metering tool)
# * [NetPlan](https://netplan.io/) (network configuration; on Linux systems only!)
# * [OpenSSL](https://openssl.org/) (Cryptography and TLS toolkit)
# * [Traceroute](https://linux.die.net/man/8/traceroute)
# * [PLocate](https://plocate.sesse.net/) ("locate" command for finding files)
# * [PwGen](https://opensource.com/article/21/7/generate-passwords-pwgen) (secure password generator)
# * [Python](https://www.python.org/) (Python 3 interpreter)
# * [RSPLIB](https://www.nntb.no/~dreibh/rserpool/) RSerPool Tools (RSerPool testing tools)
# * [RSync](https://rsync.samba.org/) Tools (file synchronisation)
# * [SubNetCalc](https://www.nntb.no/~dreibh/subnetcalc/) (address calculator)
# * [System-Tools](https://www.nntb.no/~dreibh/system-tools/) (system information on login)
# * [TCPDump](https://www.tcpdump.org/) (packet sniffer)
# * [Tree](https://linux.die.net/man/1/tree) (tree view of directory hierachy)
# * [TSCTP](https://www.nntb.no/~dreibh/tsctp/) (SCTP test tool)
# * [T-Shark](https://www.wireshark.org/) (packet sniffer, CLI-version for Wireshark)
# * [UUID](http://www.ossp.org/pkg/lib/uuid/) (UUID generator)
# * [Zip](https://infozip.sourceforge.net/Zip.html) (Zip compression tools)
# ###########################################################################


# ###### Print script name, to make Packer output easier readable ###########
if command -v figlet >/dev/null && command -v print-utf8 >/dev/null ; then
   echo
   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;34m█" "▀" "█\e[0m"
   figlet -w 156 "$(basename "$0")" | LC_ALL=C.UTF-8 print-utf8 -x 160 -n -C "\e[1;34m█\e[22m" "\e[1;34m█\e[0m"
   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;34m█" "▄" "█\e[0m"
else
   echo -e "\e[1;34;22m########## $(basename "$0") ##########\e[0m"
fi

# Enable printing the command-lines executed:
set -x


# ###### Main program #######################################################

# ====== Obtain system details ==============================================
UNAME="$(uname)"
NAME="${UNAME}"
ID="${UNAME,,}"
VERSION="$(uname -r)"
VERSION_ID="${VERSION/_*/}"
if [ -f /etc/os-release ] ; then
   . /etc/os-release
fi


# ###### Clone or update Git repository #####################################
# NOTE: System-Tools may not be installed, yet! No use of try-hard, etc.
clone-or-update ()
{
   local repository="$1"
   local url="$2"
   if [ ! -e "${repository}" ] ; then
      git clone "${url}" "${repository}"
   else
      pushd "${repository}" >/dev/null
      git fetch --all
      git pull
      popd >/dev/null
   fi
}


# ====== Package installation ===============================================

# ------ Ubuntu/Debian ------------------------------------------------------
if [ "${ID}" == "ubuntu" ] || [ "${ID}" == "debian" ] ; then

   if [ "${ID}" == "debian" ] ; then
      # ------ Add Debian FastTrack repository ------------------------------
      if [[ "${VERSION_ID}" =~ ^[0-9]+$ ]] ; then
         DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends fasttrack-archive-keyring
         if [ "${VERSION_ID}" -ge 13 ] ; then
            # On newer Debian versions, it is necessary to specify "signed-by";
            # the fasttrack-archive-keyring installs
            # /usr/share/keyrings/fasttrack-archive-keyring.gpg.
            cat >/etc/apt/sources.list.d/fasttrack.list <<EOF
deb [signed-by=/usr/share/keyrings/fasttrack-archive-keyring.gpg] http://fasttrack.debian.net/debian-fasttrack/ ${VERSION_CODENAME}-fasttrack main contrib
# deb-src [signed-by=/usr/share/keyrings/fasttrack-archive-keyring.gpg] http://fasttrack.debian.net/debian-fasttrack/ ${VERSION_CODENAME}-fasttrack main contrib
EOF
         else
            # Older Debian versions use the deprecated APT keyring, and
            # fasttrack-archive-keyring adds the key to the APT keyring:
            cat >/etc/apt/sources.list.d/fasttrack.list <<EOF
deb http://fasttrack.debian.net/debian-fasttrack/ ${VERSION_CODENAME}-fasttrack main contrib
# deb-src http://fasttrack.debian.net/debian-fasttrack/ ${VERSION_CODENAME}-fasttrack main contrib
EOF
         fi
         apt-get update
      fi
   fi

   packages=(
      acl
      apt-file
      binutils
      bridge-utils
      bwm-ng
      bzip2
      chrpath
      cloud-guest-utils
      curl
      dnsutils
      ethtool
      fail2ban
      gdisk
      gpm
      htop
      idn
      iproute2
      iptables
      iputils-ping
      joe
      jq
      less
      make
      man
      netperfmeter
      net-tools
      nmap
      openssl
      parallel
      pwgen
      python3
      rsplib-tools
      rsync
      subnetcalc
      tcpdump
      td-system-configure-grub
      td-system-tools-basic
      traceroute
      tree
      tsctp
      tshark
      unzip
      uuid
      wget
      zip
   )

   # ------ Ubuntu ----------------------------------------------------------
   if [ "${ID}" == "ubuntu" ] && [[ "${VERSION_ID}" =~ ^1[2345]\.[01][04]$ ]] || \
      [ "${ID}" == "debian" ] && [[ "${VERSION_ID}" =~ ^1[01]$ ]] ; then
      # Old Ubuntu versions 12.04/14.04 and Debian versions 10/11
      # do not have "hipercontracer"!
      echo "NOTE: HiPerConTracer is not available in this Ubuntu/Debian version!"
   else
      packages+=( "hipercontracer" )
   fi
   if [ "${ID}" == "ubuntu" ] && [[ "${VERSION_ID}" =~ ^1[234567]\.[01][04]$ ]] ; then
      # Old Ubuntu versions 12.04/14.04/16.04 do not have "netplan"!
      echo "NOTE: NetPlan is not available in this Ubuntu version!"
   else
      packages+=( "netplan.io" )
   fi
   if [ "${ID}" == "ubuntu" ] && [[ "${VERSION_ID}" =~ ^1[23456789]\.[01][04]$ ]] ; then
      # Old Ubuntu versions 12.04/14.04/16.04/18.04 do not have "systemd-timesyncd"!
      echo "NOTE: systemd-timesyncd is not available in this Ubuntu version!"
   else
      packages+=( "systemd-timesyncd" )
   fi
   if [ "${ID}" == "ubuntu" ] ; then
      if [[ "${VERSION_ID}" =~ ^1[2345]\.[01][04]$ ]] ; then
         echo "NOTE: delv is not available in this Ubuntu version!"
      elif [[ "${VERSION_ID}" =~ ^1[67]\.[01][04]$ ]] ; then
         # Old Ubuntu version 16.04 has "delv" is in the "bind9" package!
         packages+=( "bind9" )
      fi
   fi

   env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends "${packages[@]}"

   # ------ Locate ----------------------------------------------------------
   # PLocate is the successor of MLocate and findutils, all providing a "locate" command.
   # Try PLocate first, then MLocate, then findutils:
   env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends plocate || \
      env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends mlocate || \
         env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends findutils


# ------ Fedora -------------------------------------------------------------
elif [ "${ID}" == "fedora" ] ; then

   packages=(
      acl
      bind-utils
      bridge-utils
      bwm-ng
      bzip2
      chrpath
      cloud-utils-growpart
      cmake
      curl
      diff
      ethtool
      fail2ban
      gdisk
      gpm
      hipercontracer
      htop
      iproute
      iproute-tc
      iptables
      iputils
      joe
      jq
      libidn
      make
      man
      netperfmeter
      netplan
      net-tools
      nmap
      openssl
      parallel
      plocate
      pwgen
      python3
      rsplib-tools
      rsync
      strings
      subnetcalc
      tar
      tcpdump
      td-system-tools-basic
      td-system-tools-configure-grub
      traceroute
      tree
      tsctp
      unzip
      uuid
      wget
      wireshark-cli
      zip
   )

   dnf install --setopt=install_weak_deps=False -y "${packages[@]}"

   # Make initial NetPlan configuration:
   if [ ! -e /etc/netplan/netplan.yaml ] ; then
      interface="$(ip route show default | awk '{ for(i=1;i<=NF;i++) if($i=="dev") print $(i+1) }')"
      cat >/etc/netplan/netplan.yaml <<EOF
network:
  version: 2
  renderer: NetworkManager
  ethernets:
    ${interface}:
      dhcp4: true
      dhcp6: true
      accept-ra: true
EOF
      chmod 600 /etc/netplan/netplan.yaml
   fi

   # netplan-configure.service is not enabled by default:
   systemctl enable netplan-configure.service || true

   if [ -e /etc/selinux/config ] ; then
      # FIXME!
      # Fedora is buggy, preventing NetworkManager startup with NetPlan:
      # https://bugzilla.redhat.com/show_bug.cgi?id=2308655
      # Work-around is to turn SELinux into "permissive" mode:
      sed -e "s/^SELINUX=.*/SELINUX=permissive/" -i /etc/selinux/config
   fi


# ------ OpenSUSE -----------------------------------------------------------
elif [[ "${ID}" =~ ^opensuse- ]] ; then

   packages=(
      acl
      bind-utils
      binutils
      bridge-utils
      bwm-ng
      bzip2
      chrpath
      cmake
      curl
      diffutils
      ethtool
      fail2ban
      findutils
      gdisk
      gpm
      growpart
      hipercontracer
      htop
      iproute2
      iproute2-bash-completion
      iptables
      iputils
      joe
      jq
      libidn
      libidn-tools
      make
      man
      netperfmeter
      net-tools
      net-tools-deprecated
      nmap
      openssl
      gnu_parallel
      plocate
      pwgen
      python3
      rsplib-tools
      rsync
      subnetcalc
      tar
      tcpdump
      td-system-tools-basic
      td-system-tools-configure-grub
      traceroute
      tree
      tsctp
      unzip
      uuid
      wget
      wireshark
      zip
   )

   zypper --non-interactive install \
      --force-resolution --allow-vendor-change --allow-name-change \
      --no-recommends -y "${packages[@]}"


# ------ Alpine -------------------------------------------------------------
elif [ "${ID}" == "alpine" ] ; then

   packages=(
      acl
      bind-dnssec-tools
      binutils
      bridge-utils
      bwm-ng
      bzip2
      chrpath
      cloud-utils-growpart
      cmake
      curl
      docs
      ethtool
      fail2ban
      findutils-locate
      gptfdisk
      gpm
      hipercontracer
      htop
      iproute2
      iptables
      iputils
      joe
      jq
      libidn
      make
      man-pages
      netperfmeter
#       netplan
      net-tools
      nmap
      openssl
      ossp-uuid
      parallel
      pwgen
      python3
      rsplib-tools
      rsync
      subnetcalc
      tar
      tcpdump
      td-system-tools-basic
      td-system-tools-configure-grub
      traceroute
      tree
      tsctp
      tshark
      unzip
      wget
      zip
   )

   apk add "${packages[@]}"


# ------ FreeBSD ------------------------------------------------------------
elif [ "${ID}" == "freebsd" ] ; then

   packages=(
      base64
      bind-tools
      bwm-ng
      chrpath
      cmake
      curl
      flock
      gawk
      gdisk
      gmake
      hipercontracer
      htop
      joe
      jq
      libidn
      netperfmeter
      nmap
      openssl
      ossp-uuid
      parallel
      plocate
      pwgen
      py312-fail2ban
      python3
      rsplib
      rsync
      subnetcalc
      tcpdump
      td-system-tools
      tree
      tsctp
      wget
      wireshark-nox11
      zip
   )

   pkg install -y "${packages[@]}"


# ------ NetBSD -------------------------------------------------------------
elif [ "${ID}" == "netbsd" ] ; then

   packages=(
      base64
      bwm-ng
      chrpath
      cmake
      curl
      fail2ban
      gawk
      gmake
#      hipercontracer
      htop
      joe
      jq
      libidn
#      netperfmeter
      nmap
      openssl
      ossp-uuid
      parallel
      pwgen
      python314
#      rsplib
      rsync
#      subnetcalc
      tcpdump
#      td-system-tools
      tree
#      tsctp
      wireshark
      wget
      zip
   )

   pkgin -y install "${packages[@]}"

   # ------ Build missing programs from sources -----------------------------
   mkdir -p /root/src
   cd /root/src
   if ! command -v print-utf8 >/dev/null ; then
      pkgin -y install cmake pkgconf  figlet gettext mbuffer ossp-uuid pwgen
      clone-or-update system-tools https://dreibh@github.com/dreibh/system-tools
      ( cd /root/src/system-tools && ./autogen.sh -- -DWITH_CONFIGURE_GRUB=OFF -DWITH_GIMP_SCRIPTS=OFF -DWITH_GIMP_SCRIPTS_EXAMPLES=OFF && make install )
   fi
   if ! command -v subnetcalc >/dev/null ; then
      pkgin -y install cmake pkgconf  gettext libidn2 libiberty libmaxminddb
      clone-or-update subnetcalc https://dreibh@github.com/dreibh/subnetcalc
      ( cd /root/src/subnetcalc && ./autogen.sh && make install )
   fi
   if ! command -v netperfmeter >/dev/null ; then
      pkgin -y install cmake pkgconf
      clone-or-update netperfmeter https://dreibh@github.com/dreibh/netperfmeter
      ( cd /root/src/netperfmeter && ./autogen.sh -- -DWITH_ICONS=OFF && make install )
   fi
   if ! command -v hipercontracer >/dev/null ; then
      pkgin -y install cmake pkgconf  boost lzmalib zstd
      clone-or-update hipercontracer https://dreibh@github.com/dreibh/hipercontracer
      ( cd /root/src/hipercontracer && ./autogen.sh -- -DWITH_ICONS=OFF -DWITH_IMPORTER=OFF -DWITH_QUERY=OFF -DWITH_LIBHPCTDB=OFF -DWITH_LIBUNIVERSALIMPORTER=OFF && make install )
   fi
   if ! command -v tsctp >/dev/null ; then
      pkgin -y install cmake pkgconf
      clone-or-update tsctp https://dreibh@github.com/dreibh/tsctp
      ( cd /root/src/tsctp && ./autogen.sh && make install )
   fi
   if ! command -v rspterminal >/dev/null ; then
      pkgin -y install cmake pkgconf
      clone-or-update rsplib https://dreibh@github.com/dreibh/rsplib
      ( cd /root/src/rsplib && ./autogen.sh -- -DENABLE_ICONS=OFF -DENABLE_QT=OFF && make install )
   fi


# ------ OpenBSD ------------------------------------------------------------
elif [ "${ID}" == "openbsd" ] ; then

   packages=(
      base64
      bwm-ng
#       chrpath
      cmake
      curl
      gawk
      gmake
#       hipercontracer
      htop
      isc-bind--
      joe
      jq
      libidn
#       netperfmeter
      nmap
#       openssl
      ossp-uuid
      parallel
      pwgen
#       py312-fail2ban
      "python--%3"
#       rsplib
      rsync--
#       slocate
#       subnetcalc
#       tcpdump
#       td-system-tools
      tree
#       tsctp
      tshark
      unzip--
      wget
      zip
   )
   pkg_add -r -I "${packages[@]}"

   # ------ Build missing programs from sources -----------------------------
   mkdir -p /root/src
   cd /root/src
   if ! command -v print-utf8 >/dev/null ; then
      pkg_add -r -I cmake gnugetopt  buffer figlet gettext-runtime gettext-tools ossp-uuid pwgen
      clone-or-update system-tools https://dreibh@github.com/dreibh/system-tools
      ( cd /root/src/system-tools && ./autogen.sh -- -DWITH_CONFIGURE_GRUB=OFF -DWITH_GIMP_SCRIPTS=OFF -DWITH_GIMP_SCRIPTS_EXAMPLES=OFF && make install )
   fi
   if ! command -v subnetcalc >/dev/null ; then
      pkg_add -r -I cmake gnugetopt  gettext-runtime gettext-tools libidn2 libmaxminddb
      clone-or-update subnetcalc https://dreibh@github.com/dreibh/subnetcalc
      ( cd /root/src/subnetcalc && ./autogen.sh && make install )
   fi
   if ! command -v netperfmeter >/dev/null ; then
      pkg_add -r -I cmake gnugetopt
      clone-or-update netperfmeter https://dreibh@github.com/dreibh/netperfmeter
      ( cd /root/src/netperfmeter && ./autogen.sh -- -DWITH_ICONS=OFF && make install )
   fi
# FIXME!
#   if ! command -v hipercontracer >/dev/null ; then
#      pkg_add -r -I cmake gnugetopt  boost xz zstd
#      clone-or-update hipercontracer https://dreibh@github.com/dreibh/hipercontracer
#      ( cd /root/src/hipercontracer && ./autogen.sh -- -DWITH_ICONS=OFF -DWITH_IMPORTER=OFF -DWITH_QUERY=OFF -DWITH_LIBHPCTDB=OFF -DWITH_LIBUNIVERSALIMPORTER=OFF && make install )
#   fi


# ------ Solaris ------------------------------------------------------------
elif [ "${ID}" == "sunos" ] ; then

   packages=(
      bwm-ng
      pkg://openindiana.org/developer/build/cmake
      curl
      fail2ban
      gawk
      gptfdisk
#      hipercontracer
      htop
      joe
      jq
      libidn
#      netperfmeter
      nmap
      openssl
      parallel
      pwgen
      python-314
#      rsplib
#      subnetcalc
      tcpdump
#      td-system-tools
      tree
#      tsctp
      tshark
      wget
      zip
   )

   pkg install "${packages[@]}" || [ $? -eq 4 ]

   # ------ Build missing programs from sources -----------------------------
   mkdir -p /root/src
   cd /root/src
   if ! command -v bwm-ng >/dev/null ; then
      pkg install build/autoconf build/automake
      clone-or-update bwm-ng https://github.com/vgropp/bwm-ng
      ( cd bwm-ng && ./autogen.sh --prefix=/usr && make && make install )
   fi
   if ! command -v figlet >/dev/null ; then
      clone-or-update figlet https://github.com/cmatsuoka/figlet.git
      ( cd figlet && make CFLAGS="-Wall -DTLF_FONTS -include alloca.h" && make install )
   fi
   if ! command -v print-utf8 >/dev/null ; then
      pkg install build/cmake pkgconf  gnu-gettext mbuffer pwgen || [ $? -eq 4 ]
      clone-or-update system-tools https://dreibh@github.com/dreibh/system-tools
      ( cd /root/src/system-tools && ./autogen.sh -- -DWITH_CONFIGURE_GRUB=OFF -DWITH_GIMP_SCRIPTS=OFF -DWITH_GIMP_SCRIPTS_EXAMPLES=OFF && make install )
   fi
   if ! command -v subnetcalc >/dev/null ; then
      pkg install build/cmake pkgconf  gnu-gettext libidn2 || [ $? -eq 4 ]
      clone-or-update subnetcalc https://dreibh@github.com/dreibh/subnetcalc
      ( cd /root/src/subnetcalc && ./autogen.sh -- -DWITH_GEOIP=OFF && make install )
   fi
   if ! command -v netperfmeter >/dev/null ; then
      pkg install build/cmake pkgconf  compress/bzip2 || [ $? -eq 4 ]
      clone-or-update netperfmeter https://dreibh@github.com/dreibh/netperfmeter
      ( cd /root/src/netperfmeter && ./autogen.sh -- -DWITH_ICONS=OFF && make install )
   fi
   if ! command -v hipercontracer >/dev/null ; then
      pkg install build/cmake pkgconf  library/boost compress/bzip2 compress/xz compress/zstd || [ $? -eq 4 ]
      clone-or-update hipercontracer https://dreibh@github.com/dreibh/hipercontracer
      ( cd /root/src/hipercontracer && ./autogen.sh -- -DWITH_ICONS=OFF -DWITH_IMPORTER=OFF -DWITH_QUERY=OFF -DWITH_LIBHPCTDB=OFF -DWITH_LIBUNIVERSALIMPORTER=OFF && make install )
   fi
   if ! command -v tsctp >/dev/null ; then
      pkg install build/cmake pkgconf || [ $? -eq 4 ]
      clone-or-update tsctp https://dreibh@github.com/dreibh/tsctp
      ( cd /root/src/tsctp && ./autogen.sh && make install )
   fi
#   if ! command -v rspterminal >/dev/null ; then
#      pkg install build/cmake pkgconf || [ $? -eq 4 ]
#      clone-or-update rsplib https://dreibh@github.com/dreibh/rsplib
#      ( cd /root/src/rsplib && ./autogen.sh -- -DENABLE_ICONS=OFF -DENABLE_QT=OFF && make install )
#   fi


# ------ Unknown ------------------------------------------------------------
else

   echo >&2 "ERROR: Unknown ID ${ID} in /etc/os-release. The installation script may need an update for supporting this system!"
   exit 1

fi


# ====== Verify command availability ========================================

# ------ Prepare list of required commands ----------------------------------
programs=(
   Reset-Machine-ID
   System-Info
   System-Maintenance
   awk
   base64
   bwm-ng
   bzip2
   curl
   diff
   dig
   find
   htop
   idn
   ifconfig
   joe
   jq
   less
   locate
   man
   netperfmeter
   nmap
   openssl
   parallel
   ping
   print-utf8
   pwgen
   python3
   random-sleep
   rsync
   strings
   subnetcalc
   tar
   tcpdump
   text-block
   time2unixts
   traceroute
   tree
   try-hard
   tshark
   unixts2time
   unzip
   wget
   xargs
   zip
)

if [ "${ID}" == "ubuntu" ] && [[ "${VERSION_ID}" =~ ^1[2345]\.[01][04]$ ]] ; then
   true
else
   programs+=( delv )
fi

if [ "${ID}" == "openbsd" ] ; then
   true
elif [ "${ID}" == "sunos" ] ; then
   programs+=(
      getfacl
      setfacl
      tsctp
      uuidgen
   )
else
   programs+=(
      chrpath
      flock
      getfacl
      setfacl
      tsctp
      uuid
   )
fi

if [ "${ID}" != "netbsd" ] && [ "${ID}" != "openbsd" ] ; then
   programs+=( gdisk )
fi

if [ "${ID}" == "ubuntu" ] && [[ "${VERSION_ID}" =~ ^1[2345]\.[01][04]$ ]] || \
   [ "${ID}" == "debian" ] && [[ "${VERSION_ID}" =~ ^1[01]$ ]] ; then
   true   # No HiPerConTracer in old Ubuntu and Debian versions
elif [ "${ID}" == "openbsd" ] ; then
   true   # FIXME!
else
   programs+=( hipercontracer )
fi

if [ "$(uname)" == "Linux" ] ; then
   if [ "${ID}" == "ubuntu" ] && [[ "${VERSION_ID}" =~ ^1[234567]\.[01][04]$ ]] ; then
      true   # No netplan in old Ubuntu versions
   elif [[ "${ID}" =~ ^opensuse- ]] || [ "${ID}" == "alpine" ] ; then
      true   # No netplan in OpenSUSE and Alpine
   else
      programs+=( netplan )
   fi
   programs+=( brctl ethtool growpart ip iptables tc )
fi

if [ "${ID}" == "debian" ] && [[ ! "${VERSION_ID}" =~ ^1[01]$ ]] ; then
   true   # No rsplib in old Debian versions
elif [ "${ID}" == "openbsd" ] ; then
   true   # No rsplib in OpenBSD
elif [ "${ID}" == "sunos" ] ; then
   true   # FIXME! No rsplib in Solaris
else
   programs+=( rspserver rspterminal )
fi

if [ "${ID}" == "openbsd" ] ; then
   true   # No SCTP support in OpenBSD
else
   programs+=( tsctp )
fi


# ------ Verify command availability ----------------------------------------
set +x
echo "Verifying command availability:"
errors=0
missing=()
for command in "${programs[@]}" ; do
   if ! command -v "${command}" >/dev/null 2>&1 ; then
      errors=$((errors+1))
      missing+=( "${command}" )
   fi
done
if [ ${errors} -gt 0 ] ; then
   echo >&2 "ERROR: ${errors} commands are missing:"
   (
      for program in "${missing[@]}" ; do
         echo >&2 " * ${program}"
      done
   ) | sort
   exit 1
else
   echo "OK"
fi
set -x


# ====== Enable DNSSEC ======================================================
resolvedConf=""
if [ -e /etc/systemd/resolved.conf ] ; then
   resolvedConf="/etc/systemd/resolved.conf"
elif [ -e /usr/lib/systemd/resolved.conf ] ; then
   resolvedConf="/usr/lib/systemd/resolved.conf"
fi
if [ "${resolvedConf}" != "" ] ; then
   sed -e "s/^#DNSSEC=.*$/DNSSEC=yes/g" <${resolvedConf} >${resolvedConf}.new
   mv ${resolvedConf}.new ${resolvedConf}
   # FIXME: Not restarting the service yet, it will be active after reboot.
   # service systemd-resolved restart
fi
