#!/usr/bin/env bash
#
# Autoinstall Scripts
# Copyright (C) 2017-2024 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

# Bash options:
set -exu


# ====== Check/set environment variables ====================================
UNAME="$(uname)"


# ====== Configure System-Info ==============================================
if [ "${UNAME}" == "FreeBSD" ] ; then
   systemInfoDirectory="/usr/local/etc/system-info.d"

   # FIXME! This can be removed when the td-system-tools port got updated!
   pkg install -y figlet
else
   systemInfoDirectory="/etc/system-info.d"
fi

find /tmp/system-info -type f -print0 | xargs -r -0 -I "{}" chmod +x "{}"
find /tmp/system-info -type f -print0 | xargs -r -0 -I "{}" cp "{}" "${systemInfoDirectory}"
