#!/usr/bin/env bash
# ==========================================================================
#  ___         _        _ _      _   _            ___         _      _
# |_ _|_ _  __| |_ __ _| | |__ _| |_(_)___ _ _   / __| __ _ _(_)_ __| |_ ___
#  | || ' \(_-<  _/ _` | | / _` |  _| / _ \ ' \  \__ \/ _| '_| | '_ \  _(_-<
# |___|_||_/__/\__\__,_|_|_\__,_|\__|_\___/_||_| |___/\__|_| |_| .__/\__/__/
#                                                              |_|
#
#   --- Virtual Machine Image Builder and System Installation Scripts ---
#            https://www.nntb.no/~dreibh/vmimage-builder-scripts/
# ==========================================================================
#
# System Installation Scripts
# Copyright (C) 2017-2026 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

# Bash options:
set -euo pipefail


# ###### Print script name, to make Packer output easier readable ###########
if command -v figlet >/dev/null && command -v print-utf8 >/dev/null ; then
   echo
   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;34m█" "▀" "█\e[0m"
   figlet -w 156 "$(basename "$0")" | LC_ALL=C.UTF-8 print-utf8 -x 160 -n -C "\e[1;34m█\e[22m" "\e[1;34m█\e[0m"
   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;34m█" "▄" "█\e[0m"
else
   echo -e "\e[1;34;22m########## $(basename "$0") ##########\e[0m"
fi

# Enable printing the command-lines executed:
set -x


# ###### Main program #######################################################

# ====== Obtain system details ==============================================
UNAME="$(uname)"


# ====== Configure System-Info ==============================================
case "${UNAME}" in
   FreeBSD|OpenBSD)
      systemInfoDirectory="/usr/local/etc/system-info.d"
      ;;
   NetBSD)
      systemInfoDirectory="/usr/pkg/etc/system-info.d"
      ;;
   *)
      systemInfoDirectory="/etc/system-info.d"
      ;;
esac

# This directory is created by the configurations in ../files/$0
# Make sure that the corresponding configuration exists there!
INPUT_DIRECTORY="/tmp/installtmp/system-info"

if [ -d "${INPUT_DIRECTORY}" ] ; then
   mkdir -p "${systemInfoDirectory}"
   find "${INPUT_DIRECTORY}" -type f -exec chmod +x {} \;
   find "${INPUT_DIRECTORY}" -type f -exec cp {} "${systemInfoDirectory}/" \;
else
   echo >&2 "ERROR: ${INPUT_DIRECTORY} does not exist!"
   exit 1
fi

# ====== Set up /etc/profile ================================================
if [ "${UNAME}" == "NetBSD" ] || [ "${UNAME}" == "OpenBSD" ] ; then
   if [ ! -e /etc/profile ] ; then
      touch  /etc/profile
   fi
   if ! grep -q "Source profile.d directories" /etc/profile; then
      profileDirectories=(
         /etc/profile.d
         /usr/local/etc/profile.d
      )
      cat >>/etc/profile << EOF
# ====== Source profile.d directories =======================================
for dir in ${profileDirectories[@]} ; do
    if [ -d "\$dir" ]; then
        for script in "\$dir"/*.sh; do
            # The [ -r ... ] check ensures non-matching wildcards are not sourced:
            [ -r "\$script" ] && . "\$script"
        done
    fi
done
unset dir script
EOF
   fi
fi
