#!/usr/bin/env bash
#
# Autoinstall Scripts
# Copyright (C) 2017-2024 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

# Bash options:
set -ex


UNAME="$(uname)"


# ====== Configure GRUB bootloader ==========================================
if [ "${UNAME}" == "Linux" ] ; then

   # If the background image files are not at their location, try to move them
   # from tmp/. They should have been placed there by the file provisioner.
   if [ ! -e "${BOOTSPLASH}" ] ; then
      dir="$(dirname "${BOOTSPLASH}")"
      sudo mkdir -p "${dir}/"
      sudo mv "/tmp/$(basename "${BOOTSPLASH}")" "${dir}/"
   fi

   loader=""
   if [[ "${BOOTSPLASH}" =~ (\.[Jj][Pp][Ee][Gg]|\.[Jj][Pp][Ee][Gg])$ ]] ; then
      loader="jpeg"
   elif [[ "${BOOTSPLASH}" =~ (\.[Pp][Nn][Gg])$ ]] ; then
      loader="png"
   elif [[ "${BOOTSPLASH}" =~ (\.[Tt][Gg][Aa])$ ]] ; then
      loader="tga"
   else
      echo >&2 "ERROR: Unknown bootsplash image format of ${BOOTSPLASH}!"
      exit 1
   fi

   # Set the background image as bootsplash:
   if [ -e /usr/share/configure-grub/grub-defaults-nornet ] ; then
      sed -e "s%@SET_BOOTSPLASH_HERE@%${BOOTSPLASH}%g" \
          -e "s%@SET_LOADER_HERE@%${loader}%g" \
          </tmp/06_aaaaa_bootsplash.in >/etc/grub.d/06_aaaaa_bootsplash
      chmod +x /etc/grub.d/06_aaaaa_bootsplash
      configure-grub /usr/share/configure-grub/grub-defaults-nornet -o /etc/default/grub

      if [ -x /usr/sbin/grub2-mkconfig ] ; then
         /usr/sbin/grub2-mkconfig -o /boot/grub2/grub.cfg || true
      else
         update-grub || true
      fi
   fi

fi
