#!/usr/bin/env bash
# ==========================================================================
#  ___         _        _ _      _   _            ___         _      _
# |_ _|_ _  __| |_ __ _| | |__ _| |_(_)___ _ _   / __| __ _ _(_)_ __| |_ ___
#  | || ' \(_-<  _/ _` | | / _` |  _| / _ \ ' \  \__ \/ _| '_| | '_ \  _(_-<
# |___|_||_/__/\__\__,_|_|_\__,_|\__|_\___/_||_| |___/\__|_| |_| .__/\__/__/
#                                                              |_|
#
#   --- Virtual Machine Image Builder and System Installation Scripts ---
#            https://www.nntb.no/~dreibh/vmimage-builder-scripts/
# ==========================================================================
#
# System Installation Scripts
# Copyright (C) 2017-2026 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

# Bash options:
set -euo pipefail


# ###### Print script name, to make Packer output easier readable ###########
if command -v figlet >/dev/null && command -v print-utf8 >/dev/null ; then
   echo
   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;34m█" "▀" "█\e[0m"
   figlet -w 156 "$(basename "$0")" | LC_ALL=C.UTF-8 print-utf8 -x 160 -n -C "\e[1;34m█\e[22m" "\e[1;34m█\e[0m"
   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;34m█" "▄" "█\e[0m"
else
   echo -e "\e[1;34;22m########## $(basename "$0") ##########\e[0m"
fi

# Enable printing the command-lines executed:
set -x


# ###### Main program #######################################################

# ====== Check/set environment variables ====================================
if [ ! -v BOOTSPLASH ] || [ ! -v VIDEO ] ; then
   echo >&2 "Usage: env BOOTSPLASH=<bootsplash> VIDEO=<widthxheight> $0"
   echo >&2 "Example: sudo env BOOTSPLASH=/usr/share/bootsplash/Bjørnsund-3840x2160.jpeg VIDEO=1920x1080 $0"
   exit 1
fi

# ====== Obtain system details ==============================================
UNAME="$(uname)"


# ====== Configure GRUB bootloader ==========================================
if [ "${UNAME}" == "Linux" ] ; then

   # ------ Set GRUB bootsplash image ---------------------------------------
   if [ "${BOOTSPLASH}" != "" ] ; then
      # If the background image files are not at their location, try to move them
      # from tmp/. They should have been placed there by the file provisioner.
      if [ ! -e "${BOOTSPLASH}" ] ; then
         dir="$(dirname "${BOOTSPLASH}")"
         mkdir -p "${dir}/"
         tmpBootsplashFile="/tmp/bootsplash-images/$(basename "${BOOTSPLASH}")"
         if [ -e "${tmpBootsplashFile}" ] ; then
            mv "${tmpBootsplashFile}" "${dir}/"
         else
            echo >&2 "ERROR: Bootsplash file ${BOOTSPLASH} not found locally or in /tmp/bootsplash-images!"
            exit 1
         fi
      fi

      loader=""
      if [[ "${BOOTSPLASH}" =~ (\.[Jj][Pp][Ee][Gg]|\.[Jj][Pp][Gg])$ ]] ; then
         loader="jpeg"
      elif [[ "${BOOTSPLASH}" =~ (\.[Pp][Nn][Gg])$ ]] ; then
         loader="png"
      elif [[ "${BOOTSPLASH}" =~ (\.[Tt][Gg][Aa])$ ]] ; then
         loader="tga"
      else
         echo >&2 "ERROR: Unknown bootsplash image format of ${BOOTSPLASH}!"
         exit 1
      fi
      if [ -d /etc/grub.d ] && [ -e /etc/default/grub ] ;  then
         templateFile="/tmp/configuration-files/06_aaaaa_bootsplash.in"
         if [ -e "${templateFile}" ] ; then
            sed -e "s%@SET_BOOTSPLASH_HERE@%${BOOTSPLASH}%g" \
                -e "s%@SET_LOADER_HERE@%${loader}%g" \
                <"${templateFile}" >/etc/grub.d/06_aaaaa_bootsplash
            chmod +x /etc/grub.d/06_aaaaa_bootsplash
         else
            echo >&2 "ERROR: Bootsplash configuration template ${templateFile} is missing!"
            exit 1
         fi
      fi
   fi

   # ------ Update GRUB configuration ---------------------------------------
   if [ -e /etc/default/grub ] ; then
      if [ -e /usr/share/configure-grub/grub-defaults-nornet ] ; then
         configure-grub /usr/share/configure-grub/grub-defaults-nornet \
            -V "auto,${VIDEO},1024x768" \
            -o /etc/default/grub
      fi
      if command -v grub2-mkconfig 2>/dev/null ; then
         grub2-mkconfig -o /boot/grub2/grub.cfg || true
      else
         update-grub || true
      fi
   fi

fi
