#!/usr/bin/env bash
#
# Autoinstall Scripts
# Copyright (C) 2017-2024 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

# Bash options:
set -exu


# ====== Check/set environment variables ====================================
if [ ! -e /etc/os-release ] ; then
   echo >&2 "ERROR: /etc/os-release does not exist!"
   exit 1
fi
. /etc/os-release


# ====== Package installation ===============================================

# ------ Ubuntu/Debian ------------------------------------------------------
if [ "${ID}" == "ubuntu" ] || [ "${ID}" == "debian" ] ; then

   # ------ Add Zabbix Official Repository ----------------------------------
   cat >/etc/apt/sources.list.d/zabbix.list <<EOF
deb https://repo.zabbix.com/zabbix/7.0/${ID} ${VERSION_CODENAME} main
# deb-src https://repo.zabbix.com/zabbix/7.0/${ID} ${VERSION_CODENAME} main
EOF
   rm -f /etc/apt/trusted.gpg.d/zabbix-official-repo.gpg
   curl -fsSL https://repo.zabbix.com/zabbix-official-repo.key | \
      sudo gpg --batch --dearmor -o /etc/apt/trusted.gpg.d/zabbix-official-repo.gpg
   /usr/bin/apt-get update

   # ------ Install ---------------------------------------------------------
   packages="zabbix-agent"

   # shellcheck disable=SC2086
   env DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get install -y --no-install-recommends ${packages}

# ------ Fedora -------------------------------------------------------------
elif [ "${ID}" == "fedora" ] ; then

   packages="zabbix-agent"

   # shellcheck disable=SC2086
   /usr/bin/dnf install -y ${packages}

# ------ FreeBSD ------------------------------------------------------------
elif [ "${ID}" == "freebsd" ] ; then

   packages="zabbix7-agent"
   # shellcheck disable=SC2086
   /usr/sbin/pkg install -y ${packages}

# ------ Unknown ------------------------------------------------------------
else

   echo >&2 "ERROR: Unknown ID ${ID} in /etc/os-release. The installation script may need an update for supporting this system!"
   exit 1

fi
