#!/usr/bin/env bash
# ==========================================================================
#  ___         _        _ _      _   _            ___         _      _
# |_ _|_ _  __| |_ __ _| | |__ _| |_(_)___ _ _   / __| __ _ _(_)_ __| |_ ___
#  | || ' \(_-<  _/ _` | | / _` |  _| / _ \ ' \  \__ \/ _| '_| | '_ \  _(_-<
# |___|_||_/__/\__\__,_|_|_\__,_|\__|_\___/_||_| |___/\__|_| |_| .__/\__/__/
#                                                              |_|
#
#   --- Virtual Machine Image Builder and System Installation Scripts ---
#            https://www.nntb.no/~dreibh/vmimage-builder-scripts/
# ==========================================================================
#
# System Installation Scripts
# Copyright (C) 2017-2026 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

# Bash options:
set -euo pipefail


# ###### Print script name, to make Packer output easier readable ###########
if command -v figlet >/dev/null && command -v print-utf8 >/dev/null ; then
   echo
   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;34m█" "▀" "█\e[0m"
   figlet -w 156 "$(basename "$0")" | LC_ALL=C.UTF-8 print-utf8 -x 160 -n -C "\e[1;34m█\e[22m" "\e[1;34m█\e[0m"
   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;34m█" "▄" "█\e[0m"
else
   echo -e "\e[1;34;22m########## $(basename "$0") ##########\e[0m"
fi

# Enable printing the command-lines executed:
set -x


# ###### Main program #######################################################

# ====== Obtain system details ==============================================
UNAME="$(uname)"
NAME="${UNAME}"
ID="${UNAME,,}"
VERSION="$(uname -r)"
VERSION_ID="${VERSION/_*/}"
if [ -f /etc/os-release ] ; then
   . /etc/os-release
fi


# ====== Package installation ===============================================

# ------ Ubuntu/Debian ------------------------------------------------------
if [ "${ID}" == "ubuntu" ] || [ "${ID}" == "debian" ] ; then

   # ------ Add Zabbix Official Repository ----------------------------------
   zabbixVersion="7.4"
   cat >/etc/apt/sources.list.d/zabbix.list <<EOF
deb https://repo.zabbix.com/zabbix/${zabbixVersion}/stable/${ID} ${VERSION_CODENAME} main
# deb-src https://repo.zabbix.com/zabbix/${zabbixVersion}/stable/${ID} ${VERSION_CODENAME} main
EOF
   cat >/etc/apt/sources.list.d/zabbix-release.list <<EOF
deb https://repo.zabbix.com/zabbix/${zabbixVersion}/release/${ID} ${VERSION_CODENAME} main
# deb-src https://repo.zabbix.com/zabbix/${zabbixVersion}/release/${ID} ${VERSION_CODENAME} main
EOF
   cat >/etc/apt/sources.list.d/zabbix-tools.list <<EOF
deb https://repo.zabbix.com/zabbix-tools/debian-ubuntu ${VERSION_CODENAME} main
deb-src https://repo.zabbix.com/zabbix-tools/debian-ubuntu ${VERSION_CODENAME} main
EOF
#    cat >/etc/apt/sources.list.d/zabbix-release.list <<EOF
# # deb https://repo.zabbix.com/zabbix/${zabbixVersion}/unstable/${ID} ${VERSION_CODENAME} main
# # deb-src https://repo.zabbix.com/zabbix/${zabbixVersion}/unstable/${ID} ${VERSION_CODENAME} main
# EOF
   mkdir -p /etc/apt/trusted.gpg.d
   rm -f /etc/apt/trusted.gpg.d/zabbix-official-repo.gpg
   curl -fsSL https://repo.zabbix.com/zabbix-official-repo.key | \
      gpg --batch --dearmor -o /etc/apt/trusted.gpg.d/zabbix-official-repo.gpg
   apt-get update

   # ------ Install ---------------------------------------------------------
   packages=( "zabbix-agent" )
   env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends "${packages[@]}"

   systemctl enable zabbix-agent || true
   systemctl start  zabbix-agent || true

# ------ Fedora -------------------------------------------------------------
elif [ "${ID}" == "fedora" ] ; then

   packages=( "zabbix-agent" )
   dnf install --setopt=install_weak_deps=False -y "${packages[@]}"

   systemctl enable zabbix-agent || true
   systemctl start  zabbix-agent || true

# ------ FreeBSD ------------------------------------------------------------
elif [ "${ID}" == "freebsd" ] ; then

   packages=( "zabbix74-agent" )
   pkg install -y "${packages[@]}"

   sysrc zabbix_agentd_enable="YES"
   service zabbix_agentd start || true

# ------ NetBSD -------------------------------------------------------------
elif [ "${ID}" == "netbsd" ] ; then

   packages=( "zabbix-agent" )
   pkgin -y install "${packages[@]}"

# ------ OpenBSD ------------------------------------------------------------
elif [ "${ID}" == "openbsd" ] ; then

   packages=( "zabbix-agent" )
   pkg_add -r -I "${packages[@]}"

# ------ Unknown ------------------------------------------------------------
else

   echo >&2 "ERROR: Unknown ID ${ID} in /etc/os-release. The installation script may need an update for supporting this system!"
   exit 1

fi
