#!/usr/bin/env bash
# ==========================================================================
#  ___         _        _ _      _   _            ___         _      _
# |_ _|_ _  __| |_ __ _| | |__ _| |_(_)___ _ _   / __| __ _ _(_)_ __| |_ ___
#  | || ' \(_-<  _/ _` | | / _` |  _| / _ \ ' \  \__ \/ _| '_| | '_ \  _(_-<
# |___|_||_/__/\__\__,_|_|_\__,_|\__|_\___/_||_| |___/\__|_| |_| .__/\__/__/
#                                                              |_|
#
#   --- Virtual Machine Image Builder and System Installation Scripts ---
#            https://www.nntb.no/~dreibh/vmimage-builder-scripts/
# ==========================================================================
#
# System Installation Scripts
# Copyright (C) 2017-2026 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

# Bash options:
set -euo pipefail


# ###########################################################################
# The "KDE" installation is based on the [Basic](#basic) installation.
#
# It must contain the following packages:
# * The [KDE Plasma Desktop](https://kde.org/plasma-desktop/) with Oxygen theme and [SDDM](https://github.com/sddm/sddm)
# * [DejaVu Fonts](https://dejavu-fonts.github.io/) (DejaVu fonts)
# * [Dia](https://wiki.gnome.org/Apps/Dia) (drawing tool)
# * [Firefox](https://www.mozilla.org/en-US/firefox/new/) (web browser)
# * [FractGen](https://www.nntb.no/~dreibh/fractalgenerator/) (fractal generator)
# * [LibreOffice](https://www.libreoffice.org/) (office suite)
# * [Gimp](https://www.gimp.org/) (graphics editing tool)
# * [Inkscape](https://inkscape.org/) (drawing tool)
# * [Kate](https://kate-editor.org/) (editor)
# * [Kile](https://kile.sourceforge.io/) (LaTeX editor)
# * [Konsole](https://konsole.kde.org/) (console)
# * [Noto Fonts](https://fonts.google.com/noto) (Noto fonts, complete UTF-8 character range)
# * [Okteta](https://apps.kde.org/okteta/) (Hex editor)
# * [Okular](https://okular.kde.org/) (file viewer, e.g. for PDF)
# * [Open Sans Fonts](https://fonts.google.com/specimen/Open+Sans) (Open Sans fonts)
# * [R](https://www.r-project.org/) (statistical computing suite)
# * [Strawberry Music Player](https://www.strawberrymusicplayer.org/) (audio player)
# * [Wireshark](https://www.wireshark.org/) (packet sniffer, GUI version)
#
# Further properties:
# * Configured KDE and SDDM login manager
# * Configured 4 virtual desktops
# * Configured switchable keyboard layouts
# * Configured Konsole keyboard shortcuts
# * Configured Firefox (hardened settings, enhanced privacy settings, as well as some add-ons like NoScript, uBlock Origin, etc.)
# * Configured Wireshark (predefined filters, coloring rules, etc.)
# * Ubuntu 22.04+: Firefox is installed from PPA mozillateam/ppa (<https://launchpad.net/~mozillateam/+archive/ubuntu/ppa/+packages>), instead of using the Snap package.
# ###########################################################################


# ###### Main program #######################################################

# ====== Print script name, to make Packer output easier readable ===========
SCRIPT="20-kde"   # Set to "$(basename "$0")" of this file!
if command -v figlet >/dev/null && command -v print-utf8 >/dev/null ; then
   echo
   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;31m█" "▀" "█\e[0m"
   figlet -w 156 "${SCRIPT}" | LC_ALL=C.UTF-8 print-utf8 -x 160 -n -C "\e[1;31m█\e[22m" "\e[1;31m█\e[0m"
   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;31m█" "▄" "█\e[0m"
else
   echo -e "\e[1;31;22m########## ${SCRIPT} ##########\e[0m"
fi

# Enable printing the command-lines executed:
set -x

# ====== Obtain system details ==============================================
UNAME="$(uname)"
NAME="${UNAME}"
ID="${UNAME,,}"
VERSION="$(uname -r)"
VERSION_ID="${VERSION/_*/}"
if [ -f /etc/os-release ] ; then
   . /etc/os-release
fi


# ====== Package installation ===============================================

# ------ Ubuntu/Debian ------------------------------------------------------
if [ "${ID}" == "ubuntu" ] || [ "${ID}" == "debian" ] ; then

   packages=(
      dia
      fonts-dejavu
      fonts-noto
      fonts-open-sans
      fractgen
      kde-plasma-desktop
      gimp
      gstreamer1.0-libav
      inkscape
      kate
      kile
      konsole
      libreoffice
      okteta
      okular
      oxygen-icon-theme
      plasma-theme-oxygen
      sddm
      sddm-theme-breeze
      wireshark
   )

   # ------ Add Firefox package ---------------------------------------------
   if [ "${ID}" == "debian" ] ; then
      # Debian: firefox-esr instead of firefox!
      packages+=( firefox-esr )
   else
      packages+=( firefox )
   fi

   # ------ Ubuntu: Get Firefox from PPA, not via Snap ----------------------
   if [ "${ID}" == "ubuntu" ] ; then
      # shellcheck disable=SC2072,SC2071
      if [[ "${VERSION_ID}" > "21.10" ]] ; then
         cat >/etc/apt/preferences.d/firefox.pref <<EOF
# Use Firefox from PPA, instead of installing it via Snap!
Package: firefox
Pin: release o=LP-PPA-mozillateam
Pin-Priority: 1024
EOF
         add-apt-repository -sy ppa:mozillateam/ppa
      fi
   fi

   # NOTE: Try IPv4-only, if there is a problem. This seems to be necessary for Ubuntu 18.04.
   env DEBIAN_FRONTEND=noninteractive apt-get install -y "${packages[@]}" || \
      env DEBIAN_FRONTEND=noninteractive apt-get install -o Acquire::ForceIPv4=true -y "${packages[@]}"

   # Oxygen style for Qt6 or Qt5:
   env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends kde-style-oxygen-qt6 || \
      env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends kde-style-oxygen-qt5

   # Only newer system versions have Strawberry, install Clementine instead:
   env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends strawberry ||
      env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends clementine

   # FIXME: Ubuntu 20.04 triggers GNOME Desktop as "recommends".
   #        Fix should be to use --no-install-recommends!
   # Work-around: disable GDM, to get SDDM working:
   env DEBIAN_FRONTEND=noninteractive apt-get autoremove -y gdm3 || true


# ------ Fedora -------------------------------------------------------------
elif [ "${ID}" == "fedora" ] ; then

   packages=(
      dejavu-fonts-all
      dia
      firefox
      fractgen
      gimp
      inkscape
      kate
      @kde-desktop-environment
      kile
      konsole
      libreoffice
      google-noto-fonts-all
      okteta
      okular
      open-sans-fonts
      oxygen-fonts
      oxygen-icon-theme
      plasma-oxygen
      plasma-workspace-x11
      qt6-qtimageformats
      strawberry
      wireshark
   )

   dnf install --setopt=install_weak_deps=False -y --allowerasing "${packages[@]}"
   dnf remove -y elisa-player

   systemctl set-default graphical.target
   systemctl disable plasma-setup.service


# ------ OpenSUSE -----------------------------------------------------------
elif [[ "${ID}" =~ ^opensuse- ]] ; then

   packages=(
      dejavu-fonts
      dia
      firefox
      fractgen
      gimp
      gstreamer-plugins-good
      inkscape
      kate
      patterns-kde-kde_plasma
      kile
      konsole
      libreoffice
      google-noto-fonts
      google-noto-coloremoji-fonts
      google-noto-sans-cjk-fonts
      google-noto-sans-hk-fonts
      google-noto-sans-hk-mono-fonts
      google-noto-sans-jp-fonts
      google-noto-sans-jp-mono-fonts
      google-noto-sans-kr-fonts
      google-noto-sans-kr-mono-fonts
      google-noto-sans-sc-mono-fonts
      google-noto-sans-tc-fonts
      google-noto-sans-tc-mono-fonts
      google-noto-serif-hk-fonts
      google-noto-serif-jp-fonts
      google-noto-serif-kr-fonts
      google-noto-serif-tc-fonts
      okteta
      okular
      google-opensans-fonts
      kde-oxygen-fonts
      kf6-oxygen-icons
      oxygen6
      plasma6-desktop
      plasma6-session-x11
      qt6-imageformats
      sddm-qt6
      strawberry
      wireshark
   )

   zypper --non-interactive install \
      --force-resolution --allow-vendor-change --allow-name-change --replacefiles \
      --no-recommends -y "${packages[@]}"

   systemctl set-default graphical.target


# ------ Alpine -------------------------------------------------------------
elif [ "${ID}" == "alpine" ] ; then

   packages=(
      font-dejavu
      firefox
#      fractgen
      gimp
      inkscape
      kate
      plasma-desktop-meta
#      kile
      konsole
      libreoffice
      font-noto-all
      okteta
      okular
      font-opensans
      oxygen
      plasma-workspace
      qt6-qtimageformats
      strawberry
      wireshark

      mesa-dri-gallium mesa-va-gallium
      xf86-video-qxl xf86-video-vmware xf86-video-vesa
   )

   apk add "${packages[@]}"

   setup-devd udev
   rc-update add udev sysinit
   rc-service udev start

   rc-update add elogind default
   rc-service elogind start

   rc-update add sddm default

#    adduser <your-username> audio
#    adduser <your-username> video
#    adduser <your-username> input


# ------ FreeBSD ------------------------------------------------------------
elif [ "${ID}" == "freebsd" ] ; then

   packages=(
      dejavu
      dia
      firefox-esr
      fractgen
      gimp3-app
      inkscape
      kate
      kile
      konsole
      gstreamer1-plugins-soup
      libreoffice
      noto
      opensans-ttf
      okteta
      oxygen-fonts
      plasma6-plasma
      plasma6-oxygen
      plasma6-sddm-kcm
      R
      sddm
      strawberry

      wireshark
      xf86-video-vmware
      xorg
   )

   pkg install -y "${packages[@]}"

   sysrc dbus_enable="YES" ; service dbus start || true
   sysrc sddm_enable="YES" ; service sddm start || true


# ------ NetBSD -------------------------------------------------------------
elif [ "${ID}" == "netbsd" ] ; then

   false   # TBD! Not working, yet!

   packages=(
      dejavu-ttf
      dia
      firefox
#       fractgen
      gimp
      inkscape
      kate
      kile
      konsole
      libreoffice
      noto-ttf
      okteta
      okular
      plasma6-workspace
      plasma6-oxygen
      R
      sddm
      strawberry
      wireshark

      xterm   # FIXME!
   )

   pkgin -y install "${packages[@]}"

   cp /usr/pkg/share/examples/rc.d/dbus /etc/rc.d/
   cp /usr/pkg/share/examples/rc.d/sddm /etc/rc.d/
   echo "dbus=YES" >> /etc/rc.conf
   echo "sddm=YES" >> /etc/rc.conf

   cp /usr/pkg/share/examples/pam.d/sddm* /etc/pam.d/


# ------ OpenBSD ------------------------------------------------------------
elif [ "${ID}" == "openbsd" ] ; then

   false   # TBD! Not working, yet!

   packages=(
      dejavu
      dia
      firefox
#       fractgen
      gimp
      inkscape
      kate
      kde
      kde-plasma
      kile
      konsole
      libreoffice
      noto-fonts
      okteta
      okular
      open-sans-ttf
      R
      sddm
      strawberry
      wireshark
   )

   pkg_add -r -I "${packages[@]}"

   rcctl enable messagebus || true
   rcctl enable sddm || true

# ------ Solaris ------------------------------------------------------------
elif [ "${ID}" == "sunos" ] ; then

   false   # TBD! Not working, yet!

   packages=(
      desktop/kde
      desktop/sddm
      desktop/kate
      desktop/konsole
      desktop/libreoffice
      desktop/okteta
      desktop/okular
      diagnostic/wireshark
      graphics/dia
      image/editor/gimp
      image/inkscape
      math/r
      system/font/truetype/dejavu
      system/font/truetype/open-sans
      web/browser/firefox
   )

   pkg install --accept "${packages[@]}" || [ $? -eq 4 ]

   svcadm enable -r application/graphical-login/sddm


# ------ Unknown ------------------------------------------------------------
else

   echo >&2 "ERROR: Unknown ID ${ID} in /etc/os-release. The installation script may need an update for supporting this system!"
   exit 1

fi
