#!/usr/bin/env bash
#
# Autoinstall Scripts
# Copyright (C) 2017-2024 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

# Bash options:
set -exu


# ###########################################################################
# The "KDE" installation is based on the "Basic" installation.
#
# It must contain the following packages:
# * The [KDE Plasma Desktop](https://kde.org/plasma-desktop/) with Oxygen theme and [SDDM](https://github.com/sddm/sddm)
# * [Dia](https://wiki.gnome.org/Apps/Dia) (drawing tool)
# * [Firefox](https://www.mozilla.org/en-US/firefox/new/) (web browser)
# * [FractGen](https://www.nntb.no/~dreibh/fractalgenerator/) (fractal generator)
# * [LibreOffice](https://www.libreoffice.org/) (office suite)
# * [Gimp](https://www.gimp.org/) (graphics editing tool)
# * [Inkscape](https://inkscape.org/) (drawing tool)
# * [Kate](https://kate-editor.org/) (editor)
# * [Kile](https://kile.sourceforge.io/) (LaTeX editor)
# * [Konsole](https://konsole.kde.org/) (console)
# * [Noto Fonts](https://fonts.google.com/noto) (Noto fonts, complete UTF-8 character range)
# * [Okular](https://okular.kde.org/) (file viewer, e.g. for PDF)
# * [R](https://www.r-project.org/) (statistical computing suite)
# * [Strawberry Music Player](https://www.strawberrymusicplayer.org/) (audio player)
# * [Wireshark](https://www.wireshark.org/) (packet sniffer, GUI version)
#
# Further properties:
# * Configured KDE and SDDM login manager
# * Configured 4 virtual desktops
# * Configured switchable keyboard layouts
# * Configured Konsole keyboard shortcuts
# * Configured Firefox (hardened settings, enhanced privacy settings, as well as some add-ons like NoScript, uBlock Origin, etc.)
# * Configured Wireshark (predefined filters, coloring rules, etc.)
# * Ubuntu 22.04+: Firefox is installed from PPA mozillateam/ppa (<https://launchpad.net/~mozillateam/+archive/ubuntu/ppa/+packages>), instead of using the Snap package.
# ###########################################################################


# ====== Check/set environment variables ====================================
if [ ! -e /etc/os-release ] ; then
   echo >&2 "ERROR: /etc/os-release does not exist!"
   exit 1
fi
. /etc/os-release


# ====== Package installation ===============================================

# ------ Ubuntu/Debian ------------------------------------------------------
if [ "${ID}" == "ubuntu" ] || [ "${ID}" == "debian" ] ; then

   packages="
      dia
      fractgen
      kde-plasma-desktop
      kde-style-oxygen-qt5
      gimp
      gstreamer1.0-libav
      inkscape
      kate
      kile
      konsole
      libreoffice
      okular
      oxygen-icon-theme
      plasma-theme-oxygen
      sddm
      sddm-theme-breeze
      strawberry
      wireshark
   "

   # ------ Distribution-specific KDE meta package --------------------------
   # if [ "${ID}" == "debian" ] ; then
   #    # See also: https://wiki.debian.org/KDE
   #    packages="${packages} kde-standard"
   # else
   #    packages="${packages} kubuntu-desktop"
   # fi

   # ------ Add Firefox package ---------------------------------------------
   if [ "${ID}" == "debian" ] ; then
      # Debian: firefox-esr instead of firefox!
      packages="${packages} firefox-esr"
   else
      packages="${packages} firefox"
   fi

   # ------ Ubuntu: Get Firefox from PPA, not via Snap ----------------------
   if [ "${ID}" == "ubuntu" ] ; then
      # shellcheck disable=SC2072,SC2071
      if [[ "${VERSION_ID}" > "21.10" ]] ; then
         cat >/etc/apt/preferences.d/firefox.pref <<EOF
# Use Firefox from PPA, instead of installing it via Snap!
Package: firefox
Pin: release o=LP-PPA-mozillateam
Pin-Priority: 1024
EOF
         sudo add-apt-repository -sy ppa:mozillateam/ppa
      fi
   fi

   # shellcheck disable=SC2086
   env DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get install -y ${packages}

   # FIXME: Ubuntu 20.04 triggers GNOME Desktop as "recommends".
   #        Fix should be to use --no-install-recommends!
   # Work-around: disable GDM, to get SDDM working:
   env DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get autoremove -y gdm3 || true


# ------ Fedora -------------------------------------------------------------
elif [ "${ID}" == "fedora" ] ; then

   packages="
      dia
      firefox
      fractgen
      gimp
      inkscape
      kate
      @KDE
      kile
      konsole
      libreoffice
      okular
      oxygen-fonts
      oxygen-icon-theme
      plasma-oxygen
      qt5-style-oxygen
      strawberry
      wireshark
   "

   # shellcheck disable=SC2086
   /usr/bin/dnf install -y --allowerasing ${packages}

   # FIXME!
   # 2024/03: Wayland is still completely unusable in VirtualBox!
   # SDDM on Wayland just produces a black screen -> use X11 instead!
   /usr/bin/dnf install -y --allowerasing sddm-x11

   systemctl enable sddm.service
   systemctl start sddm.service
   systemctl set-default graphical.target


# ------ FreeBSD ------------------------------------------------------------
elif [ "${ID}" == "freebsd" ] ; then

   packages="
      dia
      firefox-esr
      fractgen
      gimp
      inkscape
      kde5
      kile
      libreoffice
      noto
      oxygen-fonts
      plasma5-oxygen
      plasma5-sddm-kcm
      R
      sddm
      strawberry
      wireshark
      xf86-video-vmware
      xorg
   "

   # shellcheck disable=SC2086
   /usr/sbin/pkg install -y ${packages}

   sysrc dbus_enable="YES" ; service dbus start || true
   sysrc sddm_enable="YES" ; service sddm start || true


   # ------ Unknown ------------------------------------------------------------
else

   echo >&2 "ERROR: Unknown ID ${ID} in /etc/os-release. The installation script may need an update for supporting this system!"
   exit 1

fi
