#!/usr/bin/env bash
# ==========================================================================
#  ___         _        _ _      _   _            ___         _      _
# |_ _|_ _  __| |_ __ _| | |__ _| |_(_)___ _ _   / __| __ _ _(_)_ __| |_ ___
#  | || ' \(_-<  _/ _` | | / _` |  _| / _ \ ' \  \__ \/ _| '_| | '_ \  _(_-<
# |___|_||_/__/\__\__,_|_|_\__,_|\__|_\___/_||_| |___/\__|_| |_| .__/\__/__/
#                                                              |_|
#
#   --- Virtual Machine Image Builder and System Installation Scripts ---
#            https://www.nntb.no/~dreibh/vmimage-builder-scripts/
# ==========================================================================
#
# System Installation Scripts
# Copyright (C) 2017-2026 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

# Bash options:
set -euo pipefail


# NOTE:
# Non-root user permission will be given in 38-allow-wireshark-as-user, not here!


# ###### Main program #######################################################

# ====== Print script name, to make Packer output easier readable ===========
SCRIPT="22-configure-wireshark"   # Set to "$(basename "$0")" of this file!
if command -v figlet >/dev/null && command -v print-utf8 >/dev/null ; then
   echo
   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;31m█" "▀" "█\e[0m"
   figlet -w 156 "${SCRIPT}" | LC_ALL=C.UTF-8 print-utf8 -x 160 -n -C "\e[1;31m█\e[22m" "\e[1;31m█\e[0m"
   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;31m█" "▄" "█\e[0m"
else
   echo -e "\e[1;31;22m########## ${SCRIPT} ##########\e[0m"
fi

# ====== Check environment variables ========================================
if [ ! -v USER_NAME ] || [ "${USER_NAME}" == "" ] ; then
   echo >&2 "Usage: env USER_NAME=<user> $0"
   echo >&2 "Example: sudo env USER_NAME=nornetpp $0"
   exit 1
fi

# Enable printing the command-lines executed:
set -x

USER_GROUP="$(id -gn "${USER_NAME}")"
USER_HOME="$(getent passwd "${USER_NAME}" | cut -d: -f6 || awk -F: -v user="${USER_NAME}" '$1==user { print $6 }' /etc/passwd)"
UNAME="$(uname)"


# ====== Wireshark filter rules =============================================
if [ -d /tmp/installtmp/wireshark ] ; then
   skelDirectory="/etc/skel"
   if [ "${UNAME}" == "FreeBSD" ] ; then
      skelDirectory="/usr/share/skel"
   fi

   mkdir -p /root/.config/wireshark
   mkdir -p "${USER_HOME}/.config/wireshark"
   mkdir -p "${skelDirectory}/.config/wireshark"

   for configurationFile in colorfilters decode_as_entries dfilters preferences ; do
      sourceConfigurationFile="/tmp/installtmp/wireshark/${configurationFile}"
      if [ -e "${sourceConfigurationFile}" ] ; then
         cp "${sourceConfigurationFile}" /root/.config/wireshark/
         cp "${sourceConfigurationFile}" "${USER_HOME}/.config/wireshark/"
         cp "${sourceConfigurationFile}" "${skelDirectory}/.config/wireshark/"
      else
         echo >&2 "WARNING: Source Wireshark configuration file ${sourceConfigurationFile} is missing!"
      fi
   done
   chown -R "${USER_NAME}":"${USER_GROUP}" "${USER_HOME}/.config/wireshark"
else
   echo >&2 "ERROR: Source directory /tmp/installtmp/wireshark does not exist!"
   exit 1
fi
