#!/usr/bin/env bash
#
# Autoinstall Scripts
# Copyright (C) 2017-2025 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

# Bash options:
set -exu


# NOTE:
# Non-root user permission will be given in 31-allow-wireshark-as-user, not here!


# ====== Check environment variables ========================================
if [ ! -v USER_NAME ] || [ "${USER_NAME}" == "" ] ; then
   echo >&2 "Usage: env USER_NAME=<user> $0"
   echo >&2 "Example: sudo env USER_NAME=nornetpp $0"
   exit 1
fi


# ====== Wireshark filter rules =============================================
mkdir -p /root/.config/wireshark
sudo -u "${USER_NAME}" mkdir -p "/home/${USER_NAME}/.config/wireshark"
for file in colorfilters dfilters preferences ; do
   cp "/tmp/wireshark/${file}" /root/.config/wireshark
   sudo -u "${USER_NAME}" cp "/tmp/wireshark/${file}" "/home/${USER_NAME}/.config/wireshark"
done
