#!/usr/bin/env bash
# ==========================================================================
#  ___         _        _ _      _   _            ___         _      _
# |_ _|_ _  __| |_ __ _| | |__ _| |_(_)___ _ _   / __| __ _ _(_)_ __| |_ ___
#  | || ' \(_-<  _/ _` | | / _` |  _| / _ \ ' \  \__ \/ _| '_| | '_ \  _(_-<
# |___|_||_/__/\__\__,_|_|_\__,_|\__|_\___/_||_| |___/\__|_| |_| .__/\__/__/
#                                                              |_|
#
#   --- Virtual Machine Image Builder and System Installation Scripts ---
#            https://www.nntb.no/~dreibh/vmimage-builder-scripts/
# ==========================================================================
#
# System Installation Scripts
# Copyright (C) 2017-2026 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

# Bash options:
set -euo pipefail


# ###### Print script name, to make Packer output easier readable ###########
if command -v figlet >/dev/null && command -v print-utf8 >/dev/null ; then
   echo
   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;32m█" "▀" "█\e[0m"
   figlet -w 156 "$(basename "$0")" | LC_ALL=C.UTF-8 print-utf8 -x 160 -n -C "\e[1;32m█\e[22m" "\e[1;32m█\e[0m"
   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;32m█" "▄" "█\e[0m"
else
   echo -e "\e[1;34;22m########## $(basename "$0") ##########\e[0m"
fi

# Enable printing the command-lines executed:
set -x


# ###### Main program #######################################################

# ====== Check environment variables ========================================
if [ ! -v USER_NAME ] || [ "${USER_NAME}" == "" ] ; then
   echo >&2 "Usage: env USER_NAME=<user> $0"
   echo >&2 "Example: sudo env USER_NAME=nornetpp $0"
   exit 1
fi
USER_GROUP="$(id -gn "${USER_NAME}")"
USER_HOME="$(getent passwd "${USER_NAME}" | cut -d: -f6 || awk -F: -v user="${USER_NAME}" '$1==user { print $6 }' /etc/passwd)"

# ====== Obtain system details ==============================================
UNAME="$(uname)"


# ====== Prepare configuration and playlist files ===========================
skelDirectory="/etc/skel"
if [ "${UNAME}" == "FreeBSD" ] ; then
   skelDirectory="/usr/share/skel"
fi

for targetDirectory in "${USER_HOME}" "${skelDirectory}" ; do
   # ------ Create configuration file ---------------------------------------
   if [ ! -e "${targetDirectory}/.config/strawberry/strawberry.conf" ] ; then
      mkdir -p "${targetDirectory}/.config/strawberry"
      cat >"${targetDirectory}/.config/strawberry/strawberry.conf" <<EOF
[MainWindow]
do_not_show_sponsor_message=true
EOF
   fi

   # ------ Copy playlist ---------------------------------------------------
   if [ -e /tmp/data-files/Radios.m3u ] ; then
      mkdir -p "${targetDirectory}/Music"
      cp /tmp/data-files/Radios.m3u "${targetDirectory}/Music/"
   fi

   # ------ Link playlist to desktop ----------------------------------------
   if [ -e "${targetDirectory}/Music/Radios.m3u" ] ; then
      mkdir -p "${targetDirectory}/Desktop"
      if [ ! -e "${targetDirectory}/Desktop/Radios.m3u" ] ; then
         ln -s "../Music/Radios.m3u" "${targetDirectory}/Desktop/"
      fi
   fi
done


# ====== Apply proper permissions and ownership =============================
chown -R "${USER_NAME}":"${USER_GROUP}" "${USER_HOME}/.config/strawberry"
if [ -d "${USER_HOME}/Music" ] ; then
   chown -R "${USER_NAME}":"${USER_GROUP}" "${USER_HOME}/Music"
fi
if [ -d "${USER_HOME}/Desktop" ] ; then
   chown -R "${USER_NAME}":"${USER_GROUP}" "${USER_HOME}/Desktop"
fi
