#!/usr/bin/env bash
#
# Autoinstall Scripts
# Copyright (C) 2017-2024 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

# Bash options:
set -e


# ###########################################################################
# The "Development" installation is based on the "Basic" installation.
#
# It must contain the following packages:
# - Autoconf/Automake/Libtool (basic build tools)
# - CMake (build tool)
# - GNU gcc/g++, GNU Make, GNU Debugger (compilers, debugger and make tool)
# - GraphicsMagick (image conversion)
# - LibTool (build tool for libraries)
# - Valgrind (debugging tool)
#
# Further properties:
# - Password-less sudo calls
#   WARNING: Development settings are intended for developers only!
# - Source packages enabled from package manager (if available)
# ###########################################################################


# ====== Package installation ===============================================

# ------ Ubuntu/Debian ------------------------------------------------------
if [ -e /usr/bin/apt-get ] ; then

   packages="
      autoconf
      automake
      cmake
      g++
      gcc
      gdb
      graphicsmagick
      libtool-bin
      valgrind
   "

   # shellcheck disable=SC2086
   env DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get install -y --no-install-recommends ${packages}

   for list in /etc/apt/sources.list $(find /etc/apt/sources.list.d -name "*.list"); do
      grep "^deb \(.*\)$" "${list}" | \
         sed -e "s/deb[ \t]*//g" | \
         xargs -n1 -I§ echo "s@^#[ \t]*deb-src \(§\)[ \t]*\$@deb-src \\1@g" >"${list}".sed
      sed -f "${list}".sed <"${list}" >"${list}".new
      diff "${list}" "${list}".new || true
      mv "${list}".new "${list}"
      rm -f "${list}".sed
   done


# ------ Fedora -------------------------------------------------------------
elif [ -e /usr/bin/dnf ] ; then

   packages="
      autoconf
      automake
      cmake
      g++
      gcc
      gdb
      GraphicsMagick
      libtool
      valgrind
   "

   # shellcheck disable=SC2086
   /usr/bin/dnf install -y ${packages}


# ------ FreeBSD ------------------------------------------------------------
elif [ -e /usr/sbin/pkg ] ; then

   packages="
      autoconf
      automake
      cmake
      gcc
      gdb
      graphicsmagick
      libtool
      valgrind
   "

   # shellcheck disable=SC2086
   /usr/sbin/pkg install -y ${packages}

fi


# ====== Verify command availability ========================================
echo "Verifying command availability:"
errors=0
for command in autoconf automake cmake g++ gcc gdb gm libtool make valgrind ; do
   echo -n "${command}: "
   if which ${command} >/dev/null ; then
      echo "OK"
   else
      echo "FAILED!"
      errors=$((errors+1))
   fi
done
if [ ${errors} -gt 0 ] ; then
   echo >&2 "ERROR: ${errors} packages are missing!"
   exit 1
fi
