#!/usr/bin/env bash
#
# Autoinstall Scripts
# Copyright (C) 2017-2026 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

# Bash options:
set -eux


# ====== Check/set environment variables ====================================
if [ ! -v USER_NAME ] || [ "${USER_NAME}" == "" ] ; then
   echo >&2 "Usage: env USER_NAME=<user> $0"
   echo >&2 "Example: sudo env USER_NAME=nornetpp $0"
   exit 1
fi
if [ ! -e /etc/os-release ] ; then
   echo >&2 "ERROR: /etc/os-release does not exist!"
   exit 1
fi
. /etc/os-release
if [ ! -v VERSION_ID ] ; then
   VERSION_ID=""
fi


# ====== Package installation ===============================================
architecture="$(uname -m)"
if [[ ! "${architecture}" =~ ^(amd64|x86_64|arm64|aarch64)$ ]] ; then
   echo "Docker is (currently) only available on AMD64 and ARM64 => nothing to do here!"
   exit 0
fi

# ------ Ubuntu/Debian ------------------------------------------------------
if [ "${ID}" == "ubuntu" ] || [ "${ID}" == "debian" ] ; then

   if [ "${ID}" == "ubuntu" ] ; then
      if [[ "${VERSION_ID}" =~ ^(1[2-9]\.[01][04]|2[01]\.[01][04])$ ]] ; then
         # Old Ubuntu versions do not have docker-buildx and docker-cli:
         packages="containerd docker.io docker-compose"
      else
         packages="containerd docker.io docker-buildx docker-cli docker-compose-v2"
      fi
   elif [ "${ID}" == "debian" ] ; then
      if [[ "${VERSION_ID}" =~ ^[0-9]+$  ]] && [[ "${VERSION_ID}" -lt 13 ]] ; then
         # Old Debian versions do not have docker-buildx and docker-cli:
         packages="containerd docker.io docker-compose"
      else
         packages="containerd docker.io docker-buildx docker-cli docker-compose"
      fi
   else
      echo >&2 "ERROR: Inexpected ID ${ID}!"
      exit 1
   fi

   # shellcheck disable=SC2086
   env DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get install -y -m --no-install-recommends ${packages}

   # Add user to "docker" group:
   usermod -a -G docker "${USER_NAME}"


# ------ Fedora -------------------------------------------------------------
elif [ "${ID}" == "fedora" ] ; then

   # Programs:
   packages="containerd docker docker-buildx docker-cli docker-compose"

   # shellcheck disable=SC2086
   /usr/bin/dnf install --setopt=install_weak_deps=False -y ${packages}

   # Add user to "docker" group:
   usermod -a -G docker "${USER_NAME}"


# ------ FreeBSD ------------------------------------------------------------
elif [ "${ID}" == "freebsd" ] ; then

   # FreeBSD has support for Podman:
   # https://freebsdfoundation.org/blog/oci-containers-on-freebsd/

   /usr/sbin/pkg install -y podman-suite

   if [ ! -e /etc/pf.conf ] ; then
      interface="$(ifconfig -l | cut -d' ' -f1)"
      sed -e "s/^v4egress_if[ \t]*=.*$/v4egress_if = ${interface}/" \
          -e "s/^v6egress_if[ \t]*=.*$/v6egress_if = ${interface}/" \
          </usr/local/etc/containers/pf.conf.sample \
          >/etc/pf.conf
   fi
   service pf enable
   service pf start
   service linux enable
   service linux start
   service podman enable
   service podman start

   # Tests:
   # sudo podman run -it --rm ghcr.io/freebsd/freebsd-runtime:14.3 freebsd-version
   # sudo podman run -it --rm --os=linux docker.io/ubuntu:latest cat /etc/os-release
   # sudo podman run -it --rm --os=linux docker.io/dreibh/basic-debian:13 bash --login

# ------ Unknown ------------------------------------------------------------
else

   echo >&2 "ERROR: Unknown ID ${ID} in /etc/os-release. The installation script may need an update for supporting this system!"
   exit 1

fi


# ====== Configuration ======================================================
if [ -d "/etc/docker" ] && [ ! -e "/etc/docker/daemon.json" ] ; then
   # By default, Docker creates a network interface docker0 172.17.0.1/16.
   # Since all systems have the same network, it interferes with SCTP.
   # SCTP assumes that source and destination host are the same => ABORT
   # Solution: Creating a /26 network with random link-local IPv4 address.
   network="169.254.$(( 1 + (RANDOM % 253) )).$(( ((RANDOM % 4) << 6) + 1 ))/26"
   ( cat <<EOF
{
  "bip": "${network}",
  "ipv6": true
}
EOF
   ) | sudo tee "/etc/docker/daemon.json"
   service docker restart || true
fi
if [ -e "/usr/local/etc/containers/containers.conf" ] ; then
   # By default, Podman creates a default network 10.88.0.0/16.
   # Unfortunately, link-local IPv4 addresses do not work here.
   # => Using 192.168.x.y instead:
   network="192.168.$(( 1 + (RANDOM % 253) )).$(( ((RANDOM % 4) << 6) + 1 ))/26"
   sed -e "s@^#default_subnet[ \t]*=[ \t]*\"10.88.0.0/16\"@default_subnet = \"${network}\"@" \
       </usr/local/etc/containers/containers.conf \
       >/usr/local/etc/containers/containers.conf.new
   mv /usr/local/etc/containers/containers.conf.new /usr/local/etc/containers/containers.conf
fi


# ====== Verify command availability ========================================

echo "Verifying command availability:"
errors=0
if [ "$(uname)" == "Linux" ] ; then
   # shellcheck disable=SC2043
   for command in docker ; do
      echo -n "${command}: "
      if which ${command} >/dev/null ; then
         echo "OK"
      else
         echo "FAILED!"
         errors=$((errors+1))
      fi
   done
fi
if [ ${errors} -gt 0 ] ; then
   echo >&2 "ERROR: ${errors} packages are missing!"
   exit 1
fi
