#!/usr/bin/env bash
# ==========================================================================
#  ___         _        _ _      _   _            ___         _      _
# |_ _|_ _  __| |_ __ _| | |__ _| |_(_)___ _ _   / __| __ _ _(_)_ __| |_ ___
#  | || ' \(_-<  _/ _` | | / _` |  _| / _ \ ' \  \__ \/ _| '_| | '_ \  _(_-<
# |___|_||_/__/\__\__,_|_|_\__,_|\__|_\___/_||_| |___/\__|_| |_| .__/\__/__/
#                                                              |_|
#
#   --- Virtual Machine Image Builder and System Installation Scripts ---
#            https://www.nntb.no/~dreibh/vmimage-builder-scripts/
# ==========================================================================
#
# System Installation Scripts
# Copyright (C) 2017-2026 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

# Bash options:
set -euo pipefail



# ###### Main program #######################################################

# ====== Ensure that script is executed by the user account =================
SCRIPT="35-homebrew"   # Set to "$(basename "$0")" of this file!
if command -v figlet >/dev/null && command -v print-utf8 >/dev/null ; then
   echo
   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;31m█" "▀" "█\e[0m"
   figlet -w 156 "${SCRIPT}" | LC_ALL=C.UTF-8 print-utf8 -x 160 -n -C "\e[1;31m█\e[22m" "\e[1;31m█\e[0m"
   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;31m█" "▄" "█\e[0m"
else
   echo -e "\e[1;31;22m########## ${SCRIPT} ##########\e[0m"
fi

# ====== Check environment variables ========================================
if [ ! -v USER_NAME ] || [ "${USER_NAME}" == "" ] ; then
   echo >&2 "Usage: env USER_NAME=<user> $0"
   echo >&2 "Example: sudo env USER_NAME=nornetpp $0"
   exit 1
fi

# Enable printing the command-lines executed:
set -x

USER_GROUP="$(id -gn "${USER_NAME}")"
USER_HOME="$(getent passwd "${USER_NAME}" | cut -d: -f6 || awk -F: -v user="${USER_NAME}" '$1==user { print $6 }' /etc/passwd)"

# ====== Obtain system details ==============================================
UNAME="$(uname)"
NAME="${UNAME}"
ID="${UNAME,,}"
VERSION="$(uname -r)"
VERSION_ID="${VERSION/_*/}"
if [ -f /etc/os-release ] ; then
   . /etc/os-release
fi


# ====== Install Homebrew ===================================================
if [ "${UNAME}" == "Linux" ] ; then
   case "${ID}" in
      debian|ubuntu)
         env DEBIAN_FRONTEND=noninteractive apt-get update && \
         env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends build-essential procps curl file git
         ;;
      fedora)
         dnf install -y gcc gcc-c++ make procps-ng curl file git
         ;;
      opensuse*)
         zypper --non-interactive install gcc gcc-c++ make procps curl file git
         ;;
      alpine)
         apk add --no-cache build-base procps curl file git bash gcompat
         ;;
   esac

   # Create target directory and grant ownership to non-root user:
   mkdir -p /home/linuxbrew/.linuxbrew
   chown -R "${USER_NAME}:${USER_GROUP}" /home/linuxbrew

   # Execute Homebrew installer as non-root user:
   sudo -u "${USER_NAME}" NONINTERACTIVE=1 bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

   if ! grep -qs "brew shellenv" "${USER_HOME}/.bashrc" ; then
      homebrewLocation="/home/linuxbrew/.linuxbrew"
      sudo -u "${USER_NAME}" tee --append "${USER_HOME}/.bashrc" <<EOF

# ------ Homebrew -----------------------------------------------------------
if [ -x "${homebrewLocation}/bin/brew" ] ; then
   eval "\$(${homebrewLocation}/bin/brew shellenv)"
fi
EOF
   fi

fi
