#!/usr/bin/env bash
# ==========================================================================
#  ___         _        _ _      _   _            ___         _      _
# |_ _|_ _  __| |_ __ _| | |__ _| |_(_)___ _ _   / __| __ _ _(_)_ __| |_ ___
#  | || ' \(_-<  _/ _` | | / _` |  _| / _ \ ' \  \__ \/ _| '_| | '_ \  _(_-<
# |___|_||_/__/\__\__,_|_|_\__,_|\__|_\___/_||_| |___/\__|_| |_| .__/\__/__/
#                                                              |_|
#
#   --- Virtual Machine Image Builder and System Installation Scripts ---
#            https://www.nntb.no/~dreibh/vmimage-builder-scripts/
# ==========================================================================
#
# System Installation Scripts
# Copyright (C) 2017-2026 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

# Bash options:
set -euo pipefail


# ###### Print script name, to make Packer output easier readable ###########
SCRIPT="39-source-repositories"   # Set to "$(basename "$0")" of this file!
if command -v figlet >/dev/null && command -v print-utf8 >/dev/null ; then
   echo
   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;31m█" "▀" "█\e[0m"
   figlet -w 156 "${SCRIPT}" | LC_ALL=C.UTF-8 print-utf8 -x 160 -n -C "\e[1;31m█\e[22m" "\e[1;31m█\e[0m"
   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;31m█" "▄" "█\e[0m"
else
   echo -e "\e[1;31;22m########## ${SCRIPT} ##########\e[0m"
fi

# Enable printing the command-lines executed:
set -x


# ###### Main program #######################################################

# ====== Obtain system details ==============================================
UNAME="$(uname)"
NAME="${UNAME}"
ID="${UNAME,,}"
VERSION="$(uname -r)"
VERSION_ID="${VERSION/_*/}"
if [ -f /etc/os-release ] ; then
   . /etc/os-release
fi


# ====== Enable source repositories =========================================

# ------ Ubuntu/Debian ------------------------------------------------------
if [ "${ID}" == "ubuntu" ] || [ "${ID}" == "debian" ] ; then

   # Enable APT source repositories:
   (
      if [ -f /etc/apt/sources.list ] ; then
         echo "/etc/apt/sources.list"
      fi
      if [ -d /etc/apt/sources.list.d ] ; then
         find /etc/apt/sources.list.d -mindepth 1 -maxdepth 1 \( -name "*.list" -o -name "*.sources" \)
      fi
   ) | while read -r sourceFile ; do
      if [[ "${sourceFile}" =~ .sources$ ]] ; then
         echo >&2 "Processing sources file: ${sourceFile} ..."
         while IFS= read -r line || [ -n "${line}" ] ; do
            if [[ "${line}" =~ ^(Types:[ \t]) ]] ; then
               types="$(echo "${line}" | cut -d' ' -f2- | xargs -n1 | sort -u | xargs)"
               hasSrc=0
               for type in ${types} ; do
                  if [ "${type}" == "deb-src" ] ; then
                     hasSrc=1
                     break
                  fi
               done
               if [ "${hasSrc}" -eq 0 ] ; then
                  types="${types} deb-src"
               fi
               echo "Types: ${types}"
            else
               echo "${line}"
            fi
         done <"${sourceFile}" >"${sourceFile}.new"
         diff --color "${sourceFile}" "${sourceFile}.new" || true
         mv "${sourceFile}.new" "${sourceFile}"
      elif [[ "${sourceFile}" =~ .list$ ]] ; then
         echo >&2 "Processing list file: ${sourceFile} ..."
         activateSource=0
         while IFS= read -r line || [ -n "${line}" ] ; do
            if [[ "${line}" =~ ^(deb[ \t]) ]] ; then
               echo "${line}"
               activateSource=1
            elif [[ "${line}" =~ ^(# deb-src[ \t]) ]] && [ ${activateSource} -eq 1 ] ; then
               # shellcheck disable=SC2001
               echo "${line}" | sed -e "s/^#[ \t]*//"
               activateSource=0
            else
               echo "${line}"
               activateSource=0
            fi
         done <"${sourceFile}" >"${sourceFile}.new"
         diff --color "${sourceFile}" "${sourceFile}.new" || true
         mv "${sourceFile}.new" "${sourceFile}"
      fi
   done


# ------ Fedora, OpenSUSE, Alpine -------------------------------------------
elif [ "${ID}" == "fedora"     ] || \
     [[ "${ID}" =~ ^opensuse- ]] || \
     [ "${ID}" == "alpine"     ] ; then

   # Nothing to do here!
   true


# ------ FreeBSD, NetBSD, OpenBSD -------------------------------------------
elif [ "${ID}" == "freebsd" ] || \
     [ "${ID}" == "netbsd"  ] || \
     [ "${ID}" == "openbsd" ] ; then

   # Nothing to do here: BSD sources = ports.
   true


# ------ Solaris ------------------------------------------------------------
elif [ "${ID}" == "sunos" ] ; then

   # Nothing to do here!
   true


# ------ Unknown ------------------------------------------------------------
else

   echo >&2 "ERROR: Unknown ID ${ID} in /etc/os-release. The installation script may need an update for supporting this system!"
   exit 1

fi
