#!/usr/bin/env bash
#
# Autoinstall Scripts
# Copyright (C) 2017-2024 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

# Bash options:
set -ex


UNAME="$(uname)"


# ====== NorNet configuration ===============================================
if [ "${UNAME}" == "Linux" ] ; then

   # !!! Ensure that growpart and resizefs are enabled !!!!!!!!!!!!!!!!!!!!!!!!!
   # With new Ubuntu autoinstaller:
   # /etc/cloud/cloud.cfg.d/99-installer.cfg disables growpart and resizefs
   # => fixing this here:
   if [ -e /etc/cloud/cloud.cfg.d/99-installer.cfg ] ; then
      sed -e "s#growpart: {mode: 'off'}#growpart: {mode: 'auto'}#g" \
          -e "s#resize_rootfs: false#resize_rootfs: true#g" \
          -i /etc/cloud/cloud.cfg.d/99-installer.cfg
   fi


   # ------ Ubuntu ----------------------------------------------------------
   if [ -e /usr/bin/apt-get ] ; then
      /usr/bin/apt-get update

      # Install cron-apt, autofs without recommended packets. This prevents
      # installing postfix (opens port 25) and rpcbind (opens port 111)!
      env DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get install --no-install-recommends -y \
         cron-apt autofs

      packages="nornet-management td-system-configure-grub"

      # Try 3 times, for the case of download issues:
      # shellcheck disable=SC2086
      env DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get install -y --no-install-recommends ${packages}

      # The nornet-autoupdate package only exists for newer Ubuntu versions:
      release="$(lsb_release -c | cut -d':' -f2 | tr -d ' \t')"
      if [ "${release}" != "precise" ] ; then
         env DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get install -y --no-install-recommends \
            nornet-autoupdate
      fi

   # ------ Fedora ----------------------------------------------------------
   elif [ -e /usr/bin/dnf ] ; then
      /usr/bin/dnf install -y nornet-management nornet-autoupdate td-system-tools-configure-grub
   fi


   # ====== Set configured screen resolution as fallback ====================
   if [ -e /etc/default/grub ] ; then
      /usr/bin/configure-grub /etc/default/grub \
         -V "auto,${VIDEO},1024x768" \
         -T "20000 584 144 736 48 1048 288 984 96 784 63 0 1 656 64 880 63 0 1 1176 192" \
         -o /etc/default/grub
   fi

elif [ "${UNAME}" == "FreeBSD" ] ; then
   true

fi
