#!/usr/bin/env bash
#
# Autoinstall Scripts
# Copyright (C) 2017-2025 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

# Bash options:
set -eux


# ###### Clone or update Git repository #####################################
clone-or-update ()
{
   local repository="$1"
   local url="$2"
   local clone_maxtrials=10
   local clone_delay=60
   if [ ! -e "${repository}" ] ; then
      try-hard ${clone_maxtrials} ${clone_delay} -- sudo -u "${USER_NAME}" git clone "${url}" "${repository}"
   else
      pushd "${repository}"
      try-hard ${clone_maxtrials} ${clone_delay} -- sudo -u "${USER_NAME}" git fetch --all
      try-hard ${clone_maxtrials} ${clone_delay} -- sudo -u "${USER_NAME}" git pull
      popd
   fi
}


# ====== Check environment variables ========================================
if [ ! -v USER_NAME ] || [ "${USER_NAME}" == "" ] ; then
   echo >&2 "Usage: env USER_NAME=<user> $0"
   echo >&2 "Example: sudo env USER_NAME=nornetpp $0"
   exit 1
fi
if [ ! -e /etc/os-release ] ; then
   echo >&2 "ERROR: /etc/os-release is not available!"
   exit 1
fi
. /etc/os-release


# ====== Package installation ===============================================

# ------ Debian -------------------------------------------------------------
if [ "${ID}" == "debian" ] ; then

   # Work-around for SimulaMet Environment not (yet) in Debian:
   packages="
      texlive-full
   "
   # libreoffice-l10n-en-gb libreoffice-l10n-de libreoffice-l10n-nb hunspell-de-de hunspell-no hunspell-en-gb hunspell-en-us hunspell-en-au

   # shellcheck disable=SC2086
   env DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get install -y --no-install-recommends ${packages}

   sudo -u "${USER_NAME}" mkdir -p "/home/${USER_NAME}/src"
   cd "/home/${USER_NAME}/src"
   clone-or-update simulamet https://dreibh@github.com/dreibh/simulamet

   cores=$(getconf _NPROCESSORS_ONLN 2>/dev/null || echo "1")
   cd "/home/${USER_NAME}/src/simulamet"
   sudo -u "${USER_NAME}" cmake . -DCMAKE_INSTALL_PREFIX=/usr -DFLAT_DIRECTORY_STRUCTURE=0 -DPRINT_A4=1 -DINSTALL_ORIGINALS=0 -DCMAKE_VERBOSE_MAKEFILE=OFF
   sudo -u "${USER_NAME}" make -j"${cores}"
   make install

   cd "/home/${USER_NAME}/src"
   rm -rf simulamet

   mkdir -p /boot/SimulaMet
   cp /usr/share/simulamet/Splash/*.jpeg /boot/SimulaMet
   update-grub

# ------ Ubuntu -------------------------------------------------------------
elif [ "${ID}" == "ubuntu" ] ; then

   packages="
      simulamet-management
      simulamet-desktop
      simulamet-development
      texlive-full
   "
   # libreoffice-l10n-en-gb libreoffice-l10n-de libreoffice-l10n-nb hunspell-de-de hunspell-no hunspell-en-gb hunspell-en-us hunspell-en-au

   # shellcheck disable=SC2086
   env DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get install -y --no-install-recommends ${packages}

# ------ Fedora -------------------------------------------------------------
elif [ "${ID}" == "fedora" ] ; then

   packages="
      simulamet-management
      simulamet-desktop
      simulamet-development
      texlive-scheme-full
   "

   # shellcheck disable=SC2086
   /usr/bin/dnf install --setopt=install_weak_deps=False -y ${packages}

# ------ FreeBSD ------------------------------------------------------------
elif [ "${ID}" == "freebsd" ] ; then

   # Ensure that fonts configuration is up-to-date:
   fc-cache -fv

   # Work-around for SimulaMet Environment not (yet) in FreeBSD Ports Collection:
   sudo -u "${USER_NAME}" mkdir -p "/home/${USER_NAME}/src"
   cd "/home/${USER_NAME}/src"
   clone-or-update simulamet https://dreibh@github.com/dreibh/simulamet

   cores=$(sysctl -a | grep 'hw.ncpu' | cut -d ':' -f2 | tr -d ' ' || echo "1")
   cd "/home/${USER_NAME}/src/simulamet"
   sudo -u "${USER_NAME}" cmake . -DCMAKE_INSTALL_PREFIX=/usr/local
   sudo -u "${USER_NAME}" make -j"${cores}"
   make install
   if [ ! -e /usr/share/simulamet ] ; then
      sudo ln -s /usr/local/share/simulamet /usr/share/simulamet
   fi

   cd "/home/${USER_NAME}/src"
   rm -rf simulamet

# ------ Unknown ------------------------------------------------------------
else

   echo >&2 "ERROR: Unknown ID ${ID} in /etc/os-release. The installation script may need an update for supporting this system!"
   exit 1

fi
