#!/usr/bin/env bash
#
# Autoinstall Scripts
# Copyright (C) 2017-2025 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

# Bash options:
set -eux


# ====== Check environment variables ========================================
if [ ! -v USER_NAME ] || [ "${USER_NAME}" == "" ] ; then
   echo >&2 "Usage: env USER_NAME=<user> $0"
   echo >&2 "Example: sudo env USER_NAME=nornetpp $0"
   exit 1
fi
if [ ! -e /etc/os-release ] ; then
   echo >&2 "ERROR: /etc/os-release is not available!"
   exit 1
fi
. /etc/os-release


# ====== Install DBeaver Community Edition ==================================

# ------ Debian -------------------------------------------------------------
# Default location:
dbeaverConfigurationDirectory="/home/${USER_NAME}/.local/share/DBeaverData/workspace6"
if [ "${ID}" == "debian" ] ; then

   env DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get install -y --no-install-recommends flatpak
   flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
   flatpak install -y flathub io.dbeaver.DBeaverCommunity

# ------ Ubuntu -------------------------------------------------------------
elif [ "${ID}" == "ubuntu" ] ; then

   rm -f /etc/apt/preferences.d/block-snapd.pref
   env DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get install -y --no-install-recommends snapd
   try-hard 3 60 -- snap install dbeaver-ce

   if [ ! -d "/home/${USER_NAME}/snap/dbeaver-ce/current" ] ; then
      dbeaverSnapVersion="$(snap list dbeaver-ce | awk '/^dbeaver-ce/ { print $3 }')"
      echo "V=$dbeaverSnapVersion"
      sudo -u "${USER_NAME}" ln -rs "/home/${USER_NAME}/snap/dbeaver-ce/${dbeaverSnapVersion}" "/home/${USER_NAME}/snap/dbeaver-ce/current"
   else
      dbeaverSnapVersion="current"
   fi
   dbeaverConfigurationDirectory="/home/${USER_NAME}/snap/dbeaver-ce/${dbeaverSnapVersion}/.local/share/DBeaverData/workspace6"

# ------ Fedora -------------------------------------------------------------
elif [ "${ID}" == "fedora" ] ; then

   wget -O /tmp/dbeaver.rpm "https://dbeaver.io/files/dbeaver-ce-latest-stable.x86_64.rpm"
   dnf install --setopt=install_weak_deps=False -y /tmp/dbeaver.rpm

# ------ FreeBSD ------------------------------------------------------------
elif [ "${ID}" == "freebsd" ] ; then

   pkg install -y dbeaver

# ------ Unknown ------------------------------------------------------------
else

   echo >&2 "ERROR: Unknown ID ${ID} in /etc/os-release. The installation script may need an update for supporting this system!"
   exit 1

fi


# ====== Make initial configuration =========================================
sudo -u "${USER_NAME}" mkdir -p "${dbeaverConfigurationDirectory}/General/.dbeaver"
sudo -u "${USER_NAME}" mkdir -p "${dbeaverConfigurationDirectory}/.metadata/.plugins/org.eclipse.core.runtime/.settings"
if [ ! -e "${dbeaverConfigurationDirectory}/General/.dbeaver/data-sources.json" ] ; then

   echo "{}" | sudo -u "${USER_NAME}" tee "${dbeaverConfigurationDirectory}/General/.dbeaver/data-sources.json"

   (
      cat <<EOF
eclipse.preferences.version=1
org.jkiss.dbeaver.core.confirm.exit=never
tipOfTheDayInitializer.notFirstRun=true
ui.show.tip.of.the.day.on.startup=false
EOF
   ) | sudo -u "${USER_NAME}" tee "${dbeaverConfigurationDirectory}/.metadata/.plugins/org.eclipse.core.runtime/.settings/org.jkiss.dbeaver.core.prefs"

   (
      cat <<EOF
eclipse.preferences.version=1
feature.tracking.skipConfirmation=true
EOF
   ) | sudo -u "${USER_NAME}" tee "${dbeaverConfigurationDirectory}/.metadata/.plugins/org.eclipse.core.runtime/.settings/org.jkiss.dbeaver.ui.statistics.prefs"

fi
