#!/usr/bin/env bash
#
# Autoinstall Scripts
# Copyright (C) 2017-2024 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

# Bash options:
set -exu


# ====== Check environment variables ========================================
if [ "${USER_NAME}" == "" ] ; then
   echo >&2 "Usage: env USER_NAME=<user> $0"
   echo >&2 "Example: sudo env USER_NAME=nornetpp $0"
   exit 1
fi
if [ ! -e /etc/os-release ] ; then
   echo >&2 "ERROR: /etc/os-release is not available!"
   exit 1
fi
. /etc/os-release


# ====== Install DBeaver Community Edition ==================================

# ------ Debian -------------------------------------------------------------
if [ "${ID}" == "debian" ] ; then

   env DEBIAN_FRONTEND=noninteractive apt install -y  --no-install-recommends flatpak
   flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
   flatpak install -y flathub io.dbeaver.DBeaverCommunity

# ------ Ubuntu -------------------------------------------------------------
elif [ "${ID}" == "ubuntu" ] ; then

   rm -f /etc/apt/preferences.d/block-snapd.pref
   env DEBIAN_FRONTEND=noninteractive apt install -y  --no-install-recommends snapd
   snap install dbeaver-ce

# ------ Fedora -------------------------------------------------------------
elif [ "${ID}" == "fedora" ] ; then

   wget -O /tmp/dbeaver.rpm "https://dbeaver.io/files/dbeaver-ce-latest-stable.x86_64.rpm"
   sudo dnf install -y /tmp/dbeaver.rpm

# ------ FreeBSD ------------------------------------------------------------
elif [ "${ID}" == "freebsd" ] ; then

   # FIXME!
   true

   # Based on: https://forums.freebsd.org/threads/how-to-install-dbeaver-in-freebsd.91496/

   # pkg install -y maven openjdk17
   # sudo -u "${USER_NAME}" wget -O /tmp/dbeaver.tar.gz "https://github.com/dbeaver/dbeaver/archive/refs/tags/23.3.3.tar.gz"
   # cd "/home/${USER_NAME}/src"
   # sudo -u "${USER_NAME}" tar xzf /tmp/dbeaver.tar.gz
   # cd dbeaver*
   # pwd
   # sudo -u "${USER_NAME}" JAVA_HOME=/usr/local/openjdk17 mvn package -Pall-platforms

# ------ Unknown ------------------------------------------------------------
else

   echo >&2 "ERROR: Unknown ID ${ID} in /etc/os-release. The installation script may need an update for supporting this system!"
   exit 1

fi
