#!/usr/bin/env bash
#
# Autoinstall Scripts
# Copyright (C) 2017-2024 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

# Bash options:
set -ex


# ====== Check environment variables ========================================
if [ "${USER_NAME}" == "" ] ; then
   echo >&2 "Usage: env USER_NAME=<user> $0"
   echo >&2 "Example: sudo env USER_NAME=nornetpp $0"
   exit 1
fi


# ====== Prepare source repositories ========================================
sudo -u "${USER_NAME}" mkdir -p "/home/${USER_NAME}/src"
cd "/home/${USER_NAME}/src"

if [ ! -e rsplib ] ; then
   sudo -u "${USER_NAME}" git clone https://dreibh@github.com/dreibh/rsplib
fi
if [ ! -e rserpooldemo ] ; then
   sudo -u "${USER_NAME}" git clone https://dreibh@github.com/dreibh/rserpooldemo
fi
if [ ! -e rsplib ] ; then
   sudo -u "${USER_NAME}" git clone https://dreibh@github.com/dreibh/rsplib
fi
if [ ! -e socketapi ] ; then
   sudo -u "${USER_NAME}" git clone https://dreibh@github.com/dreibh/socketapi
fi
if [ ! -e vmimage-builder-scripts ] ; then
   sudo -u "${USER_NAME}" git clone https://dreibh@github.com/simula/nornet-vmimage-builder-scripts.git vmimage-builder-scripts
fi


# ====== Package installation ===============================================

# ------ Ubuntu/Debian ------------------------------------------------------
if [ -e /usr/bin/apt-get ] ; then

   packages="
      rserpooldemo-desktop
      rserpooldemo-development
      rserpooldemo-tool
   "

   # shellcheck disable=SC2086
   env DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get install -y --no-install-recommends ${packages}


# ------ Fedora -------------------------------------------------------------
elif [ -e /usr/bin/dnf ] ; then

   packages="
      rserpooldemo-desktop
      rserpooldemo-development
      rserpooldemo-tool
   "

   # shellcheck disable=SC2086
   /usr/bin/dnf install -y ${packages}


# ------ FreeBSD ------------------------------------------------------------
elif [ -e /usr/sbin/pkg ] ; then

   # FIXME! Work-around for RSerPool Demo not (yet) in FreeBSD Ports Collection:
   cores=$(sysctl -a | grep 'hw.ncpu' | cut -d ':' -f2 | tr -d ' ' || echo "1")
   cd "/home/${USER_NAME}/src/rserpooldemo"
   sudo -u "${USER_NAME}" cmake . -DCMAKE_INSTALL_PREFIX=/usr/local
   sudo -u "${USER_NAME}" make -j${cores}
   sudo make install
   sudo update-mime-database /usr/local/share/mime
   sudo update-desktop-database

fi


# ====== Add demo scenario icon to desktop ==================================
if [ "$(uname)" == "FreeBSD" ] ; then
   usrPrefix="/usr/local"
else
   usrPrefix="/usr"
fi
sudo -u "${USER_NAME}" mkdir -p "/home/${USER_NAME}/Desktop"
if [ -e ${usrPrefix}/share/rserpooldemo/local-scenario/local-setup.xml ] ; then
   sudo -u "${USER_NAME}" ln -s ${usrPrefix}/share/rserpooldemo/local-scenario/local-setup.xml "/home/${USER_NAME}/Desktop/" || true
fi
