#!/usr/bin/env bash
# ==========================================================================
#  ___         _        _ _      _   _            ___         _      _
# |_ _|_ _  __| |_ __ _| | |__ _| |_(_)___ _ _   / __| __ _ _(_)_ __| |_ ___
#  | || ' \(_-<  _/ _` | | / _` |  _| / _ \ ' \  \__ \/ _| '_| | '_ \  _(_-<
# |___|_||_/__/\__\__,_|_|_\__,_|\__|_\___/_||_| |___/\__|_| |_| .__/\__/__/
#                                                              |_|
#
#   --- Virtual Machine Image Builder and System Installation Scripts ---
#            https://www.nntb.no/~dreibh/vmimage-builder-scripts/
# ==========================================================================
#
# System Installation Scripts
# Copyright (C) 2017-2026 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

# Bash options:
set -euo pipefail


# ###### Print script name, to make Packer output easier readable ###########
if command -v figlet >/dev/null && command -v print-utf8 >/dev/null ; then
   echo
   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;35m█" "▀" "█\e[0m"
   figlet -w 156 "$(basename "$0")" | LC_ALL=C.UTF-8 print-utf8 -x 160 -n -C "\e[1;35m█\e[22m" "\e[1;35m█\e[0m"
   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;35m█" "▄" "█\e[0m"
else
   echo -e "\e[1;34;22m########## $(basename "$0") ##########\e[0m"
fi

# Enable printing the command-lines executed:
set -x


# ###### Clone or update Git repository #####################################
clone-or-update ()
{
   local repository="$1"
   local url="$2"
   local clone_maxtrials=10
   local clone_delay=60
   if [ ! -e "${repository}" ] ; then
      try-hard ${clone_maxtrials} ${clone_delay} -- sudo -u "${USER_NAME}" git clone "${url}" "${repository}"
   else
      pushd "${repository}" >/dev/null
      try-hard ${clone_maxtrials} ${clone_delay} -- sudo -u "${USER_NAME}" git fetch --all
      try-hard ${clone_maxtrials} ${clone_delay} -- sudo -u "${USER_NAME}" git pull
      popd >/dev/null
   fi
}


# ###### Main program #######################################################

# ====== Obtain system details ==============================================
UNAME="$(uname)"
NAME="${UNAME}"
ID="${UNAME,,}"
VERSION="$(uname -r)"
VERSION_ID="${VERSION/_*/}"
if [ -f /etc/os-release ] ; then
   . /etc/os-release
fi

# ====== Check environment variables ========================================
if [ ! -v USER_NAME ] || [ "${USER_NAME}" == "" ] ; then
   echo >&2 "Usage: env USER_NAME=<user> $0"
   echo >&2 "Example: sudo env USER_NAME=nornetpp $0"
   exit 1
fi
USER_HOME="$(getent passwd "${USER_NAME}" | cut -d: -f6 || awk -F: -v user="${USER_NAME}" '$1==user { print $6 }' /etc/passwd)"


# ====== Prepare source repositories ========================================
sudo -u "${USER_NAME}" mkdir -p "${USER_HOME}/src"
cd "${USER_HOME}/src"

clone-or-update rsplib                  https://dreibh@github.com/dreibh/rsplib
clone-or-update rserpooldemo            https://dreibh@github.com/dreibh/rserpooldemo
clone-or-update sctplib                 https://dreibh@github.com/dreibh/sctplib
clone-or-update socketapi               https://dreibh@github.com/dreibh/socketapi
clone-or-update vmimage-builder-scripts https://dreibh@github.com/simula/nornet-vmimage-builder-scripts


# ====== Package installation ===============================================

# ------ Ubuntu/Debian ------------------------------------------------------
if [ "${ID}" == "ubuntu" ] || [ "${ID}" == "debian" ] ; then

   packages=(
      rserpooldemo-desktop
      rserpooldemo-development
      rserpooldemo-tool
      rsplib-registrar
   )
   env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends "${packages[@]}"

   systemctl stop rspregistrar
   systemctl disable rspregistrar

# ------ Fedora -------------------------------------------------------------
elif [ "${ID}" == "fedora" ] ; then

   packages=(
      rserpooldemo-desktop
      rserpooldemo-development
      rserpooldemo-tool
      rsplib-registrar
   )
   dnf install --setopt=install_weak_deps=False -y "${packages[@]}"

   systemctl stop rspregistrar
   systemctl disable rspregistrar

# ------ FreeBSD ------------------------------------------------------------
elif [ "${ID}" == "freebsd" ] ; then

   # Ensure that fonts configuration is up-to-date:
   fc-cache -fv

   # FIXME! Work-around for RSerPool Demo not (yet) in FreeBSD Ports Collection:
   cores="$(sysctl -a | grep "^hw.ncpu" | cut -d ":" -f2 | tr -d " " || echo "1")"
   cd "${USER_HOME}/src/rserpooldemo"
   sudo -u "${USER_NAME}" cmake . -DCMAKE_INSTALL_PREFIX=/usr/local
   sudo -u "${USER_NAME}" make -j"${cores}"
   make install
   update-mime-database /usr/local/share/mime
   update-desktop-database
   if [ ! -e /usr/share/rserpooldemo ] ; then
      sudo ln -s /usr/local/share/rserpooldemo /usr/share/rserpooldemo
   fi

# ------ Unknown ------------------------------------------------------------
else

   echo >&2 "ERROR: Unknown ID ${ID} in /etc/os-release. The installation script may need an update for supporting this system!"
   exit 1

fi


# ====== Add demo scenario icon to desktop ==================================
if [ "${ID}" == "freebsd" ] ; then
   usrPrefix="/usr/local"
else
   usrPrefix="/usr"
fi
sudo -u "${USER_NAME}" mkdir -p "${USER_HOME}/Desktop"
if [ -e ${usrPrefix}/share/rserpooldemo/local-scenario/local-setup.xml ] ; then
   sudo -u "${USER_NAME}" ln -s ${usrPrefix}/share/rserpooldemo/local-scenario/local-setup.xml "${USER_HOME}/Desktop/" || true
fi
if [ -e ${usrPrefix}/share/rserpooldemo/nornet-mec-scenario/nornet-mec-setup-localonly.xml ] ; then
   sudo -u "${USER_NAME}" ln -s ${usrPrefix}/share/rserpooldemo/nornet-mec-scenario/nornet-mec-setup-localonly.xml "${USER_HOME}/Desktop/" || true
fi
