#!/usr/bin/env bash
# ==========================================================================
#  ___         _        _ _      _   _            ___         _      _
# |_ _|_ _  __| |_ __ _| | |__ _| |_(_)___ _ _   / __| __ _ _(_)_ __| |_ ___
#  | || ' \(_-<  _/ _` | | / _` |  _| / _ \ ' \  \__ \/ _| '_| | '_ \  _(_-<
# |___|_||_/__/\__\__,_|_|_\__,_|\__|_\___/_||_| |___/\__|_| |_| .__/\__/__/
#                                                              |_|
#
#   --- Virtual Machine Image Builder and System Installation Scripts ---
#            https://www.nntb.no/~dreibh/vmimage-builder-scripts/
# ==========================================================================
#
# System Installation Scripts
# Copyright (C) 2017-2026 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

# Bash options:
set -euo pipefail


# ###### Print script name, to make Packer output easier readable ###########
if command -v figlet >/dev/null && command -v print-utf8 >/dev/null ; then
   echo
   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;36m█" "▀" "█\e[0m"
   figlet -w 156 "$(basename "$0")" | LC_ALL=C.UTF-8 print-utf8 -x 160 -n -C "\e[1;36m█\e[22m" "\e[1;36m█\e[0m"
   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;36m█" "▄" "█\e[0m"
else
   echo -e "\e[1;34;22m########## $(basename "$0") ##########\e[0m"
fi

# Enable printing the command-lines executed:
set -x


# ###### Main program #######################################################

# ====== Obtain system details ==============================================
UNAME="$(uname)"
NAME="${UNAME}"
ID="${UNAME,,}"
VERSION="$(uname -r)"
VERSION_ID="${VERSION/_*/}"
if [ -f /etc/os-release ] ; then
   . /etc/os-release
fi

if command -v virt-what >/dev/null ; then
   HYPERVISOR=" $(virt-what | xargs) "
else
   HYPERVISOR=""
fi


# ====== Package installation ===============================================

# ------ Ubuntu/Debian ------------------------------------------------------
if [ "${ID}" == "ubuntu" ] || [ "${ID}" == "debian" ] ; then

   # ------ Prevent suspend/hibernation -------------------------------------
   if [ "${HYPERVISOR}" != "" ] ; then
      if [ -e /etc/systemd/sleep.conf ] ; then
         sed -e "s/^#\?AllowSuspend=.*$/AllowSuspend=no/" \
             -e "s/^#\?AllowHibernation=.*$/AllowHibernation=no/" \
             -i /etc/systemd/sleep.conf
      fi
   fi

   # ------ VirtualBox ------------------------------------------------------
   if [[ "${HYPERVISOR}" =~ " virtualbox " ]] ; then
      # shellcheck disable=SC2071
      if [ "${ID}" == "debian" ] && [[ "${VERSION_ID}" =~ ^[0-9]+$  ]] && [[ "${VERSION_ID}" -gt 12 ]] ; then
         # FIXME! Yet another ugly Debian work-around:
         #        virtualbox-guest-utils/x11 is missing in Debian 13
         #        => needs to be added manually:
         architecture="$(dpkg --print-architecture)"
         cd /tmp/installtmp
         wget -rq --no-parent --accept-regex 'virtualbox-guest-.*deb$' https://ftp.debian.org/debian/pool/contrib/v/virtualbox/
         pkg1="$(find /tmp/installtmp/ftp.debian.org/debian/pool/contrib/v/virtualbox/ -name "virtualbox-guest-utils_*_${architecture}.deb")"
         if [ ! -e /usr/lib/systemd/system/sddm.service ] ; then
            packages="${pkg1}"
         else
            pkg2="$(find /tmp/installtmp/ftp.debian.org/debian/pool/contrib/v/virtualbox/ -name "virtualbox-guest-x11_*_${architecture}.deb")"
            packages="${pkg1} ${pkg2}"
         fi
         version="$(echo "${packages}" | xargs -n1 | sed -e 's/\(.*\)_\([^/-]*\)-.*$/\2/' | sort -urV | head -n1)"
         echo "${packages}"
         echo "${version}"
         packages="$(echo "${packages}" | xargs -n1 | grep "${version}" || true)"
         echo "${packages}"
         # shellcheck disable=SC2086
         env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends ${packages}
      else
         env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
            virtualbox-guest-utils || true
         if [ -e /usr/lib/systemd/system/sddm.service ] ; then
            # System has X11 -> also install X11 utilities as well:
            env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
               virtualbox-guest-x11 || true
         fi
      fi
   # ------ vSphere ---------------------------------------------------------
   elif [[ "${HYPERVISOR}" =~ " vmware " ]] ; then
      env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
         open-vm-tools
      if [ -e /usr/lib/systemd/system/sddm.service ] ; then
         # System has X11 -> also install X11 utilities as well:
         env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
            open-vm-tools-desktop || true
      fi
   # ------ QEMU ------------------------------------------------------------
   elif [[ "${HYPERVISOR}" =~ " kvm " ]] ; then
      env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
         qemu-guest-agent
   fi

   # ------ Not in QEMU -> remove qemu-guest-agent --------------------------
   if [[ ! "${HYPERVISOR}" =~ " kvm " ]] || [[ "${HYPERVISOR}" =~ " virtualbox " ]] ; then
      # NOTE: qemu-guest-agent may have been installed as part of th
      #       initial setup, since e.g. the Proxmox builder may expect it!
      apt-get autoremove -y --purge qemu-guest-agent || true
   fi

   # ------ Not in QEMU -> remove open-vm-tools -----------------------------
   if [ "${HYPERVISOR}" != "vmware" ] ; then
      apt-get autoremove -y --purge open-vm-tools || true
   fi


# ------ Fedora -------------------------------------------------------------
elif [ "${ID}" == "fedora" ] ; then

   # ------ VirtualBox ------------------------------------------------------
   if [[ "${HYPERVISOR}" =~ " virtualbox " ]] || [[ "${HYPERVISOR}" =~ " virtualbox " ]] ; then
      dnf install --setopt=install_weak_deps=False -y virtualbox-guest-additions
   # ------ vSphere ---------------------------------------------------------
   elif [ "${HYPERVISOR}" == "vmware" ] ; then
      dnf install --setopt=install_weak_deps=False -y open-vm-tools
      if [ -e /usr/lib/systemd/system/sddm.service ] ; then
         # System has X11 -> also install X11 utilities as well:
         dnf install --setopt=install_weak_deps=False -y open-vm-tools-desktop
      fi
   # ------ QEMU ------------------------------------------------------------
   elif [[ "${HYPERVISOR}" =~ " kvm " ]] ; then
      dnf install --setopt=install_weak_deps=False -y qemu-guest-agent
   fi

   # ------ Not in QEMU -> remove qemu-guest-agent --------------------------
   if [[ ! "${HYPERVISOR}" =~ " kvm " ]] || [[ "${HYPERVISOR}" =~ " virtualbox " ]] ; then
      # NOTE: qemu-guest-agent may have been installed as part of th
      #       initial setup, since e.g. the Proxmox builder may expect it!
      dnf remove -y qemu-guest-agent || true
   fi


# ------ OpenSUSE -----------------------------------------------------------
elif [[ "${ID}" =~ ^opensuse- ]] ; then

   # ------ VirtualBox ------------------------------------------------------
   if [[ "${HYPERVISOR}" =~ " virtualbox " ]] || [[ "${HYPERVISOR}" =~ " virtualbox " ]] ; then
      zypper --non-interactive install --no-recommends -y virtualbox-guest-tools
   # ------ vSphere ---------------------------------------------------------
   elif [ "${HYPERVISOR}" == "vmware" ] ; then
      zypper --non-interactive install --no-recommends -y open-vm-tools
   # ------ QEMU ------------------------------------------------------------
   elif [[ "${HYPERVISOR}" =~ " kvm " ]] ; then
      zypper --non-interactive install --no-recommends -y qemu-guest-agent
   fi

   # ------ Not in QEMU -> remove qemu-guest-agent --------------------------
   if [[ ! "${HYPERVISOR}" =~ " kvm " ]] || [[ "${HYPERVISOR}" =~ " virtualbox " ]] ; then
      zypper --non-interactive remove -y qemu-guest-agent || true
   fi


# ------ Alpine -------------------------------------------------------------
elif [ "${ID}" == "alpine" ] ; then

   # ------ VirtualBox ------------------------------------------------------
   if [[ "${HYPERVISOR}" =~ " virtualbox " ]] || [[ "${HYPERVISOR}" =~ " virtualbox " ]] ; then
      apk add virtualbox-guest-additions
   # ------ vSphere ---------------------------------------------------------
   elif [ "${HYPERVISOR}" == "vmware" ] ; then
      apk add open-vm-tools
   # ------ QEMU ------------------------------------------------------------
   elif [[ "${HYPERVISOR}" =~ " kvm " ]] ; then
      apk add qemu-guest-agent
   fi

   # ------ Not in QEMU -> remove qemu-guest-agent --------------------------
   if [[ ! "${HYPERVISOR}" =~ " kvm " ]] || [[ "${HYPERVISOR}" =~ " virtualbox " ]] ; then
      apk del qemu-guest-agent || true
   fi


# ------ FreeBSD ------------------------------------------------------------
elif [ "${ID}" == "freebsd" ] ; then

   # ------ VirtualBox ------------------------------------------------------
   if [[ "${HYPERVISOR}" =~ " virtualbox " ]] ; then
      pkg install -y virtualbox-ose-additions-72
      sysrc vboxguest_enable="YES"   ; service vboxguest   start || true
      sysrc vboxservice_enable="YES" ; service vboxservice start || true
   # ------ vSphere ---------------------------------------------------------
   elif [ "${HYPERVISOR}" == "vmware" ] ; then
      if [ -e /usr/lib/systemd/system/sddm.service ] ; then
         # System has X11 -> also install X11 utilities as well:
         pkg install -y open-vm-tools
      else
         pkg install -y open-vm-tools-nox11
      fi
      sysrc vmware_guestd_enable="YES" ; service vmware-guestd start || true
   # ------ QEMU ------------------------------------------------------------
   elif [[ "${HYPERVISOR}" =~ " kvm " ]] ; then
      pkg install -y qemu-guest-agent
      sysrc qemu_guest_agent_enable="YES" ; service qemu-guest-agent start || true
   fi

   # ------ Not in QEMU -> remove qemu-guest-agent --------------------------
   if [[ ! "${HYPERVISOR}" =~ " kvm " ]] || [[ "${HYPERVISOR}" =~ " virtualbox " ]] ; then
      # NOTE: qemu-guest-agent may have been installed as part of the
      #       initial setup, since e.g. the Proxmox builder expects it!
      pkg remove -y qemu-guest-agent || true
      sysrc -x qemu_guest_agent_enable || true
   fi


# ------ NetBSD -------------------------------------------------------------
elif [ "${ID}" == "netbsd" ] ; then

   # ------ VirtualBox ------------------------------------------------------
   if [[ "${HYPERVISOR}" =~ " virtualbox " ]] ; then
      # There are no VirtualBox Guest Utils for NetBSD, yet.
      true
   # ------ vSphere ---------------------------------------------------------
   elif [ "${HYPERVISOR}" == "vmware" ] ; then
      pkgin -y install open-vm-tools
      cp /usr/pkg/share/examples/rc.d/vmtools /etc/rc.d/
      if grep -q "^vmtools=" /etc/rc.conf ; then
         sed -i 's/^vmtools=.*/vmtools="YES"/' /etc/rc.conf
      else
         echo 'vmtools="YES"' >>/etc/rc.conf
      fi
      service vmtools start || true
   # ------ QEMU ------------------------------------------------------------
   elif [[ "${HYPERVISOR}" =~ " kvm " ]] ; then
      pkgin -y install qemu-guest-agent
      cp /usr/pkg/share/examples/rc.d/qemu-guest-agent /etc/rc.d/
      if grep -q "^qemu_guest_agent=" /etc/rc.conf ; then
         sed -i 's/^qemu_guest_agent=.*/qemu_guest_agent="YES"/' /etc/rc.conf
      else
         echo 'qemu_guest_agent="YES"' >>/etc/rc.conf
      fi
      service qemu-guest-agent start || true
   fi

   # ------ Not in QEMU -> remove qemu-guest-agent --------------------------
   if [[ ! "${HYPERVISOR}" =~ " kvm " ]] || [[ "${HYPERVISOR}" =~ " virtualbox " ]] ; then
      # NOTE: qemu-guest-agent may have been installed as part of the
      #       initial setup, since e.g. the Proxmox builder expects it!
      pkgin -y remove qemu-guest-agent || true
      sed -i '/^qemu_guest_agent=.*/d' /etc/rc.conf
   fi


# ------ OpenBSD ------------------------------------------------------------
elif [ "${ID}" == "openbsd" ] ; then

   # ------ VirtualBox ------------------------------------------------------
   if [[ "${HYPERVISOR}" =~ " virtualbox " ]] ; then
      # There are no VirtualBox Guest Utils for OpenBSD, yet.
      true
   # ------ vSphere ---------------------------------------------------------
   elif [ "${HYPERVISOR}" == "vmware" ] ; then
      # There are no Open VM Tools for OpenBSD, yet.
      true
   # ------ QEMU ------------------------------------------------------------
   elif [[ "${HYPERVISOR}" =~ " kvm " ]] ; then
      pkg_add -r -I qemu-ga
      # Guest agent has to use ISA serial port:
      # https://openports.pl/path/emulators/qemu,-ga
      rcctl set qemu_ga flags "-m isa-serial -p /dev/cua00"
      rcctl enable qemu_ga
      rcctl start qemu_ga || true
   fi

   # ------ Not in QEMU -> remove qemu-guest-agent --------------------------
   if [[ ! "${HYPERVISOR}" =~ " kvm " ]] || [[ "${HYPERVISOR}" =~ " virtualbox " ]] ; then
      pkg_delete qemu-ga || true
   fi


# ------ Solaris ------------------------------------------------------------
elif [ "${ID}" == "sunos" ] ; then

   # NOTE: virt-what is not available, HYPERVISOR is empty!

   # ------ VirtualBox ------------------------------------------------------
   if ! prtconf -vp | grep -qE "pci80ee" ; then
      pkg install virtualbox-additions || [ $? -eq 4 ]

   # ------ QEMU ------------------------------------------------------------
   elif ! prtdiag | grep -qE "pci1af4,3|isa|asy" ; then
      # See https://gist.github.com/jimklimov/b79ef519add34af96e1fcc59de58165c
      pkg install qemu || [ $? -eq 4 ]
   fi

# ------ Unknown ------------------------------------------------------------
else

   echo >&2 "ERROR: Unknown ID ${ID} in /etc/os-release. The installation script may need an update for supporting this system!"
   exit 1

fi


# ====== Fix for multipathd error messages ==================================
if [ "${UNAME}" == "Linux" ] ; then
   cat <<EOF | tee -a /etc/multipath.conf

blacklist {
devnode "^sd[a-z]"
}
EOF
fi
