#!/usr/bin/env bash
# ==========================================================================
#  ___         _        _ _      _   _            ___         _      _
# |_ _|_ _  __| |_ __ _| | |__ _| |_(_)___ _ _   / __| __ _ _(_)_ __| |_ ___
#  | || ' \(_-<  _/ _` | | / _` |  _| / _ \ ' \  \__ \/ _| '_| | '_ \  _(_-<
# |___|_||_/__/\__\__,_|_|_\__,_|\__|_\___/_||_| |___/\__|_| |_| .__/\__/__/
#                                                              |_|
#
#   --- Virtual Machine Image Builder and System Installation Scripts ---
#            https://www.nntb.no/~dreibh/vmimage-builder-scripts/
# ==========================================================================
#
# System Installation Scripts
# Copyright (C) 2017-2026 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

# Bash options:
set -euo pipefail


# ###### Print script name, to make Packer output easier readable ###########
if command -v figlet >/dev/null && command -v print-utf8 >/dev/null ; then
   echo
   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;36m█" "▀" "█\e[0m"
   figlet -w 156 "$(basename "$0")" | LC_ALL=C.UTF-8 print-utf8 -x 160 -n -C "\e[1;36m█\e[22m" "\e[1;36m█\e[0m"
   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;36m█" "▄" "█\e[0m"
else
   echo -e "\e[1;34;22m########## $(basename "$0") ##########\e[0m"
fi

# Enable printing the command-lines executed:
set -x


# ###### Main program #######################################################

# ====== Check/set environment variables ====================================
if [ ! -v USER_NAME ] || [ "${USER_NAME}" == "" ] ; then
   echo >&2 "Usage: env USER_NAME=<user> $0"
   echo >&2 "Example: sudo env USER_NAME=nornetpp $0"
   exit 1
fi
USER_HOME="$(getent passwd "${USER_NAME}" | cut -d: -f6 || awk -F: -v user="${USER_NAME}" '$1==user { print $6 }' /etc/passwd)"


# ====== Configuration ======================================================
DESKTOP_DIRECTORY="${USER_HOME}/Desktop"

# Directories to be directoryed
DIRECTORIES="
   /
   ${USER_HOME}
"

# Applications to be directoryed:
APPLICATIONS="
   clementine
   dbeaver
   dia
   firefox
   firefox-esr
   fractgen
   gimp
   kfractgen
   libreoffice-startcenter
   org.gnome.Dia
   org.inkscape.Inkscape
   org.kde.kate
   org.kde.kile
   org.kde.konsole
   org.kde.okteta
   org.kde.okular
   org.mozilla.firefox
   org.strawberrymusicplayer.strawberry
   org.wireshark.Wireshark
   R
   io.dbeaver.DBeaverCommunity
   dbeaver-ce_dbeaver-ce
"


# ====== Create Desktop directory ===========================================
sudo -u "${USER_NAME}" mkdir -p "${DESKTOP_DIRECTORY}"


# ====== Create links for directories =======================================
for directory in ${DIRECTORIES} ; do
   basename=$(basename "${directory}")
   if [ "${basename}" == "/" ] ; then
      basename="root"
   fi
   if [ ! -e "${DESKTOP_DIRECTORY}/${basename}" ] ; then
      echo "Creating desktop link for directory ${directory} as ${basename} ..."
      sudo -u "${USER_NAME}" ln -s "${directory}" "${DESKTOP_DIRECTORY}/${basename}"
   fi
done


# ====== Create directorys for applications =================================
for application in ${APPLICATIONS} ; do
   found=0
   for source in /usr/share/applications /usr/local/share/applications /var/lib/snapd/desktop/applications /var/lib/flatpak/exports/share/applications ; do
      if [ -e "${source}/${application}.desktop" ] ; then
         found=1
         echo "FOUND: ${application} -> ${source}/${application}.desktop"
         if [ ! -e "${DESKTOP_DIRECTORY}/${application}.desktop" ] ; then
            echo "Creating desktop link for application ${application} (in ${source}) ..."
            sudo -u "${USER_NAME}" ln -s "${source}/${application}.desktop" "${DESKTOP_DIRECTORY}/" || true
            break
         fi
      fi
   done
   if [ ${found} -eq 0 ] ; then
      echo "NOT FOUND: ${application}"
   fi
done
