#!/usr/bin/env bash
# ==========================================================================
#  ___         _        _ _      _   _            ___         _      _
# |_ _|_ _  __| |_ __ _| | |__ _| |_(_)___ _ _   / __| __ _ _(_)_ __| |_ ___
#  | || ' \(_-<  _/ _` | | / _` |  _| / _ \ ' \  \__ \/ _| '_| | '_ \  _(_-<
# |___|_||_/__/\__\__,_|_|_\__,_|\__|_\___/_||_| |___/\__|_| |_| .__/\__/__/
#                                                              |_|
#
#   --- Virtual Machine Image Builder and System Installation Scripts ---
#            https://www.nntb.no/~dreibh/vmimage-builder-scripts/
# ==========================================================================
#
# System Installation Scripts
# Copyright (C) 2017-2026 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

# Bash options:
set -euo pipefail


# ###### Main program #######################################################

# ====== Print script name, to make Packer output easier readable ===========
SCRIPT="93-language-packs"   # Set to "$(basename "$0")" of this file!
if command -v figlet >/dev/null && command -v print-utf8 >/dev/null ; then
   echo
   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;31m█" "▀" "█\e[0m"
   figlet -w 156 "${SCRIPT}" | LC_ALL=C.UTF-8 print-utf8 -x 160 -n -C "\e[1;31m█\e[22m" "\e[1;31m█\e[0m"
   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;31m█" "▄" "█\e[0m"
else
   echo -e "\e[1;31;22m########## ${SCRIPT} ##########\e[0m"
fi

# ====== Check/set environment variables ====================================
if [ ! -v LOCALES ] || [ "${LOCALES}" == "" ] ; then
   echo >&2 "Usage: env LOCALES=\"locales,...\" $0"
   echo >&2 "Example: sudo env LOCALES=\"de_DE en_IE en_US nb_NO\" $0"
   exit 1
fi

# Enable printing the command-lines executed:
set -x

# ====== Obtain system details ==============================================
UNAME="$(uname)"
NAME="${UNAME}"
ID="${UNAME,,}"
VERSION="$(uname -r)"
VERSION_ID="${VERSION/_*/}"
if [ -f /etc/os-release ] ; then
   . /etc/os-release
fi


# ====== Package installation ===============================================

# ------ Ubuntu/Debian ------------------------------------------------------
if [ "${ID}" == "ubuntu" ] || [ "${ID}" == "debian" ] ; then

   packages=()

   # ------ Ubuntu ----------------------------------------------------------
   # Ubuntu has its tool "check-language-support":
   if [ "${ID}" == "ubuntu" ] ; then
      env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
         language-selector-common

      # ------ Generate list of packages to be installed --------------------
      for locale in ${LOCALES} ; do
         language="${locale%%_*}"
         read -r -a packagesToAdd < <(check-language-support -l "${language}")
         if [ "${#packagesToAdd[@]}" -ne 0 ] ; then
            packages+=( "${packagesToAdd[@]}" )
         fi
      done

   # ------ Debian uses tasks to manage language support --------------------
   else
      env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
         tasksel-data

      # ------ Determinate whether the system has a GUI ---------------------
      isDesktop=0
      if systemctl is-enabled -q sddm.service ; then
         isDesktop=1
      fi

      # ------ Read the Debian language support information into an array ---
      set +x

      declare -A languageSupportMap
      while read -r line; do
         if [[ $line =~ ^Task:\ (.*) ]] ; then
            currentTask="${BASH_REMATCH[1]}"
         elif [[ $line =~ ^Test-lang:\ (.*) ]] ; then
            currentLanguages="${BASH_REMATCH[1]}"
            for currentLanguage in  ${currentLanguages} ; do
               languageSupportMap["${currentLanguage}"]="${currentTask}"
            done
         fi
      done </usr/share/tasksel/descs/debian-tasks.desc

      # ------ Generate list of packages to be installed --------------------
      for locale in ${LOCALES} ; do
         languageCode="${locale%%_*}"
         if [[ -v languageSupportMap["${languageCode}"] ]] ; then
            taskName="${languageSupportMap[${languageCode}]}"
            if [ -n "${taskName}" ]; then
               if apt-cache show "task-${taskName}" >/dev/null 2>&1 ; then
                  packages+=( "task-${taskName}" )
               fi
               if [ ${isDesktop} -ne 0 ] ; then
                  if apt-cache show "task-${taskName}-desktop" >/dev/null 2>&1 ; then
                     packages+=( "task-${taskName}-desktop" )
                  fi
                  if apt-cache show "task-${taskName}-kde-desktop" >/dev/null 2>&1 ; then
                     packages+=( "task-${taskName}-kde-desktop" )
                  fi
               fi
            fi
         else
            echo >&2 "WARNING: No package for language ${languageCode}!"
         fi
      done

      set -x
   fi

   # ------ Install packages ------------------------------------------------
   if [ "${#packages[@]}" -gt 0 ] ; then
      env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
         "${packages[@]}"
   fi

   # Apply the user's setting, instead of using the installation default:
   rm -f /etc/default/locale

# ------ Fedora -------------------------------------------------------------
elif [ "${ID}" == "fedora" ] ; then

   packages=()

   # ------ Determinate whether the system has a GUI ------------------------
   isDesktop=0
   if systemctl is-enabled -q sddm.service ; then
      isDesktop=1
   fi

   # ------ Generate list of packages to be installed -----------------------
   for locale in ${LOCALES} ; do
      languageCode="${locale%%_*}"
      packages+=( "glibc-langpack-${languageCode}" )
      if [ ${isDesktop} -ne 0 ] ; then
         packages+=( "langpacks-${languageCode}" )
      fi
   done

   # ------ Install packages ------------------------------------------------
   if [ "${#packages[@]}" -gt 0 ] ; then
      dnf install --setopt=install_weak_deps=False -y "${packages[@]}"
   fi

# ------ OpenSUSE -----------------------------------------------------------
elif [[ "${ID}" =~ ^opensuse- ]] ; then

   # ------ Generate and process the locales --------------------------------
   for locale in ${LOCALES} ; do
      languageCode="${locale%%_*}"
      zypper --non-interactive addlocale "${locale}"
   done

   # ------ Trigger installation of individual missing *-lang packages ------
   zypper --non-interactive install-new-recommends --no-recommends

# ------ Alpine -------------------------------------------------------------
elif [ "${ID}" == "alpine" ] ; then

   # Collect *-lang packages of installed packages:
   mapfile -t packages < <(apk info -q | grep -v '\-lang$' | sed 's/$/-lang/' | xargs apk search -q 2>/dev/null)

   # ------ Install packages ------------------------------------------------
   if [ "${#packages[@]}" -gt 0 ] ; then
      apk add "${packages[@]}"
   fi

# ------ FreeBSD, NetBSD, OpenBSD -------------------------------------------
elif [ "${UNAME}" == "FreeBSD" ] ||
     [ "${UNAME}" == "NetBSD"  ] ||
     [ "${UNAME}" == "OpenBSD" ] ||
     [ "${UNAME}" == "SunOS"   ] ; then

   # The language support should already be there!
   true

# ------ Unknown ------------------------------------------------------------
else

   echo >&2 "ERROR: Unknown ID ${ID} in /etc/os-release. The installation script may need an update for supporting this system!"
   exit 1

fi
