#!/usr/bin/env bash
# ==========================================================================
#  ___         _        _ _      _   _            ___         _      _
# |_ _|_ _  __| |_ __ _| | |__ _| |_(_)___ _ _   / __| __ _ _(_)_ __| |_ ___
#  | || ' \(_-<  _/ _` | | / _` |  _| / _ \ ' \  \__ \/ _| '_| | '_ \  _(_-<
# |___|_||_/__/\__\__,_|_|_\__,_|\__|_\___/_||_| |___/\__|_| |_| .__/\__/__/
#                                                              |_|
#
#   --- Virtual Machine Image Builder and System Installation Scripts ---
#            https://www.nntb.no/~dreibh/vmimage-builder-scripts/
# ==========================================================================
#
# System Installation Scripts
# Copyright (C) 2017-2026 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

# Bash options:
set -euo pipefail


# ###### Print script name, to make Packer output easier readable ###########
SCRIPT="95-popularity-contest"   # Set to "$(basename "$0")" of this file!
if command -v figlet >/dev/null && command -v print-utf8 >/dev/null ; then
   echo
   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;31m█" "▀" "█\e[0m"
   figlet -w 156 "${SCRIPT}" | LC_ALL=C.UTF-8 print-utf8 -x 160 -n -C "\e[1;31m█\e[22m" "\e[1;31m█\e[0m"
   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;31m█" "▄" "█\e[0m"
else
   echo -e "\e[1;31;22m########## ${SCRIPT} ##########\e[0m"
fi

# Enable printing the command-lines executed:
set -x


# ###### Main program #######################################################

# ====== Obtain system details ==============================================
UNAME="$(uname)"
NAME="${UNAME}"
ID="${UNAME,,}"
VERSION="$(uname -r)"
VERSION_ID="${VERSION/_*/}"
if [ -f /etc/os-release ] ; then
   . /etc/os-release
fi


# ====== Configuration ======================================================

# ------ Debian/Ubuntu ------------------------------------------------------
if [ "${ID}" == "debian" ] || [ "${ID}" == "ubuntu" ] ; then
   env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      popularity-contest
   sed -e 's/^PARTICIPATE="no"/PARTICIPATE="yes"/' -i /etc/popularity-contest.conf
   sed -e '/^SUBMITURLS=""/d' -e 's/^#SUBMITURLS=/SUBMITURLS=/' -i /usr/share/popularity-contest/default.conf
   /etc/cron.daily/popularity-contest
fi
