#!/usr/bin/env bash
#
# Autoinstall Scripts
# Copyright (C) 2017-2024 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

# Bash options:
set -exu


# ====== Check/set environment variables ====================================
if [ ! -e /etc/os-release ] ; then
   echo >&2 "ERROR: /etc/os-release does not exist!"
   exit 1
fi
. /etc/os-release


# ====== Package installation ===============================================

# ------ Ubuntu/Debian ------------------------------------------------------
if [ "${ID}" == "ubuntu" ] || [ "${ID}" == "debian" ] ; then

   # Ensure that "unattended-upgrades" is active and handles the PPAs:
   if [ "${ID}" == "ubuntu" ] ; then
      # Ubuntu:
      # shellcheck disable=SC2016
      sed -e 's#^//\([ \t]*"${distro_id}:${distro_codename}-updates";\)#  \1\n\t"LP-PPA-dreibh:${distro_codename}";\n\t"LP-PPA-mozillateam:${distro_codename}";\n\t"Zabbix:${distro_codename}";#' \
         </etc/apt/apt.conf.d/50unattended-upgrades | tee /etc/apt/apt.conf.d//50unattended-upgrades.new >/dev/null
   else
      # Debian:
      # shellcheck disable=SC2016
      sed -e 's#^//\([ \t]*"origin=.*,codename=${distro_codename}-updates";\)#  \1\n\t"origin=Zabbix,codename=${distro_codename}";#' \
         </etc/apt/apt.conf.d/50unattended-upgrades | tee /etc/apt/apt.conf.d//50unattended-upgrades.new >/dev/null
   fi

   diff --color /etc/apt/apt.conf.d/50unattended-upgrades /etc/apt/apt.conf.d//50unattended-upgrades.new || true
   mv /etc/apt/apt.conf.d//50unattended-upgrades.new /etc/apt/apt.conf.d/50unattended-upgrades

   # Run now:
   unattended-upgrade --verbose || true

# ------ Fedora -------------------------------------------------------------
elif [ "${ID}" == "fedora" ] ; then

   if [ -e /usr/share/dnf5/dnf5-plugins/automatic.conf ] ; then
      cp /usr/share/dnf5/dnf5-plugins/automatic.conf /etc/dnf/automatic.conf
   fi
   sed -e 's/^apply_updates = no/apply_updates = yes/' -i /etc/dnf/automatic.conf

   # Ensure that "dnf-automatic" timer is active for downloading and installing updates:
   systemctl enable --now dnf-automatic-install.timer || true   # FIXME: legacy name?
   systemctl enable --now dnf5-automatic.timer || true

   # Run now:
   systemctl start dnf-automatic-install.service || true   # FIXME: legacy name?
   systemctl start dnf-automatic.service || true

# ------ FreeBSD ------------------------------------------------------------
elif [ "${ID}" == "freebsd" ] ; then

   true    # FIXME: TDB!

# ------ Unknown ------------------------------------------------------------
else

   echo >&2 "ERROR: Unknown ID ${ID} in /etc/os-release. The installation script may need an update for supporting this system!"
   exit 1

fi
