#!/usr/bin/env bash
#
# Autoinstall Scripts
# Copyright (C) 2017-2025 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

# Bash options:
set -eux


# ====== Check/set environment variables ====================================
if [ ! -e /etc/os-release ] ; then
   echo >&2 "ERROR: /etc/os-release does not exist!"
   exit 1
fi
. /etc/os-release
UNAME="$(uname)"


# ====== Reset machine identity =============================================
if [ -e /etc/machine-id ] ; then
   # Ensure to create a new machine ID on the next boot.
   # The machine ID is used e.g. as DHCP Identifier, it must be unique to
   # avoid assigning the same IP address to multiple VMs!
   echo -n | sudo tee /etc/machine-id
   if [ -e /var/lib/dbus/machine-id ] ; then
      sudo rm /var/lib/dbus/machine-id
      sudo ln -s /etc/machine-id /var/lib/dbus/machine-id
   fi
fi


# ====== Clean up packages  =================================================

# ------ Ubuntu -------------------------------------------------------------
if [ "${ID}" == "ubuntu" ] || [ "${ID}" == "debian" ] ; then

   /usr/bin/apt-get update
   env DEBIAN_FRONTEND=noninteractive NEEDRESTART_MODE=l /usr/bin/apt-get dist-upgrade -y
   if [ "${ID}" == "ubuntu" ] ; then
      dhcpcd || true   # FIXME: Work-around for stopped networking in Ubuntu 24.04
   fi
   env DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get autoremove -y --purge
   if [ -x /usr/bin/apt-file ] ; then
      /usr/bin/apt-file update
   fi
   if [ -x /usr/bin/apt-show-versions ] ; then
      /usr/bin/apt-show-versions -i
   fi
   /usr/bin/apt-get clean

# ------ Fedora -------------------------------------------------------------
elif [ "${ID}" == "fedora" ] ; then

   /usr/bin/dnf clean all

# ------ FreeBSD ------------------------------------------------------------
elif [ "${ID}" == "freebsd" ] ; then

   /usr/sbin/pkg upgrade -y
   /usr/sbin/pkg clean -y

# ------ Unknown ------------------------------------------------------------
else

   echo >&2 "ERROR: Unknown ID ${ID} in /etc/os-release. The installation script may need an update for supporting this system!"
   exit 1

fi


# ====== Update "locate" database ===========================================
if [ "${UNAME}" == "Linux" ] ; then
   if [ -x /usr/bin/updatedb ] ; then
      /usr/bin/updatedb
   fi
elif [ "${UNAME}" == "FreeBSD" ] ; then
   /etc/periodic/weekly/310.locate
fi


# ====== Run fstrim =========================================================
if [ "${UNAME}" == "Linux" ] ; then
   if [ -x /usr/bin/fstrim ] ; then
      /usr/bin/fstrim -av || true
   fi
elif [ "${UNAME}" == "FreeBSD" ] ; then
   sudo zpool trim zroot
fi


# ====== Run sync ===========================================================
# Just to be sure all data is synced to disk.
# FreeBSD in VirtualBox cannot be shut down cleanly, due a bug!
sync
sync
sync
