#!/usr/bin/env bash
# ==========================================================================
#  ___         _        _ _      _   _            ___         _      _
# |_ _|_ _  __| |_ __ _| | |__ _| |_(_)___ _ _   / __| __ _ _(_)_ __| |_ ___
#  | || ' \(_-<  _/ _` | | / _` |  _| / _ \ ' \  \__ \/ _| '_| | '_ \  _(_-<
# |___|_||_/__/\__\__,_|_|_\__,_|\__|_\___/_||_| |___/\__|_| |_| .__/\__/__/
#                                                              |_|
#
#   --- Virtual Machine Image Builder and System Installation Scripts ---
#            https://www.nntb.no/~dreibh/vmimage-builder-scripts/
# ==========================================================================
#
# System Installation Scripts
# Copyright (C) 2017-2026 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

# Bash options:
set -euo pipefail


# ###### Print script name, to make Packer output easier readable ###########
if command -v figlet >/dev/null && command -v print-utf8 >/dev/null ; then
   echo
   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;36m█" "▀" "█\e[0m"
   figlet -w 156 "$(basename "$0")" | LC_ALL=C.UTF-8 print-utf8 -x 160 -n -C "\e[1;36m█\e[22m" "\e[1;36m█\e[0m"
   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;36m█" "▄" "█\e[0m"
else
   echo -e "\e[1;34;22m########## $(basename "$0") ##########\e[0m"
fi

# Enable printing the command-lines executed:
set -x


# ###### Main program #######################################################

# ====== Obtain system details ==============================================
UNAME="$(uname)"
NAME="${UNAME}"
ID="${UNAME,,}"
VERSION="$(uname -r)"
VERSION_ID="${VERSION/_*/}"
if [ -f /etc/os-release ] ; then
   . /etc/os-release
fi


# ====== Clean up the temporary directory (created in 01-system-settings) ===
rm -rf /tmp/installtmp


# ====== Reset machine identity =============================================
if [ -e /etc/machine-id ] ; then
   # Ensure to create a new machine ID on the next boot.
   # The machine ID is used e.g. as DHCP Identifier, it must be unique to
   # avoid assigning the same IP address to multiple VMs!
   echo -n | sudo tee /etc/machine-id
   if [ -e /var/lib/dbus/machine-id ] ; then
      if [ -e /var/lib/dbus/machine-id ] ; then
         rm -f /var/lib/dbus/machine-id
      fi
      sudo ln -s /etc/machine-id /var/lib/dbus/machine-id
   fi
fi


# ====== Clean up packages  =================================================

# ------ Ubuntu/Debian ------------------------------------------------------
if [ "${ID}" == "ubuntu" ] || [ "${ID}" == "debian" ] ; then

   apt-get update
   env DEBIAN_FRONTEND=noninteractive NEEDRESTART_MODE=l apt-get dist-upgrade -y
   env DEBIAN_FRONTEND=noninteractive apt-get autoremove -y --purge
   if command -v apt-file 2>/dev/null ; then
      apt-file update
   fi
   if command -v apt-show-versions 2>/dev/null ; then
      apt-show-versions -i
   fi
   apt-get clean

# ------ Fedora -------------------------------------------------------------
elif [ "${ID}" == "fedora" ] ; then

   dnf upgrade -y
   dnf clean all

# ------ OpenSUSE -----------------------------------------------------------
elif [[ "${ID}" =~ ^opensuse- ]] ; then

   zypper --non-interactive --gpg-auto-import-keys dist-upgrade -y
   zypper clean --all

# ------ Alpine -------------------------------------------------------------
elif [ "${ID}" == "alpine" ] ; then

   apk upgrade
   apk cache clean

# ------ FreeBSD ------------------------------------------------------------
elif [ "${ID}" == "freebsd" ] ; then

   pkg upgrade -y
   pkg clean -y

# ------ NetBSD -------------------------------------------------------------
elif [ "${ID}" == "netbsd" ] ; then

   pkgin -y upgrade
   pkgin clean

# ------ OpenBSD ------------------------------------------------------------
elif [ "${ID}" == "openbsd" ] ; then

   syspatch
   pkg_add -u

# ------ Unknown ------------------------------------------------------------
else

   echo >&2 "ERROR: Unknown ID ${ID} in /etc/os-release. The installation script may need an update for supporting this system!"
   exit 1

fi


# ====== Update "locate" database ===========================================
if [ "${UNAME}" == "Linux" ] ; then
   if command -v updatedb 2>/dev/null ; then
      updatedb
   fi
elif [ "${UNAME}" == "FreeBSD" ] ; then
   /etc/periodic/weekly/310.locate
elif [ "${UNAME}" == "NetBSD" ] || [ "${UNAME}" == "OpenBSD" ] ; then
   /usr/libexec/locate.updatedb
fi


# ====== Run fstrim =========================================================
if [ "${UNAME}" == "Linux" ] ; then
   if [ "${ID}" == "fedora" ] ; then
      true   # FIXME! Temporary work-around for Fedora installation issue!
   else
      if command -v fstrim 2>/dev/null ; then
         fstrim -av || true
      fi
   fi
elif [ "${UNAME}" == "FreeBSD" ] ; then
   sudo zpool trim zroot
fi


# ====== Run sync ===========================================================
# Just to be sure all data is synced to disk.
# FreeBSD in VirtualBox cannot be shut down cleanly, due a bug!
sync
sync
sync
