#!/usr/bin/env bash
#
# Autoinstall Scripts
# Copyright (C) 2017-2024 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

# Bash options:
set -ex


UNAME="$(uname)"


# ====== Clean up packages  =================================================

if [ "${UNAME}" == "Linux" ] ; then
   # ------ Ubuntu ----------------------------------------------------------
   if [ -x /usr/bin/apt-get ] ; then
      env DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get dist-upgrade -y
      env DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get autoremove -y --purge
      if [ -x /usr/bin/apt-file ] ; then
         /usr/bin/apt-file update
      fi
      if [ -x /usr/bin/apt-show-versions ] ; then
         /usr/bin/apt-show-versions -i
      fi
      /usr/bin/apt-get clean

   # ------ Fedora ----------------------------------------------------------
   elif [ -x /usr/bin/dnf ] ; then
      /usr/bin/dnf clean all
   fi
fi


# ====== Update "locate" database ===========================================
if [ "${UNAME}" == "Linux" ] ; then
   if [ -x /usr/bin/updatedb ] ; then
      /usr/bin/updatedb
   fi
elif [ "${UNAME}" == "FreeBSD" ] ; then
   /etc/periodic/weekly/310.locate
fi


# ====== Run fstrim =========================================================
if [ "${UNAME}" == "Linux" ] ; then
   if [ -x /usr/bin/fstrim ] ; then
      /usr/bin/fstrim -av
   fi
elif [ "${UNAME}" == "FreeBSD" ] ; then
   sudo zpool trim zroot
fi
