#!/usr/bin/env bash
#
# Autoinstall Scripts
# Copyright (C) 2017-2024 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

# Bash options:
set -ex


UNAME="$(uname)"
HYPERVISOR=" $(virt-what | xargs) "


if [ "${UNAME}" == "Linux" ] ; then
   # ====== Ubuntu/Debian Linux =============================================
   if [ -e /usr/bin/apt-get ] ; then
      /usr/bin/apt-get update

      # ------ VirtualBox ---------------------------------------------------
      if [[ "${HYPERVISOR}" =~ " virtualbox " ]] ; then
         env DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get install -y \
            virtualbox-guest-utils virtualbox-guest-dkms || true
         if [ -e /usr/lib/systemd/system/sddm.service ] ; then
            # System has X11 -> also install X11 utilities as well:
            env DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get install -y \
               virtualbox-guest-x11 || true
         fi
      # ------ vSphere ------------------------------------------------------
      elif [[ "${HYPERVISOR}" =~ " vmware " ]] ; then
         env DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get install -y \
            open-vm-tools
         if [ -e /usr/lib/systemd/system/sddm.service ] ; then
            # System has X11 -> also install X11 utilities as well:
            env DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get install -y \
               open-vm-tools-desktop || true
         fi
      # ------ QEMU ---------------------------------------------------------
      elif [[ "${HYPERVISOR}" =~ " kvm " ]] ; then
         env DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get install -y \
            qemu-guest-agent
      fi

   # ====== Fedora Linux ====================================================
   elif [ -e /usr/bin/dnf ] ; then

      # ------ VirtualBox ---------------------------------------------------
      if [[ "${HYPERVISOR}" =~ " virtualbox " ]] ; then
         /usr/bin/dnf install -y virtualbox-guest-additions
      # ------ vSphere ------------------------------------------------------
      elif [ "${HYPERVISOR}" == "vmware" ] ; then
         /usr/bin/dnf install -y open-vm-tools
         if [ -e /usr/lib/systemd/system/sddm.service ] ; then
            # System has X11 -> also install X11 utilities as well:
            /usr/bin/dnf install -y open-vm-tools-desktop
         fi
      # ------ QEMU ---------------------------------------------------------
      elif [[ "${HYPERVISOR}" =~ " kvm " ]] ; then
         env DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get install -y \
            qemu-guest-agent
      fi
   fi

   # ====== Fix for multipathd error messages ===============================
   cat <<EOF | tee -a /etc/multipath.conf

blacklist {
  devnode "^sd[a-z]"
}
EOF

# ====== FreeBSD ============================================================
elif [ "${UNAME}" == "FreeBSD" ] ; then

   # ------ VirtualBox ------------------------------------------------------
   if [[ "${HYPERVISOR}" =~ " virtualbox " ]] ; then
      /usr/bin/dnf install -y virtualbox-guest-additions
   # ------ vSphere ---------------------------------------------------------
   elif [ "${HYPERVISOR}" == "vmware" ] ; then
      /usr/bin/dnf install -y open-vm-tools
      if [ -e /usr/lib/systemd/system/sddm.service ] ; then
         # System has X11 -> also install X11 utilities as well:
         /usr/bin/dnf install -y open-vm-tools-desktop
      fi
   # ------ QEMU ------------------------------------------------------------
   elif [[ "${HYPERVISOR}" =~ " kvm " ]] ; then
      /usr/sbin/pkg install -y qemu-guest-agent
      sysrc qemu_guest_agent_enable="YES" ; service qemu-guest-agent start || true
   elif [[ ! "${HYPERVISOR}" =~ " kvm " ]] ; then
      /usr/sbin/pkg remove -y qemu-guest-agent || true
   fi

fi
