#!/usr/bin/env bash
#
# Autoinstall Scripts
# Copyright (C) 2017-2020 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

# Bash options:
set -ex


# ====== Install MPTCP kernel ===============================================

# ------ Ubuntu -------------------------------------------------------------
if [ -e /usr/bin/apt-get ] ; then
   /usr/bin/apt-get update

   mptcpKernelImagePackage=`apt-cache search mptcp | cut -d' ' -f1 | grep "^linux-image" | grep -- '-mptcp$' | sort --version-sort --field-separator=- -r | head -n1`
   mptcpKernelHeaderPackage=`echo "${mptcpKernelImagePackage}" | sed -e "s/-image-/-header-/g"`

   echo "MPTCP kernel image package:  ${mptcpKernelImagePackage}"
   echo "MPTCP kernel header package: ${mptcpKernelHeaderPackage}"


   env DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get install -y ${mptcpKernelImagePackage} ${mptcpKernelHeaderPackage}

# ------ Fedora -------------------------------------------------------------
elif [ -e /usr/bin/dnf ] ; then

   true   # TDB!

fi
