#!/usr/bin/env bash
#
# Autoinstall Scripts
# Copyright (C) 2017-2024 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

# Bash options:
set -ex


# ###########################################################################
# The "KDE" installation must contain the following packages:
# - The KDE Plasma Desktop with Oxygen theme and SDDM
# - Dia
# - Firefox
# - FractGen
# - LibreOffice
# - Gimp
# - Kate
# - Kile
# - Konsole
# - Okular
# - R
# - Wireshark
# ###########################################################################


# ====== NorNet Desktop package installation ================================

# ------ Ubuntu -------------------------------------------------------------
if [ -e /usr/bin/apt-get ] ; then

   packages="
      dia
      fractgen
      kde-plasma-desktop
      gimp
      kate
      kile
      konsole
      libreoffice
      okular
      plasma-theme-oxygen
      sddm
      wireshark
   "

   if [ -e /etc/os-release ] ; then
      . /etc/os-release

      # ------ Distribution-specific KDE meta package -----------------------
      # if [ "${ID}" == "debian" ] ; then
      #    # See also: https://wiki.debian.org/KDE
      #    packages="${packages} kde-standard"
      # else
      #    packages="${packages} kubuntu-desktop"
      # fi

      # ------ Add Firefox package ------------------------------------------
      if [ "${ID}" == "debian" ] ; then
         # Debian: firefox-esr instead of firefox!
         packages="${packages} firefox-esr"
      else
         packages="${packages} firefox"
      fi

      # ------ Ubuntu: Get Firefox from PPA, not via Snap -------------------
      if [ "${ID}" == "ubuntu" ] ; then
         # shellcheck disable=SC2072
         if [[ "${VERSION_ID}" > "21.10" ]] ; then
            cat >/etc/apt/preferences.d/firefox.pref <<EOF
# Use Firefox from PPA, instead of installing it via Snap!
Package: firefox
Pin: release o=LP-PPA-mozillateam
Pin-Priority: 1024
EOF
            sudo add-apt-repository -sy ppa:mozillateam/ppa
         fi
      fi
   fi

   # shellcheck disable=SC2086
   env DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get install -y ${packages}

# ------ Fedora -------------------------------------------------------------
elif [ -e /usr/bin/dnf ] ; then
   /usr/bin/dnf install -y sddm @KDE qt5-style-oxygen oxygen-gtk2 plasma-oxygen oxygen-icon-theme oxygen-cursor-themes oxygen-sound-theme oxygen-fonts firefox

   systemctl enable sddm.service
   systemctl start sddm.service
   systemctl set-default graphical.target

# ------ FreeBSD ------------------------------------------------------------
elif [ -e /usr/sbin/pkg ] ; then
   /usr/sbin/pkg install -y firefox-esr jq kde5 noto oxygen-fonts plasma5-oxygen plasma5-sddm-kcm sddm xf86-video-vmware xorg

   sysrc dbus_enable="YES" ; service dbus start || true
   sysrc sddm_enable="YES" ; service sddm start || true


   /usr/sbin/pkg install -y R dia fractgen gimp kile libreoffice wireshark
fi
