#!/usr/bin/env bash
#
# Autoinstall Scripts
# Copyright (C) 2017-2024 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

# Bash options:
set -ex


# ====== NorNet Desktop package installation ================================

# ------ Ubuntu -------------------------------------------------------------
if [ -e /usr/bin/apt-get ] ; then

   packages="
      dia
      fractgen
      gimp
      kate
      kile
      konsole
      libreoffice
      okular
      plasma-theme-oxygen
      sddm
      wireshark
   "
   if [ -e /etc/os-release ] ; then
      . /etc/os-release
      if [ "${ID}" == "debian" ] ; then
         packages="${packages} firefox-esr"
      else
         packages="${packages} firefox"
      fi
   fi

   # shellcheck disable=SC2086
   env DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get install -y ${packages}

# ------ Fedora -------------------------------------------------------------
elif [ -e /usr/bin/dnf ] ; then
   /usr/bin/dnf install -y sddm @KDE qt5-style-oxygen oxygen-gtk2 plasma-oxygen oxygen-icon-theme oxygen-cursor-themes oxygen-sound-theme oxygen-fonts firefox

   systemctl enable sddm.service
   systemctl start sddm.service
   systemctl set-default graphical.target

# ------ FreeBSD ------------------------------------------------------------
elif [ -e /usr/sbin/pkg ] ; then
   /usr/sbin/pkg install -y firefox-esr jq kde5 noto oxygen-fonts plasma5-oxygen plasma5-sddm-kcm sddm xf86-video-vmware xorg

   sysrc dbus_enable="YES" ; service dbus start || true
   sysrc sddm_enable="YES" ; service sddm start || true


   /usr/sbin/pkg install -y R dia fractgen gimp kile libreoffice wireshark
fi
