#!/usr/bin/env bash
#
# Autoinstall Scripts
# Copyright (C) 2017-2021 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

# Bash options:
set -ex


# ====== Prepare Docker container ===========================================

# ------ Install "sudo" -----------------------------------------------------
/usr/bin/apt-get update -qq
env DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get install -y sudo

# ------ Create user --------------------------------------------------------
mkdir -p /home/${USER_NAME}
groupadd -r ${USER_NAME}
useradd -s /bin/bash \
   -c "${USER_REALNAME}" \
   -g "${USER_NAME}" \
   -d "/home/${USER_NAME}" \
   -p "${USER_PASSWORD}" \
   ${USER_NAME}
chown ${USER_NAME}:${USER_NAME} /home/${USER_NAME}
usermod -aG sudo ${USER_NAME}

# ------ Create loacles -----------------------------------------------------
env DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get install -y locales
locale-gen en_US.UTF-8 en_GB.UTF-8 en_AU.UTF-8 nb_NO.UTF-8 de_DE.UTF-8 zh_CN.UTF-8

# ------ Set time zone ------------------------------------------------------
env DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get install -y tzdata
rm -f /etc/localtime
ln -snf /usr/share/zoneinfo/UTC /etc/localtime
dpkg-reconfigure -f noninteractive tzdata

# ------ Install "systemd" --------------------------------------------------
env DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get install -y \
   systemd systemd-sysv
