#!/usr/bin/env bash
#
# Autoinstall Scripts
# Copyright (C) 2017-2025 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

# Bash options:
set -ex


# ====== OpenStack configuration ============================================

# ------ Ubuntu -------------------------------------------------------------
if [ -e /usr/bin/apt-get ] ; then
   /usr/bin/apt-get update

   # Install Cloud-Init:
   env DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get install -y cloud-init

   # Set user name in Cloud-Init's configuration file:
   # !!! Something messes up the instance on nisse, but not on odin, when
   # !!! the next line is active:
   sed -e "s/name: ubuntu/name: ${USER_NAME}/g" -e "s/lock_passwd: True/lock_passwd: False/g" \
       -i /etc/cloud/cloud.cfg

   # Password-less "sudo" for the default user:
   (
      echo "# Allow password-less sudo for ${USER_NAME}:"
      echo "${USER_NAME} ALL=(ALL) NOPASSWD:ALL"
   ) >"/etc/sudoers.d/99-${USER_NAME}"

   # Remove installer's cloud configuration settings, to make sure Cloud-Init
   # is run again during image instantiation!
   rm -f /etc/cloud/cloud.cfg.d/99-installer.cfg \
         /etc/cloud/cloud.cfg.d/curtin-preserve-sources.cfg \
         /etc/cloud/cloud.cfg.d/subiquity-disable-cloudinit-networking.cfg

# ------ Fedora -------------------------------------------------------------
elif [ -e /usr/bin/dnf ] ; then
   /usr/bin/dnf install -y cloud-init
fi
