#!/usr/bin/env bash
#
# Autoinstall Scripts
# Copyright (C) 2017-2024 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

# Bash options:
set -ex


# ====== Import public keys =================================================
# Thomas Dreibholz's public keys for verifying package and Git signatures:
KEYS="21412672518D8B2D1862EFEF5CD5D12AA0877B49"
KEYSERVERS="keyserver.ubuntu.com 162.213.33.8 162.213.33.9"
for key in ${KEYS} ; do
   foundKey=0
   # ------ First, try to fetch the key from a key server -------------------
   # GnuPG is picky with the DNS server response, and OsloMet has a lot of
   # obscure firewall rules as well => this may fail here!
   for keyServer in ${KEYSERVERS} ; do
      if sudo -u ${USER_NAME} gpg \
            --homedir /home/${USER_NAME}/.gnupg \
            --keyserver hkp://${keyServer} \
            --recv-keys ${key} ; then
         echo "Got ${key} from ${keyServer}!"
         foundKey=1
         break
      fi
   done
   # ------ If this fails, try to fetch the key from the NNTB server --------
   if [ ${foundKey} -eq 0 ] ; then
      if [ -x /usr/bin/wget ] ; then
         wget "https://www.nntb.no/~dreibh/${key}.asc" -O /tmp/${key}.asc
      else
         curl "https://www.nntb.no/~dreibh/${key}.asc" >/tmp/${key}.asc
      fi
      if sudo -u ${USER_NAME} gpg \
            --homedir /home/${USER_NAME}/.gnupg \
            --import /tmp/${key}.asc ; then
         echo "Got ${key} from NNTB web server!"
         foundKey=1
         break
      fi
   fi
   # ------ Check for success -----------------------------------------------
   if [ ${foundKey} -eq 0 ] ; then
      echo >&2 "ERROR: Unable to fetch key ${key}!"
      exit 1
   fi
done


# ====== Development configuration ==========================================

# ------ Ubuntu -------------------------------------------------------------
if [ -e /etc/apt/sources.list ] ; then
   for list in /etc/apt/sources.list `find /etc/apt/sources.list.d -name "*.list"`; do
      cat ${list} | grep "^deb \(.*\)$" | sed -e "s/deb[ \t]*//g" | xargs -n1 -i§ echo "s@^#[ \t]*deb-src \(§\)[ \t]*\$@deb-src \\1@g" >${list}.sed
      cat ${list} | sed -f ${list}.sed >${list}.new
      diff ${list} ${list}.new || true
      mv ${list}.new ${list}
      rm -f ${list}.sed
   done

   # Add commented-out debugging symbols repository:
   (
      echo ""
      echo "# Ubuntu debugging symbols repositories:"
      echo "# To install the key: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F2EDC64DC5AEE1F6B9C621F0C8CAB6595FDFF622"
      echo "# deb http://ddebs.ubuntu.com ${codename} main restricted universe multiverse"
      echo "# deb http://ddebs.ubuntu.com ${codename}-updates main restricted universe multiverse"
      echo "# deb http://ddebs.ubuntu.com ${codename}-proposed main restricted universe multiverse"
   ) >>/etc/apt/sources.list
   env DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get install -y ubuntu-dbgsym-keyring || apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F2EDC64DC5AEE1F6B9C621F0C8CAB6595FDFF622

   # Add commented-out MPTCP repository:
   codename=`lsb_release -c -s`
   (
      echo ""
      echo "# Thomas Dreibholz's MPTCP kernel repository:"

      echo "# To install the key: gpg --no-default-keyring --keyring /etc/apt/trusted.gpg.d/dreibh-nornet-kernel.gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys 21412672518D8B2D1862EFEF5CD5D12AA0877B49"
      echo "# deb [arch=amd64] https://packages.nntb.no/nornet-kernel/ubuntu/ ${codename} main"
      echo "# deb-src [arch=amd64] https://packages.nntb.no/nornet-kernel/ubuntu/ ${codename} main"
   ) >>/etc/apt/sources.list

   KEY="21412672518D8B2D1862EFEF5CD5D12AA0877B49"
   sudo -u ${USER_NAME} gpg \
      --homedir /home/${USER_NAME}/.gnupg \
      --armor \
      --export ${KEY} | apt-key add -

   # Clean up old installer files:
   rm -f /etc/apt/sources.list.curtin.old /etc/apt/sources.list.save

   /usr/bin/apt-get update
fi
