#!/usr/bin/env bash
#
# Autoinstall Scripts
# Copyright (C) 2017-2020 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

# Bash options:
set -x


# ###### Prepare source repositories ########################################

# NOTE: The repositories are not cloned here!

sudo -u nornetpp mkdir -p /home/nornetpp/src
cd /home/nornetpp/src

sudo -u nornetpp git clone https://dreibh@github.com/dreibh/fractgen.git
sudo -u nornetpp git clone https://dreibh@github.com/dreibh/netperfmeter.git
sudo -u nornetpp git clone https://dreibh@github.com/dreibh/subnetcalc.git
sudo -u nornetpp git clone https://dreibh@github.com/simula/nornet-vmimage-builder-scripts.git vmimage-builder-scripts
