#!/usr/bin/env bash
#
# Autoinstall Scripts
# Copyright (C) 2017-2022 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

# Bash options:
set -ex


# ====== Ensure that script is ran by user account to provision =============
if [ $(id -u) -eq 0 ] ; then
   # Running by configuring sudo root. Run script again, but as user!
   echo "Running as ROOT! SUDO_USER=$SUDO_USER"
   if [ "$SUDO_USER" != "root" ] ; then
      sudo -u $SUDO_USER $0 $@ && exit 0
      exit 1
   else
      # Prevent recursive invocation as "root" user:
      echo >&2 "ERROR: Run this script either as user or with sudo."
      exit 1
   fi
else
   # Echo running as user
   echo "Running as $USER! SUDO_USER=$SUDO_USER"
fi


# ====== Make some additions to .bashrc =====================================
cat >>.bashrc <<EOF

# Change prompt colours, to make it easier to notice being logged into a VM.
PS1='\${debian_chroot:+(\$debian_chroot)}\[\033[01;31m\]\u@\h\[\033[00m\]:\[\033[01;39m\]\w\[\033[00m\]\\$ '
EOF


# ====== Prepare source repositories ========================================
mkdir -p ~/src
cd ~/src

# NOTE: The repositories are not cloned here!

mkdir -p 5gvinni-oai-ns
pushd 5gvinni-oai-ns
git init
git remote add origin https://github.com/simula/5gvinni-oai-ns.git
popd
