#!/usr/bin/env bash
#
# Autoinstall Scripts
# Copyright (C) 2017-2025 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

# Bash options:
set -ex


# ====== Check/set environment variables ====================================
if [ ! -e /etc/os-release ] ; then
   echo >&2 "ERROR: /etc/os-release does not exist!"
   exit 1
fi
. /etc/os-release


# ====== Make sure that "sudo" is available =================================

# ------ Ubuntu/Debian ------------------------------------------------------
if [ "${ID}" == "ubuntu" ] || [ "${ID}" == "debian" ] ; then
   # apt-show-versions does not work with compressed indices:
   # https://askubuntu.com/questions/916199/install-apt-show-versions-inside-an-ubuntu-docker-container
   rm -f /etc/apt/apt.conf.d/docker-gzip-indexes

   /usr/bin/apt-get update -qq
   env DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get install -y sudo

# ------ Fedora -------------------------------------------------------------
elif [ "${ID}" == "fedora" ] ; then
   dnf install -y sudo
fi


# ====== Create user ========================================================
mkdir -p /home/"${USER_NAME}"
groupadd "${USER_NAME}"
useradd -s /bin/bash \
   -c "${USER_REALNAME}" \
   -g "${USER_NAME}" \
   -d "/home/${USER_NAME}" \
   -p "${USER_PASSWORD}" \
   "${USER_NAME}"
echo "${USER_NAME}:${USER_PASSWORD}" | chpasswd
chown "${USER_NAME}":"${USER_NAME}" /home/"${USER_NAME}"
if [ ! -e /usr/bin/dnf ] ; then
   # Debian/Ubuntu:
   usermod -aG sudo "${USER_NAME}"
else
   # Fedora:
   usermod -aG wheel "${USER_NAME}"
fi


# ====== Create locales and time zone data ==================================

# ------ Ubuntu/Debian ------------------------------------------------------
if [ "${ID}" == "ubuntu" ] || [ "${ID}" == "debian" ] ; then
   env DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get install -y locales tzdata
   locale-gen ar_SA.UTF-8 bs_BA.UTF-8 da_DK.UTF-8 de_AT.UTF-8 de_CH.UTF-8 de_DE.UTF-8 en_AU.UTF-8 en_DK.UTF-8 en_GB.UTF-8 en_IE.UTF-8 en_US.UTF-8 en_ZA.UTF-8 nb_NO.UTF-8 nn_NO.UTF-8 ro_RO.UTF-8 sk_SK.UTF-8 zh_CN.UTF-8

# ------ Fedora -------------------------------------------------------------
elif [ "${ID}" == "fedora" ] ; then
   dnf install -y glibc-locale-source
   localedef -v -c -i en_US -f UTF-8 en_US.UTF-8 || true
fi


# ====== Make sure that "systemctl" is available ============================

# ------ Ubuntu/Debian ------------------------------------------------------
if [ "${ID}" == "ubuntu" ] || [ "${ID}" == "debian" ] ; then
   env DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get install -y systemctl || true

# ------ Fedora -------------------------------------------------------------
elif [ "${ID}" == "fedora" ] ; then
   dnf install -y systemd
fi
