#!/usr/bin/env bash
# ==========================================================================
#  ___         _        _ _      _   _            ___         _      _
# |_ _|_ _  __| |_ __ _| | |__ _| |_(_)___ _ _   / __| __ _ _(_)_ __| |_ ___
#  | || ' \(_-<  _/ _` | | / _` |  _| / _ \ ' \  \__ \/ _| '_| | '_ \  _(_-<
# |___|_||_/__/\__\__,_|_|_\__,_|\__|_\___/_||_| |___/\__|_| |_| .__/\__/__/
#                                                              |_|
#
#   --- Virtual Machine Image Builder and System Installation Scripts ---
#            https://www.nntb.no/~dreibh/vmimage-builder-scripts/
# ==========================================================================
#
# System Installation Scripts
# Copyright (C) 2017-2026 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

# Bash options:
set -euxo pipefail


# ###### Print script name, to make Packer output easier readable ###########
if command -v figlet >/dev/null && command -v print-utf8 >/dev/null ; then
   echo
   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;32m█" "▀" "█\e[0m"
   figlet -w 156 "$(basename "$0")" | LC_ALL=C.UTF-8 print-utf8 -x 160 -n -C "\e[1;32m█\e[22m" "\e[1;32m█\e[0m"
   LC_ALL=C.UTF-8 print-utf8 -x 160 -n -s "\e[1;32m█" "▄" "█\e[0m"
else
   echo -e "\e[1;34;22m########## $(basename "$0") ##########\e[0m"
fi

# Enable printing the command-lines executed:
set -x


# ###### Main program #######################################################

# ====== Check/set environment variables ====================================
if [ ! -v USER_NAME ]     || [ "${USER_NAME}"     == "" ] || \
   [ ! -v USER_REALNAME ] || [ "${USER_REALNAME}" == "" ] || \
   [ ! -v USER_PASSWORD ] || [ "${USER_PASSWORD}" == "" ] ; then
   echo >&2 "Usage: env USER_NAME=<user> USER_REALNAME=\"<full user name>\" PASSWORD=\"<password>\" $0"
   echo >&2 "Example: sudo env USER_NAME=nornetpp USER_REALNAME=\"NorNet Praesum Presum\" \" PASSWORD=\"test\" $0"
   exit 1
fi

# ====== Obtain system details ==============================================
UNAME="$(uname)"
NAME="${UNAME}"
ID="${UNAME,,}"
VERSION="$(uname -r)"
VERSION_ID="${VERSION/_*/}"
if [ -f /etc/os-release ] ; then
   . /etc/os-release
fi


# ====== Make sure that "sudo" is available =================================

# ------ Ubuntu/Debian ------------------------------------------------------
if [ "${ID}" == "ubuntu" ] || [ "${ID}" == "debian" ] ; then
   # apt-show-versions does not work with compressed indices:
   # https://askubuntu.com/questions/916199/install-apt-show-versions-inside-an-ubuntu-docker-container
   rm -f /etc/apt/apt.conf.d/docker-gzip-indexes

   apt-get update -qq
   env DEBIAN_FRONTEND=noninteractive apt-get install -y sudo

# ------ Fedora -------------------------------------------------------------
elif [ "${ID}" == "fedora" ] ; then
   dnf install --setopt=install_weak_deps=False -y sudo

# ------ OpenSUSE -----------------------------------------------------------
elif [[ "${ID}" =~ ^opensuse- ]] ; then

   zypper --non-interactive install --no-recommends -y bash sudo

# ------ Alpine -------------------------------------------------------------
elif [ "${ID}" == "alpine" ] ; then

   apk add bash doas shadow sudo

# ------ Unknown ------------------------------------------------------------
else

   echo >&2 "ERROR: Unknown ID ${ID} in /etc/os-release. The installation script may need an update for supporting this system!"
   exit 1

fi


# ====== Create user ========================================================
mkdir -p "/home/${USER_NAME}"
groupadd "${USER_NAME}"
useradd -s /bin/bash \
   -c "${USER_REALNAME}" \
   -g "${USER_NAME}" \
   -d "/home/${USER_NAME}" \
   -p "${USER_PASSWORD}" \
   "${USER_NAME}"
echo "${USER_NAME}:${USER_PASSWORD}" | chpasswd
chown "${USER_NAME}:${USER_NAME}" "/home/${USER_NAME}"
if [ "${ID}" == "ubuntu" ] || [ "${ID}" == "debian" ] ; then
   # Debian/Ubuntu: group is "sudo"
   usermod -aG sudo "${USER_NAME}"
elif [ "${ID}" == "fedora" ] ; then
   # Fedora: group is "wheel"
   usermod -aG wheel "${USER_NAME}"
elif [[ "${ID}" =~ ^opensuse- ]] ; then
   usermod -aG wheel "${USER_NAME}"
elif [ "${ID}" == "alpine" ] ; then
   echo 'permit nopass :wheel' >/etc/doas.d/wheel.conf
   addgroup sudo
   usermod -a -G sudo "${USER_NAME}"
   sed -e 's/^# %sudo /%sudo /' -i /etc/sudoers
   usermod -aG wheel "${USER_NAME}"
fi


# ====== Make sure that "systemctl" is available ============================

# ------ Ubuntu/Debian ------------------------------------------------------
if [ "${ID}" == "ubuntu" ] || [ "${ID}" == "debian" ] ; then
   env DEBIAN_FRONTEND=noninteractive apt-get install -y systemctl || true

# ------ Fedora -------------------------------------------------------------
elif [ "${ID}" == "fedora" ] ; then
   dnf install --setopt=install_weak_deps=False -y systemd
fi
