#!/usr/bin/env bash
#
# Autoinstall Scripts
# Copyright (C) 2017-2020 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

# Bash options:
set -ex


UNAME="`uname`"


# ====== Set timezone =======================================================
if [ "${UNAME}" == "Linux" ] ; then
   if [ -x /usr/bin/timedatectl ] ; then
      /usr/bin/timedatectl set-timezone Europe/Oslo
   else
      # ------ Old Ubuntu (12.04 etc.) -----------------------
      if [ ! -e /usr/bin/apt ] ; then
         echo "Europe/Oslo" >/etc/timezone
         dpkg-reconfigure -f noninteractive tzdata
      fi
   fi
fi


# ====== Set sysctls ========================================================
if [ "${UNAME}" == "Linux" ] ; then
   cat >>/etc/sysctl.conf <<EOF

###################################################################

# ------ Custom settings ------------------------------------------
# Enable ECN:
net.ipv4.tcp_ecn=1

# ------ TCP settings ---------------------------------------------
# Turn off auto-tuning of the TCP receive buffer size:
# sysctl -w net.ipv4.tcp_moderate_rcvbuf=0
# sysctl -w net.netfilter.nf_conntrack_icmp_timeout=60

# sysctl -w net.core.rmem_default=212992
# sysctl -w net.core.rmem_max=134217728
# sysctl -w net.core.wmem_default=212992
# sysctl -w net.core.wmem_max=134217728
# sysctl -w net.ipv4.tcp_rmem='4096 87380 134217728'
# sysctl -w net.ipv4.tcp_wmem='4096 16384 134217728'
# sysctl -w net.ipv4.tcp_mem='134217728 134217728 134217728'
# sysctl -w net.ipv4.route.flush=1
# sysctl -w net.ipv6.route.flush=1

# ----- MPTCP settings ------------------------------------------------------
# sysctl -w net.mptcp.mptcp_enabled=1
# sysctl -w net.mptcp.mptcp_path_manager=fullmesh
EOF

elif [ "${UNAME}" == "FreeBSD" ] ; then
   cat >>/etc/sysctl.conf <<EOF

###################################################################

# ------ Custom settings ------------------------------------------
# Enable ECN:
net.inet.tcp.ecn.enable=1
EOF

fi


# ====== Make some additions to .bashrc =====================================
cat >>/home/${USER_NAME}/.bashrc <<EOF


# ---------------------------------------------------------------------------

alias runws="sudo echo Starting Wireshark && ( sudo wireshark & )"

ulimit -c unlimited

export EDITOR=joe
export CVSEDITOR=\${EDITOR}
export SVN_EDITOR=\${EDITOR}
export XZ_DEFAULTS="--threads=0"

cores=\`getconf _NPROCESSORS_ONLN 2>/dev/null || true\`
if [ \$cores -gt 1 ] ; then
   export MAKEFLAGS=-j\${cores}
fi
EOF


# ====== Make some directories ==============================================
sudo -u ${USER_NAME} mkdir -p /home/${USER_NAME}/src
sudo -u ${USER_NAME} chattr +c /home/${USER_NAME}/src || true
sudo -u ${USER_NAME} mkdir -p /home/${USER_NAME}/tmp

sudo -u ${USER_NAME} mkdir -p /home/${USER_NAME}/.ssh
sudo -u ${USER_NAME} chmod 700 /home/${USER_NAME}/.ssh
sudo -u ${USER_NAME} touch /home/${USER_NAME}/.ssh/authorized_keys
sudo -u ${USER_NAME} chmod 600 /home/${USER_NAME}/.ssh/authorized_keys


# ====== Renew SSH keys and enforce strong cipher configurations ============
if [ -e /usr/bin/Create-New-SSH-Node-Keys ] ; then
   /usr/bin/Create-New-SSH-Node-Keys -yes-to-all-i-am-really-sure
fi
