#!/bin/sh
# FreeBSD Autoinstall Configuration
# Copyright (C) 2024 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

set -ex

# NOTE:
# This script is a simple work-around to customise the partitioning in
# bsdinstall. Instead of running zfsboot to the default ZFS installation,
# it runs a custom partitioning script.

# /usr/libexec/bsdinstall is read-only on a CD-ROM: Copy everything into
# a tmpfs.
cp -a /usr/libexec/bsdinstall/ /tmp/bsdinstall/
mount -t tmpfs none /usr/libexec/bsdinstall
cp -a /tmp/bsdinstall/ /usr/libexec/bsdinstall/

# /usr/libexec/bsdinstall (tmpfs) is now writable:
mv /usr/libexec/bsdinstall/zfsboot /usr/libexec/bsdinstall/zfsboot.orig
cp zfsboot /usr/libexec/bsdinstall/

# Now, it is possible to run the FreeBSD installer:
bsdinstall $@
