#!/bin/sh -x

# ###### Partitioning #######################################################

# ====== Find disks =========================================================
DISK_ROOT=""
for d in ada1 da1 vtbd1; do
  if [ -e "/dev/$d" ]; then
    export DISK_ROOT=$d
    break
  fi
done
if [ "$DISK_ROOT" == "" ] ; then
   echo >&2 "ERROR: Root disk not found!"
   exit 1
fi

DISK_HOME=""
for d in ada2 da2 vtbd2; do
  if [ -e "/dev/$d" ]; then
    export DISK_HOME=$d
    break
  fi
done
if [ "$DISK_HOME" == "" ] ; then
   echo >&2 "ERROR: Home disk not found!"
   exit 1
fi

DISK_SWAP=""
for d in ada3 da3 vtbd3; do
  if [ -e "/dev/$d" ]; then
    export DISK_SWAP=$d
    break
  fi
done
if [ "$DISK_SWAP" == "" ] ; then
   echo >&2 "ERROR: Swap disk not found!"
   exit 1
fi

echo "root=$DISK_ROOT home=$DISK_HOME swap=$DISK_SWAP"


# ====== Prepare root disk ==================================================
zpool destroy zrootXXXX 2>/dev/null || true
gpart delete -i 2 $DISK_ROOT 2>/dev/null || true
gpart delete -i 1 $DISK_ROOT 2>/dev/null || true
gpart destroy -F $DISK_ROOT  2>/dev/null || true

gpart create -s gpt $DISK_ROOT
gpart add -a 4k -s 64M -t efi  -l EFI  $DISK_ROOT
gnop create -S 4096 /dev/gpt/EFI
gpart add -a 4k -t freebsd-zfs -l Root $DISK_ROOT
gnop create -S 4096 /dev/gpt/Root

# ------ Create EFI Boot ----------------------------------------------------
newfs_msdos -F 32 -c 1 /dev/gpt/EFI
mount -t msdosfs -o longnames /dev/gpt/EFI /mnt
mkdir -p /mnt/EFI/BOOT
cp /boot/loader.efi /mnt/EFI/BOOT/BOOTX64.efi

# ------ Create ZFS Root ----------------------------------------------------
zpool create -f -o altroot=/mnt -o cachefile=/var/tmp/zpool.cache zrootXXXX /dev/gpt/Root.nop

# ------ Configure ZFS Root -------------------------------------------------
# -> https://wiki.freebsd.org/RootOnZFS/GPTZFSBoot
zfs set compress=on                                            zrootXXXX

zfs create -o mountpoint=none                                  zrootXXXX/ROOT
zfs create -o mountpoint=none                                  zrootXXXX/ROOT/default
mount -t tmpfs tmpfs /mnt
mount -t zfs zrootXXXX/ROOT/default /mnt

zfs create -o mountpoint=/tmp  -o exec=on      -o setuid=off   zrootXXXX/tmp
zfs create -o canmount=off -o mountpoint=/usr                  zrootXXXX/usr
# zfs create                                                   zrootXXXX/usr/home
zfs create                     -o exec=off     -o setuid=off   zrootXXXX/usr/src
zfs create                                                     zrootXXXX/usr/obj
zfs create -o mountpoint=/usr/ports            -o setuid=off   zrootXXXX/usr/ports
zfs create                     -o exec=off     -o setuid=off   zrootXXXX/usr/ports/distfiles
zfs create                     -o exec=off     -o setuid=off   zrootXXXX/usr/ports/packages
zfs create -o canmount=off -o mountpoint=/var                  zrootXXXX/var
zfs create                     -o exec=off     -o setuid=off   zrootXXXX/var/audit
zfs create                     -o exec=off     -o setuid=off   zrootXXXX/var/crash
zfs create                     -o exec=off     -o setuid=off   zrootXXXX/var/log
zfs create -o atime=on         -o exec=off     -o setuid=off   zrootXXXX/var/mail
zfs create                     -o exec=on      -o setuid=off   zrootXXXX/var/tmp

ln -s /usr/home /mnt/home
chmod 1777 /mnt/var/tmp
chmod 1777 /mnt/tmp

zpool set bootfs=zrootXXXX/ROOT/default zrootXXXX


# ====== Prepare home disk ==================================================
zpool destroy zhomeYYYY 2>/dev/null || true
gpart delete -i 1 $DISK_HOME 2>/dev/null || true
gpart destroy -F $DISK_HOME  2>/dev/null || true

gpart create -s gpt $DISK_HOME
gpart add -a 4k -t freebsd-zfs -l Home $DISK_HOME
gnop create -S 4096 /dev/gpt/Home

zpool create -f -o altroot=/mnt/usr/home -o cachefile=/var/tmp/zpool.cache zhomeYYYY /dev/gpt/Home.nop

# ------ Configure home -----------------------------------------------------
# -> https://wiki.freebsd.org/RootOnZFS/GPTZFSBoot
zfs set compress=on                                            zhomeYYYY

zfs create -o mountpoint=none                                  zhomeYYYY/HOME
zfs create -o mountpoint=none                                  zhomeYYYY/HOME/default

zfs create                                                     zhomeYYYY/home


# ====== Prepare swap disk ==================================================
gpart delete -i 1 $DISK_SWAP 2>/dev/null || true
gpart destroy -F $DISK_SWAP  2>/dev/null || true

gpart create -s gpt $DISK_SWAP
gpart add -a 4k -t freebsd-swap -l Swap $DISK_SWAP
gnop create -S 4096 /dev/gpt/Swap


# ====== Create fstab =======================================================
cat <<EOF >/tmp/bsdinstall_etc/fstab
# Device          Mountpoint     FStype    Options     Dump     Pass#
/dev/gpt/Swap     none           swap      sw          0        0
EOF

# ====== Checks =============================================================
camcontrol devlist
gpart show -p $DISK_ROOT
gpart show -p $DISK_HOME
gpart show -p $DISK_SWAP
zpool list
