System hostname = <SET_HOSTFQDN_HERE>
Which network interface do you wish to configure = em0
IPv4 address for em0 = dhcp
IPv6 address for em0 = none
Which network interface do you wish to configure = done
Password for root account = <SET_PASSWORD_HERE>
Start sshd(8) by default = yes
Allow root ssh login = prohibit-password
Do you expect to run the X Window System = no
What timezone are you in = Etc/UTC
Location of sets = http
Http server = cdn.openbsd.org
