# ====== System setup =======================================================
System hostname = <SET_HOSTFQDN_HERE>
Choose your keyboard layout = <SET_XKBLAYOUT_HERE>
Use (W)hole disk MBR, whole disk (G)PT, (O)penBSD area or (E)dit? = G
An EFI/GPT disk may not boot. Proceed? = yes
URL to autopartitioning template for disklabel = file:/tmp/autoinstall/disk-layout.template
Which network interface do you wish to configure = em0
IPv4 address for em0 = dhcp
IPv6 address for em0 = none
Which network interface do you wish to configure = done
Password for root account = <SET_PASSWORD_HERE>
Start sshd(8) by default = yes
Allow root ssh login = prohibit-password
Do you expect to run the X Window System = no
What timezone are you in = Etc/UTC

# ====== Installation of the system =========================================
Location of sets = http
Http server = cdn.openbsd.org
Set name(s) = done

# ====== Installation of site<VERSION>.tgz ==================================
Location of sets = disk
Is the disk partition already mounted? = yes
Pathname to the sets = ../tmp/autoinstall
Directory does not contain SHA256.sig. Continue without verification? = yes
Use sets found here anyway? = yes
Set name(s) = site<VERSION>.tgz
Set name(s) = done

# ====== Installation finished ==============================================
Location of sets = done

# ====== Create user account ================================================
Setup a user = <SET_USERNAME_HERE>
Full name for user <SET_USERNAME_HERE> = <SET_REALNAME_HERE>
Password for user <SET_USERNAME_HERE> = <SET_PASSWORD_HERE>
Public ssh key for user <SET_USERNAME_HERE> = none
